#!/usr/bin/env bash
# apply.sh -- graft the FujiNet cartridge device into a MAME tree.
#
# Usage: ./apply.sh [/path/to/mame]      default: ~/Workspace/mame
#
# Copies the device model (fujinet.cpp/h, fujitcp.c/h) and the cartridge
# firmware's own sources (fujimail, fujibus, the bus decode, the glyph
# compositor and their headers -- so MAME runs the code the cartridge actually
# ships, not a lookalike) into src/devices/bus/vcs/, and makes two shared-file
# edits:
#
#   scripts/src/bus.lua              the VCS file list
#   src/mame/atari/a2600.cpp         the slot option and its include
#
# Idempotent, and every edit is anchored: if MAME moves an anchor this exits
# nonzero rather than half-patching.
#
# WHAT IS DELIBERATELY NOT PATCHED. vcs_cart_slot_device::call_load() rejects
# any image whose size is not on a hard whitelist (0x800, 0x1000, 0x2000,
# 0x28ff, 0x2900, 0x3000, 0x4000, 0x8000, 0x10000, 0x80000). A FujiNet client
# is (N+1) * 2048 bytes -- N banks plus the fixed half -- and N in {1,3,7,15}
# gives exactly 4K, 8K, 16K and 32K, all whitelisted. So the constraint costs
# nothing and the whitelist stays untouched: every core file this script edits
# is one more thing that breaks silently on a MAME upgrade, and tools/checkrom.py
# enforces the size on our side where it belongs.
#
# Afterwards: make -C /path/to/mame -j$(nproc) NOWERROR=1 REGENIE=1
# (REGENIE=1 is required the first time, because bus.lua changed. Re-run THIS
# script after every edit to a shared source -- MAME builds the copies.)

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:-$HOME/Workspace/mame}
BUSDIR="$MAME/src/devices/bus/vcs"
BUSLUA="$MAME/scripts/src/bus.lua"
DRIVER="$MAME/src/mame/atari/a2600.cpp"

[ -d "$BUSDIR" ] || { echo "apply.sh: $BUSDIR missing" >&2; exit 1; }
[ -f "$DRIVER" ] || { echo "apply.sh: $DRIVER missing" >&2; exit 1; }

# The shared sources are C, but MAME's device project forces a C++ precompiled
# header on every file it owns, so they are copied in under .cpp names and
# compiled as C++ (they are written to build both ways).
cp fujinet.cpp fujinet.h fujitcp.h "$BUSDIR/"
cp fujitcp.c "$BUSDIR/fujitcp.cpp"
cp ../firmware/src/fujimail.c "$BUSDIR/fujimail.cpp"
cp ../firmware/src/fujibus.c "$BUSDIR/fujibus.cpp"
cp ../firmware/src/vcs_render.c "$BUSDIR/vcs_render.cpp"
cp ../firmware/include/fujimail.h ../firmware/include/fujibus.h \
   ../firmware/include/fuji_mailbox.h ../firmware/include/vcs_cart.h \
   ../firmware/include/vcs_render.h ../firmware/include/vcs_font.h \
   ../firmware/include/vcsmap.h \
   "$BUSDIR/"
rm -f "$BUSDIR/fujitcp.c" "$BUSDIR/fujimail.c" "$BUSDIR/fujibus.c" \
      "$BUSDIR/vcs_render.c"

# Rename every shared symbol, because more than one of these cartridges can be
# grafted into the same MAME tree at once.
#
# fujimail.c, fujibus.c and fujitcp.c are byte-identical across the Astrocade,
# Arcadia, ColecoVision, Channel F and 2600 ports -- that is the whole point of
# sharing them -- but each copy is compiled against its OWN fuji_mailbox.h,
# where FN_R_MAGIC0 is 0x1C09 on one platform and 0x1F09 here. With several
# grafted, the linker picks one definition of fujimail_paint() for the whole
# binary and the others silently paint the wrong offsets: the cartridge
# answers, the socket connects, and the client reads $FF forever. Prefixing
# makes the collision impossible instead of merely unlikely.
cat > "$BUSDIR/fujins.h" <<'NSEOF'
/* GENERATED by pico/atari-2600/emu/apply.sh -- do not edit.
 *
 * Give this port's copies of the shared sources their own symbols, so several
 * FujiNet cartridges can live in one MAME binary. See apply.sh. */
#ifndef A2600_FUJINS_H
#define A2600_FUJINS_H
NSEOF
for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
           fujibus_build_request fujibus_parse_reply fujibus_selftest \
           fujitcp_init fujitcp_active fujitcp_close fujitcp_transact \
           fujitcp_send_bare \
           vcs_render_row vcs_render_clear vcs_font; do
    echo "#define $sym a2600_$sym" >> "$BUSDIR/fujins.h"
done
echo "#endif" >> "$BUSDIR/fujins.h"

# Inject the include as the first line of every copied shared file, so the
# renames reach declarations and definitions alike.
for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h \
         vcs_render.cpp vcs_render.h vcs_font.h; do
    if ! head -1 "$BUSDIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$BUSDIR/$f")" > "$BUSDIR/$f.tmp"
        mv "$BUSDIR/$f.tmp" "$BUSDIR/$f"
    fi
done

# bus.lua: add our files to the VCS block, once.
if ! grep -q 'vcs/fujinet.cpp' "$BUSLUA"; then
    python3 - "$BUSLUA" <<'EOF'
import sys

path = sys.argv[1]
text = open(path).read()
anchor = '\t\tMAME_DIR .. "src/devices/bus/vcs/rom.h",\n'
if anchor not in text:
    sys.exit("apply.sh: bus.lua VCS anchor line not found")
addition = anchor + "".join(
    '\t\tMAME_DIR .. "src/devices/bus/vcs/%s",\n' % f
    for f in ("fujinet.cpp", "fujinet.h", "fujitcp.cpp", "fujitcp.h",
              "fujimail.cpp", "fujimail.h", "fujibus.cpp", "fujibus.h",
              "vcs_render.cpp", "vcs_render.h", "vcs_font.h", "vcsmap.h",
              "fuji_mailbox.h", "vcs_cart.h", "fujins.h"))
open(path, "w").write(text.replace(anchor, addition, 1))
EOF
    echo "apply.sh: bus.lua updated (build with REGENIE=1)"
fi

# a2600.cpp: the include and the slot option.
if ! grep -q 'A26_ROM_FUJINET' "$DRIVER"; then
    python3 - "$DRIVER" <<'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

inc_anchor = '#include "bus/vcs/rom.h"\n'
if inc_anchor not in text:
    sys.exit("apply.sh: a2600.cpp include anchor not found")
text = text.replace(inc_anchor, '#include "bus/vcs/fujinet.h"\n' + inc_anchor, 1)

# The slot option list. Ours is added explicitly and is never auto-detected:
# identify_cart_type() would size-match a FujiNet client to a stock ROM type,
# so the client is always selected with -cartslot fujinet.
opt_anchor = '\tdevice.option_add("a26_2k_4k", A26_ROM_2K_4K);\n'
if opt_anchor not in text:
    sys.exit("apply.sh: a2600.cpp slot option anchor not found")
text = text.replace(opt_anchor,
                    opt_anchor + '\tdevice.option_add("fujinet",   A26_ROM_FUJINET);\n', 1)

open(path, "w").write(text)
EOF
    echo "apply.sh: a2600.cpp updated"
fi

echo "apply.sh: grafted into $MAME"
echo "  build:  make -C $MAME -j\$(nproc) NOWERROR=1 REGENIE=1"
echo "  run:    ./run.sh fujitest  (SLOT=fujinet)"
