#!/usr/bin/env bash
# build.sh -- assemble the Atari 2600 console clients with Macroassembler AS.
#
# Usage: ./build.sh [client ...]        default: hello
#
# Output: build/<client>.bin. MAME's vcs_cart_slot_device::call_load() rejects
# any image whose size is not on its whitelist (0x800, 0x1000, 0x2000, 0x28ff,
# 0x2900, 0x3000, 0x4000, 0x8000, 0x10000, 0x80000), so every image this
# builds is exactly 4096 bytes for now -- a flat client, one bank plus the
# fixed half. Banked clients are (N+1)*2048 and pick the whitelisted sizes.
#
# AS rather than dasm: dasm is not installed and cannot be fetched here, while
# AS is already the family's assembler (o2/8048, arcadia/2650, channelf/F8),
# already supports 6502, and CI already caches its build. testrom/vcs.inc is
# written from the hardware register map rather than copied from the dasm
# world's vcs.h, which is explicitly not redistributable.

set -euo pipefail
cd "$(dirname "$0")"

if command -v asl >/dev/null 2>&1; then
    AS=asl P2BIN=p2bin
elif [ -x "$HOME/asl/asl" ]; then
    AS="$HOME/asl/asl" P2BIN="$HOME/asl/p2bin"
else
    echo "build.sh: no Macroassembler AS found (tried PATH and ~/asl)" >&2
    exit 1
fi

mkdir -p build

# The client's equates are hand-mirrored from the firmware header. Check them
# before assembling anything: a drifted address assembles cleanly, runs, and
# silently talks to a page that decodes nothing.
python3 tools/checkdefs.py firmware/include/fuji_mailbox.h testrom/fujinet.inc

# The M0 screen. Regenerated every run so a stale render cannot survive a font
# or geometry change -- and it comes from tools/vcsfont.py, the same reference
# renderer host_test/test_render.c will be byte-compared against.
gen_screen() {
    python3 tools/vcsfont.py --screen-file testrom/screen.txt > testrom/screen.inc
}

# The claim. An image carrying "FUJI" at FN_R_CLAIM promises the mailbox pages
# are not its own code, so the cartridge keeps decoding after it boots. For a
# 4K image the window maps linearly, so the image offset is the console address
# minus $1000.
CLAIM_OFF=$((0x0F10))

# fujiboot's target, regenerated every run so a stale value cannot survive an
# environment change.
gen_bootcfg() {
    {
        echo "; generated by build.sh -- do not edit"
        echo "BOOTHST EQU     ${BOOT_HOST:-0}"
        printf 'BOOTPTH:DB      "%s"\n' "${BOOT_PATH:-/vcsgame.bin}"
        echo "        DB      0"
    } > testrom/bootcfg.inc
}

build_one() {
    local name=$1
    # Only the M0 client bakes a screen; everything after it renders at run
    # time, through the cartridge.
    # `[ ... ] && cmd` would return nonzero when the test fails, and under
    # `set -e` that aborts the function. Use a real if.
    if [ "$name" = hello ]; then gen_screen; fi
    if [ "$name" = fujiboot ]; then gen_bootcfg; fi
    # AS resolves INCLUDE against the cwd, so assemble from testrom/.
    (cd testrom && $AS -q -L "$name.asm")
    mv "testrom/$name.p" "build/$name.p"
    mv -f "testrom/$name.lst" "build/$name.lst" 2>/dev/null || true
    $P2BIN "build/$name.p" "build/$name.bin" -r '$1000-$1FFF' -l 0
    rm -f "build/$name.p"
    printf 'FUJI' | dd of="build/$name.bin" bs=1 seek=$CLAIM_OFF \
        conv=notrunc status=none
    python3 tools/checkrom.py "build/$name.bin"
    echo "build/$name.bin: $(stat -c%s "build/$name.bin") bytes"
}

clients=("$@")
[ ${#clients[@]} -eq 0 ] && clients=(hello fujitest fujiboot fujidir)
for client in "${clients[@]}"; do
    build_one "$client"
done
