#!/usr/bin/env bash
# build.sh -- the 1802 side: the bring-up clients, with Macroassembler AS.
# Everything lands in build/.
#
#   ./build.sh                    every client
#   ./build.sh fujiboot           just one
#   BOOT_HOST=0 BOOT_PATH=/x.st2 ./build.sh fujiboot
#
# Each client is build/<name>.st2: what the cart serves (run.sh hands it to
# MAME's device as $FUJINET_BOOT). AS runs case-sensitive (-U): fn_frames is
# not FN_FRAMES.
set -euo pipefail
cd "$(dirname "$0")"

ASL=${ASL:-$HOME/asl/asl}
[ -x "$ASL" ] || ASL=$(command -v asl) || { echo "build.sh: no asl (Macroassembler AS)" >&2; exit 1; }
mkdir -p build/gen build/obj

cat > build/gen/bootcfg.inc <<EOC
; GENERATED by build.sh -- do not edit.
BOOTHST EQU     ${BOOT_HOST:-0}
BOOTPATH MACRO
        DB      "${BOOT_PATH:-/soak.st2}", 0
        ENDM
EOC
python3 tools/checkdefs.py

build_one() {
    local name=$1
    [ -f "testrom/$name.asm" ] || { echo "no testrom/$name.asm" >&2; exit 1; }
    (cd testrom && "$ASL" -q -U -L -i . -i ../build/gen -o "../build/obj/$name.p" \
        -olist "../build/obj/$name.lst" "$name.asm")
    python3 tools/checkrom.py "build/obj/$name.lst"
    python3 tools/mkst2.py "build/obj/$name.p" "build/$name.st2"
}

targets=("$@")
if [ ${#targets[@]} -eq 0 ]; then
    targets=(hello fujitest)
    [ -f testrom/fujiboot.asm ] && targets+=(fujiboot)
fi
for t in "${targets[@]}"; do
    build_one "$t"
done
