#ifndef ATASCII_H
#define ATASCII_H

#define ATASCII_ESCAPE 0x1B
#define ATASCII_CURSOR_UP 0x1C
#define ATASCII_CURSOR_DOWN 0x1D
#define ATASCII_CURSOR_LEFT 0x1E
#define ATASCII_CURSOR_RIGHT 0x1F
#define ATASCII_CLEAR_SCREEN 0x7D
#define ATASCII_BACKSPACE 0x7E
#define ATASCII_TAB 0x7F
#define ATASCII_EOL 0x9B
#define ATASCII_DELETE_LINE 0x9C
#define ATASCII_INSERT_LINE 0x9D
#define ATASCII_CTRL_TAB 0x9E
#define ATASCII_SHIFT_TAB 0x9F
#define ATASCII_BELL 0xFD
#define ATASCII_DELETE_CHAR 0xFE
#define ATASCII_INSERT_CHAR 0xFF

#define ASCII_BELL 0x07
#define ASCII_BACKSPACE 0x08
#define ASCII_TAB 0x09
#define ASCII_LF 0x0A
#define ASCII_CR 0x0D
#define ASCII_DELETE 0x7F

#define ASCII_CRLF "\r\n"

#define ATASCII_REMOVE_INVERSE(X) (X & 127)

#endif // ATASCII_H
