/* GENERATED by pico/atari-5200/tools/mkmapdb.py from MAME hash/a5200.xml and hash/a5200.hsi (CC0-1.0) and tools/corpus.tsv -- do not edit. */

#include "a52map_db.h"

const a52map_db_t a52map_db[] = {
    { 0x01E6EA2Du, A52MAP_ROM },  /* Robotron 2084 (USA) (Beta) (1983-10-12) (mame) */
    { 0x037157F9u, A52MAP_ROM },  /* Last Starfighter, The (USA) (Proto) (1984-05-08) (mame) */
    { 0x041AD5B3u, A52MAP_2CHIPS },  /* RealSports Soccer (USA) (Beta) (1982-08-26) (mame) */
    { 0x04807705u, A52MAP_2CHIPS },  /* buckrog */
    { 0x04B299A4u, A52MAP_2CHIPS },  /* friskyt */
    { 0x0624E6E7u, A52MAP_ROM },  /* blueprnt */
    { 0x063EC2C4u, A52MAP_ROM },  /* gremlins */
    { 0x0675F0A5u, A52MAP_ROM },  /* jedidsb */
    { 0x09FC7648u, A52MAP_ROM },  /* riveraid */
    { 0x0A4DDB1Eu, A52MAP_ROM },  /* spacman */
    { 0x0AF19345u, A52MAP_2CHIPS },  /* frogger2 */
    { 0x0BA22ECEu, A52MAP_ROM },  /* trackfld */
    { 0x0DE2DB48u, A52MAP_ROM },  /* 5200menu */
    { 0x0F24243Cu, A52MAP_ROM },  /* mking */
    { 0x0F996184u, A52MAP_2CHIPS },  /* rsbasket2 */
    { 0x0FE438B3u, A52MAP_2CHIPS },  /* Frogger 2 - Threedeep! (Parker Brothers) (PAL) (.hsi) */
    { 0x10F33C90u, A52MAP_2CHIPS },  /* rstennis */
    { 0x1187342Fu, A52MAP_ROM },  /* tempest */
    { 0x132EED8Eu, A52MAP_2CHIPS },  /* Stargate (USA) (Proto 1) (1983-11-21) (mame) */
    { 0x15B7B5EFu, A52MAP_ROM },  /* poleposp */
    { 0x16608C3Eu, A52MAP_ROM },  /* 3-D Asteroids (USA) (Demo) (mame) */
    { 0x18417ADAu, A52MAP_ROM },  /* astrgrvr */
    { 0x18A73AF3u, A52MAP_ROM },  /* hero */
    { 0x18E0793Fu, A52MAP_ROM },  /* Spitfire (USA) (Proto) (1983-09-30) (size) */
    { 0x1A67A0F5u, A52MAP_2CHIPS },  /* Stargate (USA) (Proto 2) (1984-01-13) (mame) */
    { 0x1AA94FECu, A52MAP_ROM },  /* Meebzork (USA) (Proto) (1983-11-16) (size) */
    { 0x1CF10560u, A52MAP_ROM },  /* Vanguard (USA) (Beta) (1983-02-01) (size) */
    { 0x1D1CEE27u, A52MAP_2CHIPS },  /* stargate */
    { 0x1D544455u, A52MAP_ROM },  /* Asteroids (USA) (Proto) (Final) (size) */
    { 0x200578DDu, A52MAP_2CHIPS },  /* Choplifter! (USA) (Beta 1) (1984-01-04) (mame) */
    { 0x20DF4927u, A52MAP_2CHIPS },  /* Buck Rogers - Planet of Zoom (Sega) (PAL) (.hsi) */
    { 0x21D19C8Fu, A52MAP_ROM },  /* Barroom Baseball (USA) (Proto 1) (size) */
    { 0x22ABBBC7u, A52MAP_ROM },  /* James Bond 007 (USA) (Beta) (mame) */
    { 0x23C21720u, A52MAP_ROM },  /* Frisky Tom (USA) (Proto) (1983-01-20) (size) */
    { 0x240A1E1Au, A52MAP_ROM },  /* megmania */
    { 0x28278CD6u, A52MAP_ROM },  /* petetest */
    { 0x28A0BEF6u, A52MAP_ROM },  /* Moon Patrol (USA) (Beta 4) (size) */
    { 0x29178296u, A52MAP_2CHIPS },  /* Xari Arena (USA) (Proto) (1983-09-20) (mame) */
    { 0x2959D827u, A52MAP_ROM },  /* zonerngr */
    { 0x2A640143u, A52MAP_2CHIPS },  /* montezum */
    { 0x2C676662u, A52MAP_2CHIPS },  /* jungleh */
    { 0x3015BB24u, A52MAP_2CHIPS },  /* Space Dungeon (USA) (Beta) (1983-01-20) (mame) */
    { 0x33B70206u, A52MAP_ROM },  /* Star Trek - Strategic Operations Simulator (USA) (Alt) (trace) */
    { 0x35484751u, A52MAP_ROM },  /* aep */
    { 0x382634DCu, A52MAP_ROM },  /* xevious */
    { 0x38480891u, A52MAP_ROM },  /* asteroid */
    { 0x387365DCu, A52MAP_ROM },  /* shuttle */
    { 0x38A8AFA9u, A52MAP_2CHIPS },  /* Microgammon SB (USA) (Proto) (1983-08-15) (mame) */
    { 0x3A6E6133u, A52MAP_ROM },  /* Galaxian (USA) (Alt) (size) */
    { 0x3BD5FDD6u, A52MAP_ROM },  /* boogie */
    { 0x3C311303u, A52MAP_ROM },  /* spitfire */
    { 0x3D75D4DCu, A52MAP_2CHIPS },  /* Realsports Soccer (Atari) (U) [a1] (.hsi) */
    { 0x3DA972C8u, A52MAP_ROM },  /* Atari PAM Diagnostics (USA) (v1.1) (size) */
    { 0x3EF4A23Fu, A52MAP_ROM },  /* galaxian */
    { 0x3FE4A401u, A52MAP_ROM },  /* qbert */
    { 0x4019ECECu, A52MAP_2CHIPS },  /* achase */
    { 0x40657C26u, A52MAP_2CHIPS },  /* Black Belt (USA) (Proto 1) (trace) */
    { 0x408D29DEu, A52MAP_2CHIPS },  /* Joust (USA) (Beta) (1983-06-12) (mame) */
    { 0x420F5D0Bu, A52MAP_ROM },  /* kaboom */
    { 0x4241582Du, A52MAP_2CHIPS },  /* Gyruss (USA) (Rev 1) (mame) */
    { 0x4248D3E3u, A52MAP_ROM },  /* [BIOS] Atari 5200 (USA) (size) */
    { 0x4252ABD9u, A52MAP_ROM },  /* robotron */
    { 0x4336C2CCu, A52MAP_2CHIPS },  /* rsfootb */
    { 0x44166592u, A52MAP_ROM },  /* rsbaseb */
    { 0x44D3FF6Fu, A52MAP_ROM },  /* missile */
    { 0x460DEF2Du, A52MAP_ROM },  /* dfactor */
    { 0x4B910461u, A52MAP_ROM },  /* pitfall2 */
    { 0x4BAC5DD9u, A52MAP_2CHIPS },  /* Star Raiders (USA) (Alt) (mame) */
    { 0x5342A8B4u, A52MAP_ROM },  /* Xari Arena (USA) (Proto) (1983-08-31) (size) */
    { 0x536A70FEu, A52MAP_2CHIPS },  /* centiped */
    { 0x565F3E21u, A52MAP_ROM },  /* Spitfire (USA) (Proto) (1983-10-13) (size) */
    { 0x573F8FD1u, A52MAP_ROM },  /* Dig Dug (USA) (Beta) (1983-04-07) (size) */
    { 0x57E7945Eu, A52MAP_BBSB },  /* Bounty Bob (Big Five Software) (U) (.hsi) */
    { 0x59983C40u, A52MAP_2CHIPS },  /* jrpacman */
    { 0x63E81003u, A52MAP_ROM },  /* Dig Dug (USA) (Beta) (1983-06-20) (size) */
    { 0x63FA1EF9u, A52MAP_2CHIPS },  /* BerZerk (USA) (Beta 4) (1983-08-xx) (mame) */
    { 0x6547B51Fu, A52MAP_ROM },  /* RealSports Baseball (USA) (Beta) (1983-07-06) (size) */
    { 0x659FC323u, A52MAP_ROM },  /* BerZerk (USA) (Beta 3) (1983-08-03) (size) */
    { 0x665289E4u, A52MAP_2CHIPS },  /* Moon Patrol (USA) (Beta 1) (1983-09-14) (mame) */
    { 0x673C989Fu, A52MAP_2CHIPS },  /* Kangaroo (Atari) (U) (.hsi) */
    { 0x69F23548u, A52MAP_2CHIPS },  /* startrek */
    { 0x6A687F9Cu, A52MAP_2CHIPS },  /* digdug */
    { 0x6B3F1179u, A52MAP_ROM },  /* Mario Bros. (USA) (Alt) (size) */
    { 0x710BFE06u, A52MAP_ROM },  /* A.E. (USA) (Proto 2) (1984-01-04) (size) */
    { 0x73B5B6FBu, A52MAP_2CHIPS },  /* sprtgoof */
    { 0x741746D1u, A52MAP_ROM },  /* zaxxon */
    { 0x74C4FB9Fu, A52MAP_2CHIPS },  /* Xari Arena (USA) (Proto) (1983-06-24) (mame) */
    { 0x752F5EFDu, A52MAP_2CHIPS },  /* mspacman */
    { 0x75F566DFu, A52MAP_2CHIPS },  /* starwars */
    { 0x762C591Bu, A52MAP_ROM },  /* fractal */
    { 0x7873C6DDu, A52MAP_BBSB },  /* bbsb */
    { 0x7C988054u, A52MAP_ROM },  /* cblast */
    { 0x7D32A6CAu, A52MAP_ROM },  /* bzonea (parts joined) */
    { 0x7D819A9Fu, A52MAP_2CHIPS },  /* starraid */
    { 0x7DF1ADFBu, A52MAP_ROM },  /* mine2049 */
    { 0x7EA86E87u, A52MAP_ROM },  /* finaltst */
    { 0x83517703u, A52MAP_ROM },  /* laststar */
    { 0x84DF4925u, A52MAP_2CHIPS },  /* looneyh */
    { 0x8550A9E9u, A52MAP_2CHIPS },  /* BerZerk (USA) (Beta 1) (1983-06-01) (mame) */
    { 0x873742F1u, A52MAP_ROM },  /* mario */
    { 0x8873EF51u, A52MAP_2CHIPS },  /* pacman */
    { 0x893A6846u, A52MAP_ROM },  /* Space Dungeon (USA) (Beta) (1983-03-09) (size) */
    { 0x8A1A2B60u, A52MAP_2CHIPS },  /* Sport Goofy (USA) (Proto) (1983-03-28) (mame) */
    { 0x8A5AD939u, A52MAP_ROM },  /* Microgammon SB (USA) (Proto) (1983-07-16) (size) */
    { 0x8B5D3567u, A52MAP_2CHIPS },  /* Xari Arena (USA) (Proto) (1983-05-10) (mame) */
    { 0x8D2AAAB5u, A52MAP_ROM },  /* Asteroids (.hsi) */
    { 0x8FE3BB2Cu, A52MAP_ROM },  /* keykaper */
    { 0x906CC57Bu, A52MAP_ROM },  /* Moon Patrol (USA) (Beta 3) (size) */
    { 0x917BE656u, A52MAP_ROM },  /* koffiyk */
    { 0x9209CA2Bu, A52MAP_ROM },  /* Choplifter! (USA) (Beta 3) (mame) */
    { 0x931A454Au, A52MAP_2CHIPS },  /* microgam */
    { 0x94D97D14u, A52MAP_ROM },  /* ballblaz */
    { 0x957A4205u, A52MAP_ROM },  /* Missile Command (Europe) (Proto) (1982-04-04) (size) */
    { 0x969CFE1Au, A52MAP_ROM },  /* milliped */
    { 0x97C69F4Bu, A52MAP_ROM },  /* Gyruss (USA) (Beta) (1984-04-23) (size) */
    { 0x97DEBCD2u, A52MAP_ROM },  /* scobra */
    { 0x9AD53BBCu, A52MAP_ROM },  /* choplift */
    { 0x9BAE58DCu, A52MAP_ROM },  /* beamridr */
    { 0x9DD7776Au, A52MAP_ROM },  /* jaggi (parts joined) */
    { 0x9FB13411u, A52MAP_ROM },  /* meebzork */
    { 0xA0642110u, A52MAP_ROM },  /* sbrkout */
    { 0xA18A9A40u, A52MAP_2CHIPS },  /* popeye */
    { 0xA6400E17u, A52MAP_ROM },  /* 5200temp */
    { 0xA97606ABu, A52MAP_2CHIPS },  /* roadrun */
    { 0xAA55F9BEu, A52MAP_ROM },  /* docastle */
    { 0xAB8E035Bu, A52MAP_ROM },  /* meteorit */
    { 0xABC1D1FFu, A52MAP_2CHIPS },  /* Meebzork (USA) (Proto) (1983-05-03) (mame) */
    { 0xABC2D1E4u, A52MAP_2CHIPS },  /* polepos */
    { 0xAE7E3444u, A52MAP_ROM },  /* frogger */
    { 0xAEA6D2C2u, A52MAP_2CHIPS },  /* qix */
    { 0xB2887833u, A52MAP_ROM },  /* pitfall */
    { 0xB3B8E314u, A52MAP_2CHIPS },  /* bzone */
    { 0xB5F3402Bu, A52MAP_ROM },  /* quintana */
    { 0xB68D61E8u, A52MAP_2CHIPS },  /* spcedngn */
    { 0xB8FAAEC3u, A52MAP_2CHIPS },  /* xari */
    { 0xBB705DC9u, A52MAP_ROM },  /* Ballblazer (USA) (Beta) (1984-01-20) (size) */
    { 0xBBB3C9F2u, A52MAP_2CHIPS },  /* Meebzork (USA) (Proto) (1983-05-18) (mame) */
    { 0xBD52623Bu, A52MAP_2CHIPS },  /* defender */
    { 0xBE3CD348u, A52MAP_ROM },  /* berzerk */
    { 0xBE9A2ABDu, A52MAP_2CHIPS },  /* Vanguard (USA) (Beta) (1983-01-05) (mame) */
    { 0xBEE87E6Fu, A52MAP_ROM },  /* Choplifter! (USA) (Beta 2) (1984-01-13) (mame) */
    { 0xBFD30C01u, A52MAP_2CHIPS },  /* joust */
    { 0xC1899B05u, A52MAP_ROM },  /* Black Belt (USA) (Proto 2) (size) */
    { 0xC597C087u, A52MAP_2CHIPS },  /* minigolf */
    { 0xC8F9C094u, A52MAP_ROM },  /* blaster */
    { 0xC90196FAu, A52MAP_ROM },  /* rsbasket1 */
    { 0xC9853D0Eu, A52MAP_ROM },  /* Xari Arena (USA) (Proto) (1983-08-25) (size) */
    { 0xCAAEA0A4u, A52MAP_ROM },  /* vanguard */
    { 0xCC0EC2D4u, A52MAP_2CHIPS },  /* Jungle Hunt (USA) (Beta) (1983-04-07) (mame) */
    { 0xCE07D9ADu, A52MAP_2CHIPS },  /* pamdg23 */
    { 0xCEDCD5D9u, A52MAP_SUPERCART },  /* bosco */
    { 0xCFA0D4DAu, A52MAP_ROM },  /* Galaxian (USA) (Demo) (Kiosk) (size) */
    { 0xCFD4A7F9u, A52MAP_2CHIPS },  /* gyruss */
    { 0xD0704419u, A52MAP_ROM },  /* Pengo (USA) (Beta) (1983-08-10) (size) */
    { 0xD0B2F285u, A52MAP_ROM },  /* mpatrol */
    { 0xD18FA8C8u, A52MAP_ROM },  /* Barroom Baseball (USA) (Proto 2) (1983-11-21) (size) */
    { 0xD3BD3221u, A52MAP_ROM },  /* flegacy */
    { 0xD50E4061u, A52MAP_ROM },  /* ccrisis */
    { 0xD6F7DDFDu, A52MAP_ROM },  /* wow */
    { 0xD78C2F4Du, A52MAP_ROM },  /* Robotron 2084 (USA) (Beta) (1983-09-20) (mame) */
    { 0xD9AE4518u, A52MAP_2CHIPS },  /* jbond */
    { 0xDA228530u, A52MAP_ROM },  /* zenji */
    { 0xDA7685E6u, A52MAP_ROM },  /* Millipede (USA) (Proto) (1984-01-05) (mame) */
    { 0xDB982C2Fu, A52MAP_ROM },  /* Spitfire (USA) (Proto) (1983-11-03) (size) */
    { 0xDC1437D0u, A52MAP_2CHIPS },  /* Frogger 2 - Threedeep! (Parker Brothers) (PAL) (.hsi) */
    { 0xDD217276u, A52MAP_ROM },  /* rsbasket */
    { 0xDE5C354Au, A52MAP_ROM },  /* spaceinv */
    { 0xDE64498Au, A52MAP_ROM },  /* Space Race (USA) (Demo) (mame) */
    { 0xDEF2A207u, A52MAP_ROM },  /* Ballblazer (USA) (size) */
    { 0xE43D0D8Au, A52MAP_2CHIPS },  /* Pac-Man (USA) (Demo) (Kiosk) (trace) */
    { 0xE4F8BA8Cu, A52MAP_ROM },  /* pengo */
    { 0xE8B130C4u, A52MAP_2CHIPS },  /* pamdiag2 */
    { 0xE955DB74u, A52MAP_ROM },  /* gorf */
    { 0xEA9B852Cu, A52MAP_ROM },  /* Super Pac-Man (USA) (Proto) (1984-03-15) (mame) */
    { 0xEB5B5C64u, A52MAP_2CHIPS },  /* Tempest (USA) (Proto) (1984-03-15) (mame) */
    { 0xEC08160Du, A52MAP_ROM },  /* RealSports Baseball (USA) (Beta) (1983-02-11) (size) */
    { 0xECBD1853u, A52MAP_2CHIPS },  /* rssoccer */
    { 0xECFA624Fu, A52MAP_2CHIPS },  /* kangaroo */
    { 0xED47B0D8u, A52MAP_ROM },  /* blckbelt */
    { 0xEDDB9265u, A52MAP_ROM },  /* Millipede (USA) (Proto) (1984-01-04) (mame) */
    { 0xEE587F6Eu, A52MAP_ROM },  /* Track and Field (USA) (Proto) (1984-04-18) (mame) */
    { 0xEE702214u, A52MAP_ROM },  /* kshoot */
    { 0xEFA00F88u, A52MAP_2CHIPS },  /* BerZerk (USA) (Beta 2) (1983-07-31) (mame) */
    { 0xF085EA1Fu, A52MAP_ROM },  /* Pengo (USA) (Beta) (1983-07-27) (size) */
    { 0xF1F42BBDu, A52MAP_2CHIPS },  /* congo */
    { 0xF208A675u, A52MAP_ROM },  /* Rescue on Fractalus! (USA) (Beta) (1984-02-29) (size) */
    { 0xF270252Cu, A52MAP_ROM },  /* Jungle Hunt (USA) (Beta) (1983-05-02) (size) */
    { 0xF43E7CD0u, A52MAP_ROM },  /* decathln */
    { 0xF47BC091u, A52MAP_ROM },  /* yllowsub */
    { 0xF6AAFF07u, A52MAP_2CHIPS },  /* Moon Patrol (USA) (Beta 2) (1983-09-19) (mame) */
    { 0xFD541C80u, A52MAP_2CHIPS },  /* cntrmsre */
    { 0xFD8F0CD4u, A52MAP_2CHIPS },  /* Super Pac-Man (USA) (Proto) (Final) (mame) */
};

const unsigned a52map_db_count = sizeof a52map_db / sizeof a52map_db[0];
