#!/bin/bash
# Assemble the stub BIOS and a cart image with Macroassembler AS (run under wine
# from ~/Workspace/o2workspace/bin until AS is built natively).
set -e
AS_BIN="${AS_BIN:-$HOME/Workspace/o2workspace/bin}"
OUT="${OUT:-$PWD/build}"
mkdir -p "$OUT"
run_as() { ( cd "$OUT" && WINEDEBUG=-all wine "$AS_BIN/$@" ); }

# stub BIOS: $000-$3FF
cp emu/stubbios.a48 "$OUT/"
run_as asw.exe -q -L stubbios.a48
run_as p2bin.exe stubbios.p stubbios.bin -r 0x0-0x3FF -l 0

# Boot target for fujiboot, overridable so the same cart can be pointed at a
# local file for byte-for-byte validation of the push path:
#   BOOT_HOST=0 BOOT_PATH=/fujitest.bin ./build.sh fujiboot
BOOT_HOST="${BOOT_HOST:-2}"
BOOT_PATH="${BOOT_PATH:-/K.C. Munchkin (USA).bin}"

# cart: $400-$FFF (3K)
cp testrom/*.a48 testrom/*.inc testrom/g7000.h "$OUT/"
echo "; GENERATED by build.sh, do not edit.
HOSTSLOT equ $BOOT_HOST" > "$OUT/bootcfg.inc"
printf '; GENERATED by build.sh, do not edit.\nbootpath:  db "%s",0\n' \
  "$BOOT_PATH" > "$OUT/bootpath.inc"
for src in "$@"; do
  b=$(basename "$src" .a48)
  run_as asw.exe -q -L "$b.a48"
  run_as p2bin.exe "$b.p" "$b.bin" -r 0x400-0xFFF -l 0
  python3 tools/checklayout.py "$OUT/$b.lst"
done
ls -l "$OUT"/*.bin
