#!/bin/bash
# Assemble the stub BIOS and a cart image with Macroassembler AS (run under wine
# from ~/Workspace/o2workspace/bin until AS is built natively).
set -e
AS_BIN="${AS_BIN:-$HOME/Workspace/o2workspace/bin}"
OUT="${OUT:-$PWD/build}"
mkdir -p "$OUT"

# Macroassembler AS. A native install (Debian/Ubuntu package "asl") is preferred;
# otherwise fall back to the Windows binaries under $AS_BIN through wine, which
# is how o2workspace ships them. NOTE: only the wine path is exercised on the
# author's machine -- AS is not packaged for Arch -- so the native path is first
# proved by CI.
if command -v asl >/dev/null 2>&1; then
  AS=asl; P2BIN=p2bin
elif command -v asw >/dev/null 2>&1; then
  AS=asw; P2BIN=p2bin
else
  AS="wine $AS_BIN/asw.exe"; P2BIN="wine $AS_BIN/p2bin.exe"
  export WINEDEBUG=-all
fi
run_as()    { ( cd "$OUT" && $AS "$@" ); }
run_p2bin() { ( cd "$OUT" && $P2BIN "$@" ); }

# stub BIOS: $000-$3FF
cp emu/stubbios.a48 "$OUT/"
run_as -q -L stubbios.a48
run_p2bin stubbios.p stubbios.bin -r 0x0-0x3FF -l 0

# Boot target for fujiboot, overridable so the same cart can be pointed at a
# local file for byte-for-byte validation of the push path:
#   BOOT_HOST=0 BOOT_PATH=/fujitest.bin ./build.sh fujiboot
BOOT_HOST="${BOOT_HOST:-2}"
BOOT_PATH="${BOOT_PATH:-/K.C. Munchkin (USA).bin}"

# cart: $400-$FFF (3K)
cp testrom/*.a48 testrom/*.inc testrom/g7000.h "$OUT/"
echo "; GENERATED by build.sh, do not edit.
HOSTSLOT equ $BOOT_HOST" > "$OUT/bootcfg.inc"
printf '; GENERATED by build.sh, do not edit.\nbootpath:  db "%s",0\n' \
  "$BOOT_PATH" > "$OUT/bootpath.inc"
for src in "$@"; do
  b=$(basename "$src" .a48)
  run_as -q -L "$b.a48"
  run_p2bin "$b.p" "$b.bin" -r 0x400-0xFFF -l 0
  python3 tools/checklayout.py "$OUT/$b.lst"
done
ls -l "$OUT"/*.bin
