#!/usr/bin/env bash
# apply.sh -- graft the FujiNet Videocart device into a MAME tree.
#
# Usage: ./apply.sh /path/to/mame
#
# Copies the device model (fujinet.cpp/h, fujitcp.c/h) and the cartridge
# firmware's own protocol sources (fujimail, fujibus, chfmap, the bus observer
# and their headers -- MAME then runs the code the cartridge actually ships)
# into src/devices/bus/chanf/, and makes the shared-file edits:
#
#   scripts/src/bus.lua          the CHANNELF file list
#   src/devices/bus/chanf/slot.h   a CF_FUJINET pcb type
#   src/devices/bus/chanf/slot.cpp select it when our device is the one loaded
#   src/mame/fairchild/channelf.cpp  the slot option, and a write handler
#   src/devices/cpu/f8/f8.cpp      the ROMC trace hook (via f8trace.py)
#
# Idempotent: run it again after editing any source here.
#
# Afterwards: make -C /path/to/mame -j$(nproc) REGENIE=1 (REGENIE=1 is required
# the first time because bus.lua changed).

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:?usage: apply.sh /path/to/mame}
BUSDIR="$MAME/src/devices/bus/chanf"
BUSLUA="$MAME/scripts/src/bus.lua"
SLOT_H="$BUSDIR/slot.h"
SLOT_C="$BUSDIR/slot.cpp"
DRIVER="$MAME/src/mame/fairchild/channelf.cpp"

[ -d "$BUSDIR" ] || { echo "apply.sh: $BUSDIR missing" >&2; exit 1; }

# The shared protocol sources are C, but MAME's device project forces a C++
# precompiled header on every file it owns, so they are copied in under .cpp
# names and compiled as C++ (they are written to build both ways).
cp fujinet.cpp fujinet.h fujitcp.h "$BUSDIR/"
cp fujitcp.c "$BUSDIR/fujitcp.cpp"
cp ../firmware/src/fujimail.c "$BUSDIR/fujimail.cpp"
cp ../firmware/src/fujibus.c "$BUSDIR/fujibus.cpp"
cp ../firmware/src/chfmap.c "$BUSDIR/chfmap.cpp"
cp ../firmware/include/fujimail.h ../firmware/include/fujibus.h \
   ../firmware/include/chfmap.h ../firmware/include/fuji_mailbox.h \
   ../firmware/include/channelf_cart.h \
   "$BUSDIR/"
rm -f "$BUSDIR/fujitcp.c" "$BUSDIR/fujimail.c" "$BUSDIR/fujibus.c" \
      "$BUSDIR/chfmap.c"

# Rename every shared symbol, because more than one of these cartridges can be
# grafted into the same MAME tree at once.
#
# fujimail.c, fujibus.c and fujitcp.c are byte-identical across the Astrocade,
# Arcadia, ColecoVision and Channel F ports -- that is the whole point of
# sharing them -- but each copy is compiled against its OWN fuji_mailbox.h.
# With several grafted, the linker picks one definition of fujimail_paint() for
# the whole binary and the others silently paint the wrong offsets: the
# cartridge answers, the socket connects, and the client reads $FF forever.
# Prefixing makes the collision impossible instead of merely unlikely.
cat > "$BUSDIR/fujins.h" <<'NSEOF'
/* GENERATED by pico/channelf/emu/apply.sh -- do not edit.
 *
 * Give this port's copies of the shared protocol sources their own symbols, so
 * several FujiNet cartridges can live in one MAME binary. See apply.sh. */
#ifndef CHANF_FUJINS_H
#define CHANF_FUJINS_H
NSEOF
for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
           fujibus_build_request fujibus_parse_reply fujibus_selftest \
           fujitcp_init fujitcp_active fujitcp_close fujitcp_transact \
           fujitcp_send_bare; do
    echo "#define $sym channelf_$sym" >> "$BUSDIR/fujins.h"
done
echo "#endif" >> "$BUSDIR/fujins.h"

# Inject the include as the first line of every copied shared file, so the
# renames reach declarations and definitions alike.
for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h; do
    if ! head -1 "$BUSDIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$BUSDIR/$f")" > "$BUSDIR/$f.tmp"
        mv "$BUSDIR/$f.tmp" "$BUSDIR/$f"
    fi
done

# bus.lua: add our files to the CHANNELF block, once.
if ! grep -q "chanf/fujinet.cpp" "$BUSLUA"; then
    python3 - "$BUSLUA" <<'EOF'
import sys

path = sys.argv[1]
text = open(path).read()
anchor = '\t\tMAME_DIR .. "src/devices/bus/chanf/rom.h",\n'
if anchor not in text:
    sys.exit("apply.sh: bus.lua anchor line not found")
addition = anchor + "".join(
    f'\t\tMAME_DIR .. "src/devices/bus/chanf/{f}",\n'
    for f in ("fujinet.cpp", "fujinet.h", "fujitcp.cpp", "fujitcp.h",
              "fujimail.cpp", "fujimail.h", "fujibus.cpp", "fujibus.h",
              "chfmap.cpp", "chfmap.h", "fuji_mailbox.h", "channelf_cart.h",
              "fujins.h"))
open(path, "w").write(text.replace(anchor, addition, 1))
EOF
    echo "apply.sh: bus.lua updated (build with REGENIE=1)"
fi

# slot.h: a pcb type of our own.
if ! grep -q "CF_FUJINET" "$SLOT_H"; then
    python3 - "$SLOT_H" <<'EOF'
import sys
path = sys.argv[1]
text = open(path).read()
anchor = "\tCF_MULTI\n};"
if anchor not in text:
    sys.exit("apply.sh: slot.h pcb enum anchor not found")
open(path, "w").write(text.replace(anchor, "\tCF_MULTI,\n\tCF_FUJINET\n};", 1))
EOF
    echo "apply.sh: slot.h updated"
fi

# slot.cpp: register the type, and pick it when OUR device is in the slot.
#
# call_load() forces CF_CHESS for any fullpath image (it defaults to the Saba
# Schach PCB because homebrew tends to expect RAM at $2800), which would install
# the console's own RAM handlers over part of our address space. Keying on the
# loaded device type instead of the file is the only way to tell it apart.
if ! grep -q "CF_FUJINET" "$SLOT_C"; then
    python3 - "$SLOT_C" <<'EOF'
import sys
path = sys.argv[1]
text = open(path).read()

inc = '#include "slot.h"\n'
if inc not in text:
    sys.exit("apply.sh: slot.cpp include anchor not found")
text = text.replace(inc, inc + '#include "fujinet.h"\n', 1)

lst = '\t{ CF_MULTI,    "multi" }\n'
if lst not in text:
    sys.exit("apply.sh: slot.cpp slot_list anchor not found")
text = text.replace(lst, '\t{ CF_MULTI,    "multi" },\n\t{ CF_FUJINET,  "fujinet" }\n', 1)

old = """			if (len == 0x40000)
				m_type = CF_MULTI;  // TODO1: differentiate multicart final and earlier from fullpath
			else
				m_type = CF_CHESS;  // TODO2: is there any way to detect Maze and Hangman from fullpath?"""
if old not in text:
    sys.exit("apply.sh: slot.cpp call_load anchor not found")
new = """			if (m_cart->device().type() == CHANF_ROM_FUJINET)
				m_type = CF_FUJINET;
			else if (len == 0x40000)
				m_type = CF_MULTI;  // TODO1: differentiate multicart final and earlier from fullpath
			else
				m_type = CF_CHESS;  // TODO2: is there any way to detect Maze and Hangman from fullpath?"""
text = text.replace(old, new, 1)
open(path, "w").write(text)
EOF
    echo "apply.sh: slot.cpp updated"
fi

# channelf.cpp: include, a selectable slot option, and the write handler.
#
# The driver maps $0800-$FFFF read-only, because no stock Videocart needs more.
# Ours does: ROMC 05 is a real store cycle and both the RAM arena and the whole
# console -> cart direction ride it. Reads stay on read_rom, so the offsets
# match ($0800-relative in both directions).
if ! grep -q "CHANF_ROM_FUJINET" "$DRIVER"; then
    python3 - "$DRIVER" <<'EOF'
import sys
path = sys.argv[1]
text = open(path).read()

inc_anchor = '#include "bus/chanf/slot.h"\n'
if inc_anchor not in text:
    # the driver includes its own header, which pulls the slot in
    inc_anchor = '#include "channelf.h"\n'
    if inc_anchor not in text:
        sys.exit("apply.sh: channelf.cpp include anchor not found")
text = text.replace(inc_anchor, inc_anchor + '#include "bus/chanf/fujinet.h"\n', 1)

opt_anchor = '\tdevice.option_add_internal("multi",    CHANF_ROM_MULTI_FINAL);\n'
if opt_anchor not in text:
    sys.exit("apply.sh: channelf.cpp option anchor not found")
text = text.replace(opt_anchor,
                    opt_anchor + '\tdevice.option_add("fujinet", CHANF_ROM_FUJINET);\n',
                    1)

ms_anchor = """			case CF_MULTI:
			case CF_MULTI_OLD:"""
if ms_anchor not in text:
    sys.exit("apply.sh: channelf.cpp machine_start anchor not found")
text = text.replace(ms_anchor, """			case CF_FUJINET:
				m_maincpu->space(AS_PROGRAM).install_write_handler(0x0800, 0xffff, write8sm_delegate(*m_cart, FUNC(channelf_cart_slot_device::write_ram)));
				break;
			case CF_MULTI:
			case CF_MULTI_OLD:""", 1)
open(path, "w").write(text)
EOF
    echo "apply.sh: channelf.cpp updated"
fi

# The ROMC trace hook, for firmware/host_test/test_romc.c.
python3 f8trace.py "$MAME"

echo "apply.sh: done"
