#!/usr/bin/env python3
"""Emit firmware/src/s2_font.c: the cart text engine's 3x5 font.

    tools/mkfont.py > firmware/src/s2_font.c

$20-$7F are Channel F's 3x5 glyphs (lowercase drawn as the uppercase glyph
squashed into four rows, so case shows by height); $01-$0B are the symbols
s2_text.h names. Each row is one octal digit, bit 2 the leftmost pixel.
"""

# 3 wide, 5 tall. '#' lit.
GLYPHS = {
    ' ': "...;...;...;...;...",   '!': ".#.;.#.;.#.;...;.#.",
    '"': "#.#;#.#;...;...;...",   '#': "#.#;###;#.#;###;#.#",
    '$': ".##;##.;.#.;.##;##.",   '%': "#.#;..#;.#.;#..;#.#",
    '&': "##.;##.;###;#.#;###",   "'": ".#.;.#.;...;...;...",
    '(': "..#;.#.;.#.;.#.;..#",   ')': "#..;.#.;.#.;.#.;#..",
    '*': "...;#.#;.#.;#.#;...",   '+': "...;.#.;###;.#.;...",
    ',': "...;...;...;.#.;#..",   '-': "...;...;###;...;...",
    '.': "...;...;...;...;.#.",   '/': "..#;..#;.#.;#..;#..",
    '0': "###;#.#;#.#;#.#;###",   '1': ".#.;##.;.#.;.#.;###",
    '2': "###;..#;###;#..;###",   '3': "###;..#;###;..#;###",
    '4': "#.#;#.#;###;..#;..#",   '5': "###;#..;###;..#;###",
    '6': "###;#..;###;#.#;###",   '7': "###;..#;..#;..#;..#",
    '8': "###;#.#;###;#.#;###",   '9': "###;#.#;###;..#;###",
    ':': "...;.#.;...;.#.;...",   ';': "...;.#.;...;.#.;#..",
    '<': "..#;.#.;#..;.#.;..#",   '=': "...;###;...;###;...",
    '>': "#..;.#.;..#;.#.;#..",   '?': "###;..#;.##;...;.#.",
    '@': "###;#.#;###;#..;###",
    'A': "###;#.#;###;#.#;#.#",   'B': "##.;#.#;##.;#.#;##.",
    'C': "###;#..;#..;#..;###",   'D': "##.;#.#;#.#;#.#;##.",
    'E': "###;#..;##.;#..;###",   'F': "###;#..;##.;#..;#..",
    'G': "###;#..;#.#;#.#;###",   'H': "#.#;#.#;###;#.#;#.#",
    'I': "###;.#.;.#.;.#.;###",   'J': "..#;..#;..#;#.#;###",
    'K': "#.#;#.#;##.;#.#;#.#",   'L': "#..;#..;#..;#..;###",
    'M': "#.#;###;###;#.#;#.#",   'N': "##.;#.#;#.#;#.#;#.#",
    'O': "###;#.#;#.#;#.#;###",   'P': "###;#.#;###;#..;#..",
    'Q': "###;#.#;#.#;###;..#",   'R': "###;#.#;##.;#.#;#.#",
    'S': "###;#..;###;..#;###",   'T': "###;.#.;.#.;.#.;.#.",
    'U': "#.#;#.#;#.#;#.#;###",   'V': "#.#;#.#;#.#;#.#;.#.",
    'W': "#.#;#.#;###;###;#.#",   'X': "#.#;#.#;.#.;#.#;#.#",
    'Y': "#.#;#.#;###;.#.;.#.",   'Z': "###;..#;.#.;#..;###",
    '[': ".##;.#.;.#.;.#.;.##",   '\\': "#..;#..;.#.;..#;..#",
    ']': "##.;.#.;.#.;.#.;##.",   '^': ".#.;#.#;...;...;...",
    '_': "...;...;...;...;###",   '`': "#..;.#.;...;...;...",
    '{': "..#;.#.;##.;.#.;..#",   '|': ".#.;.#.;.#.;.#.;.#.",
    '}': "#..;.#.;.##;.#.;#..",   '~': "...;.##;###;##.;...",
    '\x7f': "###;#.#;#.#;#.#;###",
}

SYMBOLS = {
    0x01: ".#.;###;###;.#.;###",   # spade
    0x02: "#.#;###;###;.#.;...",   # heart
    0x03: ".#.;###;###;.#.;...",   # diamond
    0x04: ".#.;###;.#.;###;.#.",   # club
    0x05: "###;###;###;###;###",   # block
    0x06: "#..;##.;###;##.;#..",   # right
    0x07: "..#;.##;###;.##;..#",   # left
    0x08: "...;.#.;###;###;...",   # up
    0x09: "...;###;###;.#.;...",   # down
    0x0A: "#.#;###;#.#;#.#;#.#",   # "10"
    0x0B: "###;#.#;###;#.#;###",   # card back
}


def bits(art, what):
    rows = []
    for line in art.split(';'):
        if len(line) != 3:
            raise SystemExit("glyph %s row %r is not 3 wide" % (what, line))
        rows.append(sum(1 << (2 - i) for i, c in enumerate(line) if c == '#'))
    if len(rows) != 5:
        raise SystemExit("glyph %s is not 5 tall" % what)
    return rows


def rows_for(code):
    if code in SYMBOLS:
        return bits(SYMBOLS[code], hex(code))
    ch = chr(code)
    if 'a' <= ch <= 'z':
        up = rows_for(ord(ch.upper()))
        return [0, up[0] | up[1], up[2], up[3], up[4]]
    return bits(GLYPHS.get(ch, GLYPHS['?']), repr(ch))


def main():
    print("/* s2_font.c -- GENERATED by tools/mkfont.py, do not edit. */")
    print()
    print('#include <stddef.h>')
    print()
    print('#include "s2_text.h"')
    print()
    print("/* Rows of characters $00-$7F, one octal digit each; $00 and $0C-$1F blank.")
    print(" * No designated initializers: MAME builds this file as C++. */")
    print("static const uint8_t font[128][5] = {")
    for code in range(128):
        r = rows_for(code) if (code >= 0x20 or code in SYMBOLS) else [0] * 5
        name = chr(code) if 0x20 < code < 0x7F else "%02X" % code
        print("    { %s },   /* %s */" % (", ".join("0%o" % b for b in r), name.replace('*/', '* /')))
    print("};")
    print()
    print("const uint8_t *s2_font_rows(uint8_t c)")
    print("{")
    print("    if (c >= 0x80 || (c < 0x20 && c > 0x0B) || c == 0)")
    print("        return NULL;")
    print("    return font[c];")
    print("}")


main()
