#!/usr/bin/env python3
"""Pack the resident client (CONFIG) into the C array the cart serves at boot.

    tools/mkromh.py build/config.st2 > build/gen/fujiconfigrom.h

It must be a claimed ST2 image: "FUJI" at $07FC, every page one the cart may
claim for an app (tools/checkrom.py checks the same).
"""
import sys

sys.dont_write_bytecode = True                  # no __pycache__ in the tree

sys.path.insert(0, __import__("os").path.dirname(__file__))
import st2  # noqa: E402

if len(sys.argv) != 2:
    sys.exit("usage: mkromh.py <client.st2>")

data = open(sys.argv[1], "rb").read()
try:
    img = st2.parse(data)
except ValueError as e:
    sys.exit("%s: %s" % (sys.argv[1], e))
if not img.claim:
    sys.exit("%s: no FUJI claim at $07FC" % sys.argv[1])
bad = [p for p in img.pages if not st2.page_ok(p, app=True)]
if bad:
    sys.exit("%s: pages the cart may not claim: %s" % (sys.argv[1], " ".join("$%02X" % p for p in bad)))

print("/* fujiconfigrom.h -- GENERATED by tools/mkromh.py from %s, do not edit. */"
      % sys.argv[1].split("/")[-1])
print()
print("#ifndef FUJICONFIGROM_H")
print("#define FUJICONFIGROM_H")
print()
print("#define FUJI_CONFIGROM_SIZE %d" % len(data))
print()
print("static const unsigned char _configrom[FUJI_CONFIGROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* FUJICONFIGROM_H */")
