# pyright: reportUndefinedVariable=false
#
# "post:" extra_script in the shared [env] list, so it sees every board and
# no-ops unless that board's [fujinet] opts in:
#
#   merge_bin      = yes                 ; yes/true/1/on, case-insensitive
#   merge_bin_name = <board>-merged.bin  ; optional, default shown
#
# Merges the separate flash pieces into one file via `esptool.py merge_bin`,
# so `write_flash 0x0 <merged file>` is all that's needed to flash a chip.
# Always 0x0, on every chip: merge_bin's --target-offset defaults to 0x0, so
# the image is zero-padded up from there to the lowest piece's own offset.
#
# Uses env.AddPostAction() rather than top-level code because a "post:"
# script's top level still runs at SCons DAG-*construction* time, before
# firmware.bin exists on disk.
#
# The LittleFS `storage` partition is excluded for free: flash_files is
# ESP-IDF's own list and never mentions PlatformIO's separately-built
# storage image. Uploading that stays on `-t uploadfs` / build.sh -f.
#
# --- flash_files: offsets yes, filenames no ---
#
# Offsets, chip and flash settings come from $BUILD_DIR/flasher_args.json,
# which is what keeps this board-agnostic (0x1000 on ESP32-classic, 0x0 on
# S3/C3, no board table). Entries are sorted numerically because esptool
# needs ascending order and JSON preserves insertion order instead.
#
# But its FILENAMES are unusable: under PlatformIO's espidf integration the
# file is generated by ESP-IDF's CMake and names things the way a native
# idf.py build lays them out. Confirmed against a real fujiversal-intv build:
#
#   flasher_args.json says               PlatformIO actually writes
#   -----------------------------------  --------------------------
#   bootloader/bootloader.bin            bootloader.bin
#   partition_table/partition-table.bin  partitions.bin
#   FujiNet_idf.bin (IDF project name)   firmware.bin ($PROGNAME.bin)
#
# So each entry is mapped back to its ROLE via flasher_args.json's own
# top-level role objects, then to the name PlatformIO uses. The literal IDF
# path is tried first, so this keeps working if that layout ever appears.
#
# Chip falls back through extra_esptool_args.chip -> build.mcu -> $BOARD_MCU
# and hard-fails if all are empty, rather than guessing (the old script
# hardcoded esp32s3, correct only for the one board it supported).
#
# esptool 5.x renames merge_bin/write_flash to merge-bin/write-flash; the
# pinned espressif32@6.10.0 ships 4.5.1, so underscores are correct here.
#
# Follow-up: build_firmwarezip.py's hardcoded board -> offset table is now
# redundant with the flash_files map this reads, and could go the same way.

import glob
import json
import os
import subprocess
import sys
import configparser

Import("env")


def parse_bool(value, key):
    v = (value or "").strip().lower()
    if v == "":
        return False
    if v in ("yes", "true", "1", "on"):
        return True
    if v in ("no", "false", "0", "off"):
        return False
    raise Exception(
        f"build_merge.py: [fujinet] {key} has an unrecognised value {value!r}; "
        "expected one of yes/true/1/on or no/false/0/off"
    )


def find_esptool(env):
    try:
        pkg_dir = env.PioPlatform().get_package_dir("tool-esptoolpy")
    except Exception:
        pkg_dir = None
    if pkg_dir:
        candidate = os.path.join(pkg_dir, "esptool.py")
        if os.path.isfile(candidate):
            return candidate

    # Fallback: glob under $PLATFORMIO_CORE_DIR (or ~/.platformio if unset) --
    # unlike the old build_merge_intv.py glob, this respects a non-default
    # PLATFORMIO_CORE_DIR instead of silently ignoring it.
    core_dir = os.environ.get("PLATFORMIO_CORE_DIR", os.path.expanduser("~/.platformio"))
    candidates = glob.glob(os.path.join(core_dir, "packages", "tool-esptoolpy*", "esptool.py"))
    if candidates:
        return candidates[0]

    raise Exception(
        "build_merge.py: esptool.py not found via "
        "env.PioPlatform().get_package_dir('tool-esptoolpy') or under "
        f"{core_dir}/packages/tool-esptoolpy*"
    )


def get_chip(env, flasher_args):
    extra_args = flasher_args.get("extra_esptool_args") or {}
    chip = (extra_args.get("chip") or "").strip()

    if not chip:
        try:
            chip = (env.BoardConfig().get("build.mcu") or "").strip()
        except Exception:
            chip = ""

    if not chip:
        subst = env.subst("$BOARD_MCU")
        if subst and subst != "$BOARD_MCU":
            chip = subst.strip()

    if not chip:
        raise Exception(
            "build_merge.py: could not derive a chip name -- flasher_args.json's "
            "extra_esptool_args.chip, env.BoardConfig()['build.mcu'], and "
            "$BOARD_MCU were all empty"
        )
    return chip


# ESP-IDF role -> the filename PlatformIO actually writes into $BUILD_DIR.
# "app" is deliberately absent: it's $PROGNAME.bin, which only env can
# substitute (it's "firmware.bin" today, but PROGNAME is configurable).
_PIO_ROLE_FILES = {
    "bootloader": "bootloader.bin",
    "partition-table": "partitions.bin",
}


def _role_by_idf_path(flasher_args):
    """Map each IDF-native file path back to its role ("bootloader", "app",
    "partition-table") using flasher_args.json's own top-level role objects,
    each of which carries a matching {"offset": ..., "file": ...}."""
    roles = {}
    for role in ("bootloader", "app", "partition-table"):
        entry = flasher_args.get(role) or {}
        path = entry.get("file")
        if path:
            roles[path] = role
    return roles


def get_flash_entries(build_dir, flasher_args, env):
    """Return a list of (offset_int, offset_str, abs_path), sorted by
    ascending numeric offset (esptool requires this order).

    Offsets come from flasher_args.json; the FILES are resolved back to
    PlatformIO's own artifact names -- see the header comment for why the
    two disagree."""
    flash_files = flasher_args.get("flash_files") or {}
    if not flash_files:
        raise Exception(
            "build_merge.py: flasher_args.json has no (or an empty) "
            "'flash_files' map, so there is nothing to merge and no way to "
            "know the per-piece flash offsets. This file is regenerated by "
            "every build; a missing map means something went wrong upstream."
        )

    roles = _role_by_idf_path(flasher_args)
    entries = []

    for offset_str, rel_path in flash_files.items():
        try:
            offset = int(offset_str, 0)
        except (TypeError, ValueError):
            raise Exception(
                "build_merge.py: flasher_args.json flash_files has a "
                f"non-numeric offset key: {offset_str!r}"
            )

        # Try, in order: the literal IDF path (in case a future PlatformIO
        # release actually lays the build dir out that way), the PlatformIO
        # name for this piece's role, then a bare basename lookup.
        candidates = [os.path.join(build_dir, rel_path)]
        role = roles.get(rel_path)
        if role == "app":
            candidates.append(env.subst("$BUILD_DIR/${PROGNAME}.bin"))
        elif role in _PIO_ROLE_FILES:
            candidates.append(os.path.join(build_dir, _PIO_ROLE_FILES[role]))
        candidates.append(os.path.join(build_dir, os.path.basename(rel_path)))

        resolved = next((c for c in candidates if os.path.isfile(c)), None)
        if resolved is None:
            raise Exception(
                f"build_merge.py: could not find the build output for "
                f"flash_files entry {offset_str} = {rel_path!r} "
                f"(role: {role or 'unknown'}). Looked for: "
                + ", ".join(candidates)
            )
        entries.append((offset, offset_str, resolved))

    entries.sort(key=lambda e: e[0])
    return entries


def merge_firmware(source, target, env):
    build_dir = env.subst("$BUILD_DIR")
    flasher_args_path = os.path.join(build_dir, "flasher_args.json")

    if not os.path.isfile(flasher_args_path):
        raise Exception(f"build_merge.py: expected build output missing: {flasher_args_path}")

    with open(flasher_args_path) as fh:
        flasher_args = json.load(fh)

    entries = get_flash_entries(build_dir, flasher_args, env)

    # get_flash_entries() already proved every path exists; this only guards
    # against two pieces claiming the same offset, which would silently drop
    # one of them from the merged image.
    seen_offsets = set()
    for offset, offset_str, _path in entries:
        if offset in seen_offsets:
            raise Exception(f"build_merge.py: duplicate flash offset {offset_str} in flash_files")
        seen_offsets.add(offset)

    flash_settings = flasher_args.get("flash_settings") or {}
    for key in ("flash_mode", "flash_size", "flash_freq"):
        if key not in flash_settings:
            raise Exception(f"build_merge.py: flasher_args.json flash_settings missing '{key}'")

    chip = get_chip(env, flasher_args)
    esptool_py = find_esptool(env)

    out_name = merge_bin_name or f"{env['PIOENV']}-merged.bin"
    merged_out = os.path.join(build_dir, out_name)

    cmd = [
        sys.executable, esptool_py,
        "--chip", chip,
        "merge_bin",
        "-o", merged_out,
        "--flash_mode", flash_settings["flash_mode"],
        "--flash_size", flash_settings["flash_size"],
        "--flash_freq", flash_settings["flash_freq"],
    ]
    for offset, offset_str, path in entries:
        cmd += [offset_str, path]

    print(f"build_merge.py: running: {' '.join(cmd)}")
    result = subprocess.run(cmd)
    if result.returncode != 0:
        raise Exception(f"build_merge.py: esptool.py merge_bin exited {result.returncode}")

    if not os.path.isfile(merged_out):
        raise Exception(f"build_merge.py: expected output missing after merge_bin: {merged_out}")

    # merge_bin's --target-offset defaults to 0x0, so the merged image is
    # zero-padded from 0x0 up to whatever the lowest input offset is, and is
    # therefore ALWAYS flashed at 0x0 -- not at the lowest input offset. Those
    # two happen to coincide on ESP32-S3/C3 (bootloader at 0x0) but not on
    # ESP32-classic (bootloader at 0x1000), where writing the merged file at
    # 0x1000 would shift every piece 4K too high.
    print(f"build_merge.py: OK -- {merged_out} ({os.path.getsize(merged_out)} bytes)")
    print(f"  Flash with: esptool.py --chip {chip} write_flash 0x0 {merged_out}")


# --- [fujinet] ini parsing, same approach as build_webui.py ---

ini_file = env["PROJECT_CONFIG"]
if ini_file is None:
    ini_file = os.environ.get("PROJECT_CONFIG")
if ini_file is None:
    ini_file = "platformio.ini"

config = configparser.ConfigParser(inline_comment_prefixes=(";", "#"))
config.read(ini_file)

merge_bin_raw = config.get("fujinet", "merge_bin", fallback="")
merge_bin_name = config.get("fujinet", "merge_bin_name", fallback="").strip()
build_board = config.get("fujinet", "build_board", fallback=None)

merge_bin_enabled = parse_bool(merge_bin_raw, "merge_bin")

if merge_bin_enabled and build_board is not None and build_board.strip() == env["PIOENV"]:
    env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", merge_firmware)
