# pyright: reportUndefinedVariable=false
#
# Builds pico/intellivision/firmware/ (Minty, targeting PICO_BOARD=fujicard --
# a completely separate CMake+Ninja project, not ESP-IDF) as a "pre:"
# extra_script for the fujiversal-intv board, so `./build.sh -b -e
# fujiversal-intv` produces both firmwares from one invocation.
#
# The resulting Minty_fujicard.bin is then turned into a plain generated C++
# source file (lib/hardware/fuji_intv_bin_data.cpp, a const byte array) that
# gets compiled and linked exactly like every other file PlatformIO already
# discovers via src/CMakeLists.txt's SOURCES glob. Nothing in this repo reads
# those symbols yet -- the RP2040/RP2350 auto-reflash consumer (PicobootClient)
# is a separate, later piece of work; this script's job stops at "the image is
# embedded in the ESP32-S3 binary."
#
# Two other approaches were tried and abandoned -- worth recording so nobody
# re-attempts them:
#   - ESP-IDF's own EMBED_FILES (idf_component_register's EMBED_FILES arg):
#     computes a doubled, broken output path under PlatformIO's espidf
#     integration for any embedded file outside a component's own source
#     tree (`.pio/build/fujiversal-intv/.pio/build/fujiversal-intv/...`).
#   - Hand-rolling the same thing with objcopy -I binary (i.e. doing what
#     EMBED_FILES does internally, ourselves) and linking the resulting .o
#     via target_link_libraries() in src/CMakeLists.txt: compiles, but the
#     symbols never make it into the final firmware.elf. PlatformIO's espidf
#     build only uses CMake to *discover* the source/include/flags graph; it
#     does its own separate SCons-driven compile and link, which never sees
#     CMake-level target_link_libraries() calls -- confirmed by grepping the
#     generated build.ninja and finding no firmware.elf link rule in it at
#     all (that step happens entirely outside anything CMake or this script
#     can influence via CMakeLists.txt).
# A real source file that PlatformIO's own compiler invocation picks up
# organically sidesteps both problems entirely.
#
# This deliberately runs as a "pre" script (before PlatformIO's own source
# discovery/compile happens) so the generated .cpp is always fresh, or the
# whole build has already aborted below.
#
# Hard-fails (raises) on any RP2040/RP2350 build problem -- toolchain
# missing, cmake configure error, ninja error. No silent fallback to a stale
# .bin: shipping an ESP32-S3 image with a mismatched or out-of-date embedded
# payload would be a much worse debugging experience than a build that just
# refuses to proceed.

import os
import shutil
import subprocess

try:
    Import("env")
except NameError:
    env = None

# Only meaningful for this one board; other boards' inis never reference this
# script, but guard anyway in case something invokes it out of context.
if env is not None and env["PIOENV"] != "fujiversal-intv":
    Return()

# SCons execs this script without defining __file__, so -- like build_webui.py
# -- paths are relative to the project root, which is always cwd for a pio
# "pre:" extra_script.
RP2040_SRC = os.path.join("pico", "intellivision", "firmware")
RP2040_BUILD = os.path.join(RP2040_SRC, "build")
PICO_BOARD = "fujicard"
# CMakeLists.txt: OUTPUT_NAME "Minty_${PICO_BOARD}${OUTPUT_SUFFIX}" -- default
# OUTPUT_SUFFIX is empty, so this name doesn't vary between Debug/Release.
RP2040_BIN = os.path.join(RP2040_BUILD, f"Minty_{PICO_BOARD}.bin")

# Lands under lib/hardware/ so it's covered by src/CMakeLists.txt's existing
# `${CMAKE_SOURCE_DIR}/lib/hardware/*.cpp` glob -- no CMakeLists.txt edit
# needed, and PlatformIO's own source-discovery finds it the same way it
# finds every other file in that directory. Generated, not checked in --
# see .gitignore.
GENERATED_CPP = os.path.join("lib", "hardware", "fuji_intv_bin_data.cpp")

PICO_SDK_PATH = os.environ.get("PICO_SDK_PATH", "/usr/share/pico-sdk")


def fail(msg):
    raise Exception(f"build_pico_intv.py: {msg} -- aborting ESP32-S3 build")


def run(cmd, cwd, extra_env=None):
    print(f"build_pico_intv.py: running: {' '.join(cmd)} (in {cwd})")
    build_env = os.environ.copy()
    if extra_env:
        build_env.update(extra_env)
    result = subprocess.run(cmd, cwd=cwd, env=build_env)
    if result.returncode != 0:
        fail(f"'{' '.join(cmd)}' exited {result.returncode}")


def generate_cpp(bin_path, cpp_path):
    with open(bin_path, "rb") as f:
        data = f.read()

    with open(cpp_path, "w") as f:
        f.write("// AUTO-GENERATED by build_pico_intv.py from "
                 f"{bin_path} -- do not edit, do not commit.\n")
        f.write("#include <cstdint>\n#include <cstddef>\n\n")
        f.write('extern "C" const uint8_t fuji_intv_bin_data[] = {\n')
        for i in range(0, len(data), 20):
            row = data[i:i + 20]
            f.write("    " + ",".join(f"0x{b:02x}" for b in row) + ",\n")
        f.write("};\n\n")
        f.write(f'extern "C" const size_t fuji_intv_bin_size = {len(data)};\n')

    return len(data)


if shutil.which("arm-none-eabi-gcc") is None:
    fail("arm-none-eabi-gcc not found on PATH (RP2040/RP2350 toolchain)")

if not os.path.isdir(PICO_SDK_PATH):
    fail(f"PICO_SDK_PATH does not exist: {PICO_SDK_PATH} "
         f"(set the PICO_SDK_PATH env var to override the default)")

print(f"build_pico_intv.py: building Minty (pico/intellivision/firmware, PICO_BOARD={PICO_BOARD})")
print(f"  PICO_SDK_PATH: {PICO_SDK_PATH}")

os.makedirs(RP2040_BUILD, exist_ok=True)

if not os.path.isfile(os.path.join(RP2040_BUILD, "build.ninja")):
    run(["cmake", "-B", "build", "-G", "Ninja",
         f"-DPICO_BOARD={PICO_BOARD}", "-DCMAKE_BUILD_TYPE=Release"],
        cwd=RP2040_SRC, extra_env={"PICO_SDK_PATH": PICO_SDK_PATH})

run(["ninja", "-C", "build"], cwd=RP2040_SRC, extra_env={"PICO_SDK_PATH": PICO_SDK_PATH})

if not os.path.isfile(RP2040_BIN):
    fail(f"expected output missing after a successful ninja build: {RP2040_BIN}")

size = generate_cpp(RP2040_BIN, GENERATED_CPP)

print(f"build_pico_intv.py: OK -- {RP2040_BIN} ({size} bytes) -> {GENERATED_CPP}")
