# pyright: reportUndefinedVariable=false
#
# Safety net for every board OTHER than fujiversal-intv: deletes
# lib/hardware/fuji_intv_bin_data.cpp if a previous fujiversal-intv build
# left it behind. That file is gitignored and generated by
# build_pico_intv.py (see build-platforms/platformio-fujiversal-intv.ini),
# but it lives in lib/hardware/ -- a directory whose *.cpp glob every board
# shares via src/CMakeLists.txt's SOURCES list. Without this, switching from
# a fujiversal-intv build to any other board without an explicit clean (-c)
# build would silently compile a stale RP2040/RP2350 image into that other
# board's firmware too (confirmed: this actually happens -- fujiversal-rs232
# picked it up and built it without complaint).
#
# Registered in the SHARED [env] extra_scripts (platformio.common.ini), not
# per-board, specifically so it runs for every environment and is the one
# thing standing between "build fujiversal-intv, then build anything else"
# and a contaminated image. build_pico_intv.py itself is fujiversal-intv-only
# (only that board's ini references it) so it can't do this cleanup itself --
# it simply never runs for other boards' builds at all.

import os

try:
    Import("env")
except NameError:
    env = None

GENERATED_CPP = os.path.join("lib", "hardware", "fuji_intv_bin_data.cpp")

if env is not None and env["PIOENV"] != "fujiversal-intv":
    if os.path.isfile(GENERATED_CPP):
        print(f"cleanup_pico_intv.py: removing stale {GENERATED_CPP} "
              f"(not building fujiversal-intv)")
        os.remove(GENERATED_CPP)
