#!/usr/bin/env bash
# apply.sh -- graft the FujiNet NES cartridge device into a MAME tree.
#
# Usage: ./apply.sh /path/to/mame
#
# Copies the device model (fujinet.cpp/h, fujitcp.c/h) and the cartridge
# firmware's own protocol sources (fujimail, fujibus, nesmap, the bus decode,
# the baked CONFIG and loader ROMs -- MAME then runs the code the cartridge
# actually ships) into src/devices/bus/nes/, and makes the shared-file edits:
#
#   scripts/src/bus.lua             the NES file list
#   src/devices/bus/nes/nes_carts.cpp  the "fujinet" slot option
#   src/mame/nintendo/nes.cpp       install read_h for our device type
#
# Idempotent: run it again after editing any source here. Needs
# firmware/include/fujiconfigrom.h and nesloaderrom.h: run ../build-cart.sh.
#
# Afterwards: make -C /path/to/mame -j$(nproc) REGENIE=1 NOWERROR=1
# (REGENIE=1 is required the first time because bus.lua changed).

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:?usage: apply.sh /path/to/mame}
BUSDIR="$MAME/src/devices/bus/nes"
BUSLUA="$MAME/scripts/src/bus.lua"
CARTS="$BUSDIR/nes_carts.cpp"
DRIVER="$MAME/src/mame/nintendo/nes.cpp"

[ -d "$BUSDIR" ] || { echo "apply.sh: $BUSDIR missing" >&2; exit 1; }
for f in ../firmware/include/fujiconfigrom.h ../firmware/include/nesloaderrom.h; do
    [ -f "$f" ] || { echo "apply.sh: $f missing; run ../build-cart.sh first" >&2; exit 1; }
done

# The shared protocol sources are C, but MAME's device project forces a C++
# precompiled header on every file it owns, so they are copied in under .cpp
# names and compiled as C++ (they are written to build both ways).
cp fujinet.cpp fujinet.h fujitcp.h "$BUSDIR/"
cp fujitcp.c "$BUSDIR/fujitcp.cpp"
cp ../firmware/src/fujimail.c "$BUSDIR/fujimail.cpp"
cp ../firmware/src/fujibus.c "$BUSDIR/fujibus.cpp"
cp ../firmware/src/nesmap.c "$BUSDIR/nesmap.cpp"
cp ../firmware/include/fujimail.h ../firmware/include/fujibus.h \
   ../firmware/include/nesmap.h ../firmware/include/fuji_mailbox.h \
   ../firmware/include/nes_cart.h ../firmware/include/fujiconfigrom.h \
   ../firmware/include/nesloaderrom.h \
   "$BUSDIR/"
rm -f "$BUSDIR/fujitcp.c" "$BUSDIR/fujimail.c" "$BUSDIR/fujibus.c" "$BUSDIR/nesmap.c"

# Rename every shared symbol: fujimail.c, fujibus.c and fujitcp.c are
# byte-identical across the ports but each copy is compiled against its OWN
# fuji_mailbox.h, and several of these cartridges live in one MAME tree.
cat > "$BUSDIR/fujins.h" <<'NSEOF'
/* GENERATED by pico/nes/emu/apply.sh -- do not edit.
 *
 * Give this port's copies of the shared protocol sources their own symbols, so
 * several FujiNet cartridges can live in one MAME binary. See apply.sh. */
#ifndef NES_FUJINS_H
#define NES_FUJINS_H
NSEOF
for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
           fujibus_build_request fujibus_parse_reply fujibus_selftest \
           fujitcp_init fujitcp_active fujitcp_close fujitcp_transact \
           fujitcp_send_bare; do
    echo "#define $sym nes_$sym" >> "$BUSDIR/fujins.h"
done
echo "#endif" >> "$BUSDIR/fujins.h"

for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h; do
    if ! head -1 "$BUSDIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$BUSDIR/$f")" > "$BUSDIR/$f.tmp"
        mv "$BUSDIR/$f.tmp" "$BUSDIR/$f"
    fi
done

# bus.lua: add our files to the NES block, once.
if ! grep -q "nes/fujinet.cpp" "$BUSLUA"; then
    python3 - "$BUSLUA" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
anchor = '\t\tMAME_DIR .. "src/devices/bus/nes/nxrom.h",\n'
if anchor not in text:
    sys.exit("apply.sh: bus.lua anchor line not found")
addition = anchor + "".join(
    f'\t\tMAME_DIR .. "src/devices/bus/nes/{f}",\n'
    for f in ("fujinet.cpp", "fujinet.h", "fujitcp.cpp", "fujitcp.h",
              "fujimail.cpp", "fujimail.h", "fujibus.cpp", "fujibus.h",
              "nesmap.cpp", "nesmap.h", "fuji_mailbox.h", "nes_cart.h",
              "fujiconfigrom.h", "nesloaderrom.h", "fujins.h"))
open(path, "w").write(text.replace(anchor, addition, 1))
EOF2
    echo "apply.sh: bus.lua updated (build with REGENIE=1)"
fi

# nes_carts.cpp: the selectable slot option.
if ! grep -q "NES_FUJINET" "$CARTS"; then
    python3 - "$CARTS" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
inc = '#include "zemina.h"\n'
if inc not in text:
    sys.exit("apply.sh: nes_carts.cpp include anchor not found")
text = text.replace(inc, inc + '#include "fujinet.h"\n', 1)
opt = '\tdevice.option_add_internal("nrom",             NES_NROM);\n'
if opt not in text:
    sys.exit("apply.sh: nes_carts.cpp option anchor not found")
text = text.replace(opt, opt + '// FujiNet cartridge (pico/nes in fujinet-firmware): selectable, any image\n\tdevice.option_add("fujinet",                 NES_FUJINET);\n', 1)
open(path, "w").write(text)
EOF2
    echo "apply.sh: nes_carts.cpp updated"
fi

# nes.cpp: read_h must be installed for our device whatever pcb id the iNES
# header gave the slot -- the whole $8000-$FFFF window is ours to serve.
if ! grep -q "NES_FUJINET" "$DRIVER"; then
    python3 - "$DRIVER" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
inc = '#include "bus/nes/nes_carts.h"\n'
if inc not in text:
    sys.exit("apply.sh: nes.cpp include anchor not found")
text = text.replace(inc, inc + '#include "bus/nes/fujinet.h"\n', 1)
cond = 'if (std::find(std::begin(r_h_pcbs), std::end(r_h_pcbs), pcb_id) != std::end(r_h_pcbs))'
if cond not in text:
    sys.exit("apply.sh: nes.cpp r_h_pcbs anchor not found")
text = text.replace(cond, 'if (std::find(std::begin(r_h_pcbs), std::end(r_h_pcbs), pcb_id) != std::end(r_h_pcbs)\n\t\t\t|| m_cartslot->m_cart->device().type() == NES_FUJINET)', 1)
open(path, "w").write(text)
EOF2
    echo "apply.sh: nes.cpp updated"
fi

echo "apply.sh: done"
