#!/usr/bin/env python3
"""Generate testrom/charmap.inc: ASCII -> Odyssey 2 VDC character registers.

The VDC character pointer is a byte offset into the 512-byte character generator
(glyphs are 7 rows in an 8-byte slot) and the VDC adds (Y>>1) to it while
drawing, so the stored value is glyph*8 - Y/2, with bit 8 landing in bit 0 of the
control byte next to the colour. Verified against o2em's cset.c and vdc.c:536.
"""
G = {}
for i, ch in enumerate("0123456789"):
    G[ch] = i
G[':'] = 0x0A; G['$'] = 0x0B; G[' '] = 0x0C; G['?'] = 0x0D
G['L'] = 0x0E; G['P'] = 0x0F; G['+'] = 0x10; G['W'] = 0x11; G['E'] = 0x12
G['R'] = 0x13; G['T'] = 0x14; G['U'] = 0x15; G['I'] = 0x16; G['O'] = 0x17
G['Q'] = 0x18; G['S'] = 0x19; G['D'] = 0x1A; G['F'] = 0x1B; G['G'] = 0x1C
G['H'] = 0x1D; G['J'] = 0x1E; G['K'] = 0x1F; G['A'] = 0x20; G['Z'] = 0x21
G['X'] = 0x22; G['C'] = 0x23; G['V'] = 0x24; G['B'] = 0x25; G['M'] = 0x26
G['.'] = 0x27; G['-'] = 0x28; G['x'] = 0x29; G['='] = 0x2B; G['Y'] = 0x2C
G['N'] = 0x2D; G['/'] = 0x2E; G['\\'] = 0x3B
BLANK = 0x0C
YP, COL = 40, 0x0E

lo, hi = [], []
for c in range(0x20, 0x80):
    ch = chr(c)
    idx = G.get(ch, G.get(ch.upper(), BLANK))
    ptr = idx * 8 - (YP // 2)
    lo.append(ptr & 0xFF)
    hi.append(COL | ((ptr >> 8) & 1))

def rows(vals, per=16):
    return "\n".join("    db  " + ",".join("0%02Xh" % v for v in vals[i:i + per])
                     for i in range(0, len(vals), per))

print("""; charmap.inc -- GENERATED by tools/genmap.py, do not edit.
;
; ASCII $20-$7F -> VDC character registers, for row YP=%d. Anything the O2
; charset cannot render becomes a blank (glyph $0C).
;
; Lives in its own 256-byte page with a MOVP stub, because MOVP reads the page
; the PC is in.

CMAP_YP  equ %d
CMAP_COL equ 0%02Xh

    org 0E00h
cm_get:                     ; A = offset in page $E00 -> A = byte there
    movp a,@a
    ret

cm_lo:                      ; low byte of the character pointer
%s

cm_hi:                      ; colour + 9th pointer bit
%s""" % (YP, YP, COL, rows(lo), rows(hi)))
