#!/usr/bin/env python3
"""Pack a built cart image into the C array the cartridge firmware boots from.

    ./tools/mkromh.py build/fujicfg.bin > firmware/include/fujiconfigrom.h
"""
import sys

if len(sys.argv) != 2:
    sys.exit("usage: mkromh.py <cart.bin>")

data = open(sys.argv[1], "rb").read()
if len(data) % 1024:
    sys.exit("%s is %d bytes: not a whole number of 1K blocks" % (sys.argv[1], len(data)))

print("/* fujiconfigrom.h -- GENERATED by tools/mkromh.py, do not edit.")
print(" *")
print(" * The console client, baked into the cartridge firmware so it is there")
print(" * the moment the Odyssey 2 powers up -- there is no filesystem to load it")
print(" * from and no network yet at that point. Rebuild with:")
print(" *   ./build.sh fujicfg && ./tools/mkromh.py build/fujicfg.bin \\")
print(" *       > firmware/include/fujiconfigrom.h")
print(" */")
print()
print("#ifndef FUJICONFIGROM_H")
print("#define FUJICONFIGROM_H")
print()
print("#define FUJI_CONFIGROM_SIZE %d" % len(data))
print()
print("static const unsigned char _configrom[FUJI_CONFIGROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* FUJICONFIGROM_H */")
