#!/usr/bin/env bash
# apply.sh -- graft the FujiNet Studio II cartridge device into a MAME tree.
#
# Usage: ./apply.sh /path/to/mame
#
# Copies the device model (studio2_fujinet.cpp/h, fujitcp.c/h) and the
# cartridge firmware's own sources (fujimail, fujibus, s2map, fuji_load,
# s2_text with its font, the baked CONFIG) into src/mame/rca/, and edits
# src/mame/rca/studio2.cpp: the include, a name for the console RAM share,
# and the device in the studio2 machine. The device stays inert unless
# $FUJINET, $FUJINET_BOOT or $FUJINET_IMAGE is set, so the same binary is
# also stock MAME (Tier A's reference side).
#
# Idempotent: run it again after editing any source here. CONFIG comes from
# build/gen (../build-cart.sh) or firmware/baked/. Afterwards, in a
# single-driver tree (REGENIE=1 whenever the file list changed):
#   make SUBTARGET=studio2 SOURCES=src/mame/rca/studio2.cpp REGENIE=1 NOWERROR=1

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:?usage: apply.sh /path/to/mame}
DIR="$MAME/src/mame/rca"
DRV="$DIR/studio2.cpp"
FW=../firmware
GEN=../build/gen
[ -f "$GEN/fujiconfigrom.h" ] || GEN=$FW/baked      # no fresh build: the baked one

[ -f "$DRV" ] || { echo "apply.sh: $DRV missing" >&2; exit 1; }
[ -f "$GEN/fujiconfigrom.h" ] || { echo "apply.sh: $GEN/fujiconfigrom.h missing; run ../build-cart.sh" >&2; exit 1; }

# MAME forces a C++ precompiled header on every source file, so the shared C
# sources go in under .cpp names (they build both ways). A single-driver
# build finds them as the siblings of the headers studio2.cpp pulls in; the
# font has no header of its own, so it rides along in s2_text.cpp.
cp studio2_fujinet.cpp studio2_fujinet.h fujitcp.h "$DIR/"
cp fujitcp.c "$DIR/fujitcp.cpp"
for f in fujimail fujibus s2map fuji_load; do
    cp "$FW/src/$f.c" "$DIR/$f.cpp"
done
cat "$FW/src/s2_text.c" "$FW/src/s2_font.c" > "$DIR/s2_text.cpp"
cp "$FW/include/fujimail.h" "$FW/include/fujibus.h" "$FW/include/fuji_mailbox.h" \
   "$FW/include/s2map.h" "$FW/include/s2_cart.h" "$FW/include/s2_text.h" \
   "$FW/include/fuji_load.h" "$GEN/fujiconfigrom.h" "$DIR/"

# fujimail.c, fujibus.c, fujitcp.c and fuji_load.c carry the same symbols in
# several FujiNet ports, and a tree may hold more than one: give this copy
# its own.
{
    echo "/* GENERATED by pico/studio2/emu/apply.sh -- do not edit. */"
    echo "#ifndef S2_FUJINS_H"
    echo "#define S2_FUJINS_H"
    for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
               fujibus_build_request fujibus_parse_reply fujibus_selftest \
               fujitcp_init fujitcp_active fujitcp_close fujitcp_abort fujitcp_transact \
               fujitcp_send_bare fuji_load_init fuji_load_target fuji_load_commit \
               fuji_load_stage_config fuji_load_arm; do
        echo "#define $sym s2_$sym"
    done
    echo "#endif"
} > "$DIR/fujins.h"

for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h \
         fuji_load.cpp fuji_load.h; do
    if ! head -1 "$DIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$DIR/$f")" > "$DIR/$f.tmp"
        mv "$DIR/$f.tmp" "$DIR/$f"
    fi
done

python3 - "$DRV" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
edits = [
    ('#include "video/cdp1861.h"\n',
     '#include "video/cdp1861.h"\n#include "studio2_fujinet.h"\n'),
    ('\tmap(0x0000, 0x01ff).mirror(0xfc00).ram();\n',
     '\tmap(0x0000, 0x01ff).mirror(0xfc00).ram().share("ram");\n'),
    ('\tBEEP(config, m_beeper, 300).add_route(ALL_OUTPUTS, "mono", 1.00);\n\n\tstudio2_cartslot(config);\n}\n',
     '\tBEEP(config, m_beeper, 300).add_route(ALL_OUTPUTS, "mono", 1.00);\n\n\tstudio2_cartslot(config);\n\n'
     '\t// FujiNet cartridge (pico/studio2 in fujinet-firmware): inert unless $FUJINET\n'
     '\tSTUDIO2_FUJINET(config, "fujinet", 0);\n}\n'),
]
changed = False
for old, new in edits:
    if new in text:
        continue
    if old not in text:
        sys.exit("apply.sh: studio2.cpp anchor not found: %r" % old.strip()[:60])
    text = text.replace(old, new, 1)
    changed = True
if changed:
    open(path, "w").write(text)
    print("apply.sh: studio2.cpp updated (build with REGENIE=1)")
EOF2

echo "apply.sh: done"
