#!/usr/bin/env python3
"""Pack the resident client (CONFIG) into the C array the cart serves at boot.

    tools/mkromh.py build/config.bin > build/gen/fujiconfigrom.h

It must be a claimed 32K image: "FUJI" at $BFE0, image offset $7FE0.
"""
import sys

if len(sys.argv) != 2:
    sys.exit("usage: mkromh.py <client.bin>")

data = open(sys.argv[1], "rb").read()
if len(data) != 0x8000:
    sys.exit("%s: %d bytes; CONFIG must be a flat 32K image" % (sys.argv[1], len(data)))
if data[0x7FE0:0x7FE4] != b"FUJI":
    sys.exit("%s: no FUJI claim at $BFE0 (run tools/checkrom.py --claim)" % sys.argv[1])

print("/* fujiconfigrom.h -- GENERATED by tools/mkromh.py from %s, do not edit. */"
      % sys.argv[1].split("/")[-1])
print()
print("#ifndef FUJICONFIGROM_H")
print("#define FUJICONFIGROM_H")
print()
print("#define FUJI_CONFIGROM_SIZE %d" % len(data))
print()
print("static const unsigned char _configrom[FUJI_CONFIGROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* FUJICONFIGROM_H */")
