#!/usr/bin/env bash
# build.sh -- build the Z80 side: the loader page and the console clients.
#
#   ./build.sh                 the loader and every client in testrom/
#   ./build.sh fujitest        just that one
#
# Everything lands in build/: z88dk writes zcc_opt.def into its working
# directory, so it runs from build/obj/<client>.
#
# Environment: Z88DK (default ~/Workspace/z88dk), BOOT_HOST (default 0),
# BOOT_PATH (default /soak.bin) for fujiboot, BOOT2_PATH (default
# /sms/alexkidd.bin) for fujibank.

set -euo pipefail
cd "$(dirname "$0")"
ROOT=$PWD

Z88DK=${Z88DK:-$HOME/Workspace/z88dk}
export ZCCCFG="$Z88DK/lib/config"
export PATH="$Z88DK/bin:$PATH"
[ -x "$Z88DK/bin/zcc" ] || { echo "no zcc at $Z88DK/bin/zcc" >&2; exit 1; }

mkdir -p build/gen build/obj

cat > build/gen/bootcfg.h <<EOC
/* GENERATED by build.sh -- do not edit. */
#ifndef BOOTCFG_H
#define BOOTCFG_H
#define BOOT_HOST ${BOOT_HOST:-0}
#define BOOT_PATH "${BOOT_PATH:-/soak.bin}"
#define BOOT2_PATH "${BOOT2_PATH:-/sms/alexkidd.bin}"
#endif
EOC

build_loader() {
    z88dk-z80asm -b -O"$ROOT/build/obj" -o=loader.bin testrom/loader.asm
    cp build/obj/loader.bin build/loader.bin
    python3 tools/mkloaderh.py build/loader.bin > build/gen/smsloaderrom.h
}

SHARED="fujidisp.c fujilib.c fujiin.c"

build_one() {
    local name=$1 obj="$ROOT/build/obj/$1" src
    [ -f "testrom/$name.c" ] || { echo "no testrom/$name.c" >&2; exit 1; }
    rm -rf "$obj" && mkdir -p "$obj"
    src=("$ROOT/testrom/$name.c")
    for f in $SHARED; do src+=("$ROOT/testrom/$f"); done
    (cd "$obj" && zcc +sms -O2 -I"$ROOT/testrom" -I"$ROOT/build/gen" -m \
        -pragma-define:CRT_ENABLE_STDIO=0 -pragma-define:CLIB_FOPEN_MAX=0 \
        "${src[@]}" -o "$name" -create-app)
    python3 tools/checkrom.py --stamp "$obj/$name.sms" "build/$name.sms"
    if [ "$name" = fujibank ]; then
        python3 - "build/$name.sms" <<'EOP'
import sys
img = bytearray(open(sys.argv[1], "rb").read())
for b in (2, 3, 4):
    bank = bytearray(b"\xff" * 0x4000)
    msg = b"BANK %d IS IN SLOT 2\0" % b
    bank[:len(msg)] = msg
    img += bank
open(sys.argv[1], "wb").write(img)
EOP
        python3 tools/checkrom.py "build/$name.sms"
    fi
}

targets=("$@")
if [ ${#targets[@]} -eq 0 ]; then
    targets=(loader)
    for t in hello fujitest fujiboot fujibank; do
        [ -f "testrom/$t.c" ] && targets+=("$t")
    done
fi
for t in "${targets[@]}"; do
    if [ "$t" = loader ]; then build_loader; else build_one "$t"; fi
done
