#!/usr/bin/env bash
# build.sh -- the 6502 side: the bring-up clients, with cc65 (ca65/ld65).
# Everything lands in build/.
#
#   ./build.sh                    every client
#   ./build.sh fujiboot           just one
#   BOOT_HOST=0 BOOT_PATH=/x.a52 ./build.sh fujiboot
#
# Each client is build/<name>.bin: what the cart serves, and what MAME's
# -cart takes.
set -euo pipefail
cd "$(dirname "$0")"

command -v ca65 >/dev/null || { echo "build.sh: no ca65 (cc65)" >&2; exit 1; }
mkdir -p build/gen build/obj

python3 tools/mkfont.py > build/gen/font.inc
cat > build/gen/bootcfg.inc <<EOC
; GENERATED by build.sh -- do not edit.
BOOTHST = ${BOOT_HOST:-0}
.define BOOTPATH "${BOOT_PATH:-/soak.bin}"
EOC
python3 tools/checkdefs.py

SHARED="a52init fujidisp fujilib"

build_one() {
    local name=$1 objs=() cfg=testrom/a52.cfg
    [ -f "testrom/$name.s" ] || { echo "no testrom/$name.s" >&2; exit 1; }
    [ "$name" = fujibank ] && cfg=testrom/a52bank.cfg
    for f in $SHARED $name; do
        ca65 -I testrom -I build/gen -o "build/obj/$f.o" "testrom/$f.s"
        objs+=("build/obj/$f.o")
    done
    ld65 -C "$cfg" -m "build/obj/$name.map" -Ln "build/obj/$name.lbl" -o "build/$name.bin" "${objs[@]}"
    [ "$name" = fujibank ] && build_bank0
    python3 tools/checkrom.py --claim --map "build/obj/$name.map" "build/$name.bin"
}

# fujibank's bank 0: its own $A000-$AFFF, linked against the common code's
# addresses from bank 1's label file, laid over a copy of bank 1.
build_bank0() {
    python3 - build/obj/fujibank.lbl > build/gen/bank1syms.inc <<'EOP'
import re, sys
syms = dict((n, a) for a, n in re.findall(r"al ([0-9A-F]{6}) \.(\w+)", open(sys.argv[1]).read()))
print("; GENERATED by build.sh from fujibank.lbl -- do not edit.")
for w in ("disp_at", "disp_str", "disp_putc", "disp_rpl", "adapter"):
    print("%s = $%s" % (w, syms[w][2:]))
EOP
    ca65 -I testrom -I build/gen -o build/obj/bank0.o testrom/bank0.s
    ld65 -C testrom/bank0.cfg -o build/obj/bank0.bin build/obj/bank0.o
    python3 - <<'EOP'
b1 = open("build/fujibank.bin", "rb").read()
b0 = bytearray(b1)
b0[0x6000:0x7000] = open("build/obj/bank0.bin", "rb").read()
open("build/fujibank.bin", "wb").write(bytes(b0) + b1)
EOP
}

targets=("$@")
if [ ${#targets[@]} -eq 0 ]; then
    targets=(hello fujitest fujiboot fujibank)
fi
for t in "${targets[@]}"; do
    build_one "$t"
done
