#!/usr/bin/env bash
# Build the NES console clients and the loader ROM with cc65's ca65/ld65.
#
# Usage: ./build.sh [client ...]        default: loader hello fujitest fujiboot
#
# The boot target for fujiboot is baked in; override per build:
#   BOOT_HOST=0 BOOT_PATH=/hello.nes ./build.sh fujiboot
set -euo pipefail
cd "$(dirname "$0")"

CA65="${CA65:-ca65}"
LD65="${LD65:-ld65}"
command -v "$CA65" >/dev/null || { echo "build.sh: no ca65 on PATH (cc65 2.19)" >&2; exit 1; }

mkdir -p build
python3 tools/mkfont.py > testrom/font.inc

BOOT_HOST="${BOOT_HOST:-0}"
BOOT_PATH="${BOOT_PATH:-/hello.nes}"
cat > testrom/bootcfg.inc <<CFGEOF
; GENERATED by build.sh -- do not edit.
BOOTHST = $BOOT_HOST
.define BOOTPATH "$BOOT_PATH"
CFGEOF

clients=("$@")
[ ${#clients[@]} -eq 0 ] && clients=(loader hello fujitest fujiboot)

asm() { "$CA65" -t none -I testrom -o "build/$1.o" "testrom/$1.s"; }

for c in "${clients[@]}"; do
    echo "=== $c ==="
    if [ "$c" = loader ]; then
        asm loader
        "$LD65" -C testrom/loader.cfg -o build/loader.bin -m build/loader.map build/loader.o
        python3 tools/checkrom.py --loader build/loader.bin
        continue
    fi
    asm "$c"; asm nesinit; asm fujilib; asm fujidisp
    "$LD65" -C testrom/nes.cfg -o "build/$c.nes" -m "build/$c.map" \
        "build/$c.o" build/nesinit.o build/fujilib.o build/fujidisp.o
    python3 tools/checkrom.py --claim --map "build/$c.map" "build/$c.nes"
done
