#!/usr/bin/env python3
"""mkfont.py -- emit the cartridge's font table from tools/vcsfont.py.

The font has to exist twice: once in Python, where the reference renderer and
the M0 golden screen come from, and once in C, where the cartridge actually
composes glyphs. Two hand-maintained copies of a 96-glyph table drift, and the
drift shows up as one wrong character in a filename three milestones later.

So there is one source -- vcsfont.py's _F -- and this generates the other.
host_test/test_render.c then checks the COMPOSITION logic against the Python
renderer's output, which is the part that can still differ.

Usage: mkfont.py > firmware/include/vcs_font.h
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vcsfont import glyph, INK_H          # noqa: E402

FIRST = 0x20
LAST = 0x7F


def main():
    print("/* GENERATED by tools/mkfont.py from tools/vcsfont.py -- do not edit.")
    print(" *")
    print(" * A 3x5 glyph in a 4x6 cell, %d glyphs for $%02X-$%02X. Each entry is"
          % (LAST - FIRST + 1, FIRST, LAST))
    print(" * %d rows of three ink bits, MSB leftmost; the sixth row of the cell is"
          % INK_H)
    print(" * blank leading and is not stored.")
    print(" */")
    print("#ifndef VCS_FONT_H")
    print("#define VCS_FONT_H")
    print()
    print("#include <stdint.h>")
    print()
    print("#define VCS_FONT_FIRST 0x%02X" % FIRST)
    print("#define VCS_FONT_LAST  0x%02X" % LAST)
    print("#define VCS_FONT_INK_H %d" % INK_H)
    print()
    print("static const uint8_t vcs_font[%d][%d] = {" % (LAST - FIRST + 1, INK_H))
    for c in range(FIRST, LAST + 1):
        rows = glyph(chr(c))
        ch = chr(c)
        label = ch if 0x20 < c < 0x7F and ch not in ('*', '/') else '.'
        print("    { %s },  /* %-3s '%s' */"
              % (", ".join("%d" % r for r in rows), "$%02X" % c, label))
    print("};")
    print()
    print("#endif /* VCS_FONT_H */")


if __name__ == "__main__":
    main()
