#!/usr/bin/env python3
"""mkfontlua.py -- a Lua table for reading the rendered screen back.

The harnesses need to know what is ON the screen, not just what was sent to
it: "walk the cursor to the row whose name is X" is a much stronger test than
"press down three times", because it fails if the list is drawn in the wrong
order, truncated, or off by a row.

So the font is inverted here -- glyph bitmap to character -- and emitted for
Lua. Some glyphs are genuinely identical at 3x5 ('0' and 'O', 'C' and '['), so
the map prefers digits, then uppercase, then the rest; a decoder cannot tell
them apart and neither can a person reading the screen.

Usage: mkfontlua.py > emu/vcsfont.lua
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from vcsfont import glyph          # noqa: E402


def rank(ch):
    if ch.isdigit():
        return 0
    if ch.isupper():
        return 1
    if ch == ' ':
        return 2
    return 3


def main():
    best = {}
    for c in range(0x20, 0x80):
        ch = chr(c)
        if ch.islower():
            continue                      # folds to uppercase; never rendered
        rows = glyph(ch)
        key = 0
        for r in rows:
            key = (key << 3) | r
        if key not in best or rank(ch) < rank(best[key]):
            best[key] = ch

    print("-- GENERATED by tools/mkfontlua.py -- do not edit.")
    print("-- Glyph bitmap -> character, for decoding the rendered planes.")
    print("-- Key is the five 3-bit ink rows packed high-to-low.")
    print("local M = {}")
    print("M.glyph = {")
    for key in sorted(best):
        ch = best[key]
        lit = "'" + (ch if ch not in ("'", "\\") else "\\" + ch) + "'"
        print("  [%d] = %s," % (key, lit))
    print("}")
    print()
    print("-- Character -> glyph key, so a harness can ask what a NAME would")
    print("-- look like on screen rather than what the screen decodes to. At")
    print("-- 3x5 some glyphs are genuinely identical -- 'S' and '5', 'O' and")
    print("-- '0' -- so decoding is lossy and comparing decoded text to a")
    print("-- wanted name is not a real test. Comparing rendered forms is.")
    print("M.key = {")
    for c in range(0x20, 0x80):
        ch = chr(c)
        if ch.islower():
            continue
        rows = glyph(ch)
        key = 0
        for r in rows:
            key = (key << 3) | r
        lit = "'" + (ch if ch not in ("'", "\\") else "\\" + ch) + "'"
        print("  [%s] = %d," % (lit, key))
    print("}")
    print("return M")


if __name__ == "__main__":
    main()
