#!/usr/bin/env python3
"""mkrendergold.py -- the expectation for host_test/test_render.c.

The golden comes from tools/vcsfont.py, which was written first and knows
nothing about the C. That is the discipline the ColecoVision port arrived at
with five mappers: an expectation that calls the code under test proves only
that the code agrees with itself.

The corpus deliberately includes the cases a filename browser will actually
hit -- lowercase (which folds to uppercase), a string longer than the twelve
columns (truncated, never wrapped), a short one (space-filled), and characters
outside the font (rendered as '?' rather than reading off the end of the
table).

Usage: mkrendergold.py > firmware/host_test/render_gold.h
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from vcsfont import render_row, COLS, STRIDE, CELL_H, GROUPS   # noqa: E402

CORPUS = [
    "",
    " ",
    "FUJINET",
    "  FUJINET   ",
    "0123456789AB",
    "CDEFGHIJKLMN",
    "OPQRSTUVWXYZ",
    "HOST1: SD",
    "D1: GAME.BIN",
    "lowercase ok",
    "THIS IS FAR TOO LONG FOR TWELVE",
    "TAB\tAND\x01CTRL",
    "~{}[]|\\^_`",
    "IP: 10.0.0.9",
]


def cstr(s):
    """Escape `s` as a C string literal, using OCTAL for non-printables.

    Not hex: a C hex escape has no length limit, so "\\x01CTRL" is the single
    character 0x1C followed by "TRL" -- one character shorter than the Python
    string it is supposed to mirror, and the golden then disagrees with the
    code for a reason that has nothing to do with the renderer. Octal escapes
    stop after three digits and cannot swallow the next character.
    """
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= ord(ch) <= 0x7E:
            out.append(ch)
        else:
            out.append('\\%03o' % ord(ch))
    return "".join(out)


def main():
    print("/* GENERATED by tools/mkrendergold.py -- do not edit. */")
    print("#ifndef RENDER_GOLD_H")
    print("#define RENDER_GOLD_H")
    print()
    print("#include <stdint.h>")
    print()
    print("#define GOLD_N      %d" % len(CORPUS))
    print("#define GOLD_STRIDE %d   /* %d groups x %d scanlines */"
          % (STRIDE, GROUPS, CELL_H))
    print()
    print("static const char *const gold_text[GOLD_N] = {")
    for s in CORPUS:
        print('    "%s",' % cstr(s))
    print("};")
    print()
    print("/* One composed row per corpus entry, group-major: group g owns")
    print(" * bytes [g*%d .. g*%d+%d]. */" % (CELL_H, CELL_H, CELL_H - 1))
    print("static const uint8_t gold_row[GOLD_N][GOLD_STRIDE] = {")
    for s in CORPUS:
        row = render_row(s)
        print("    { " + ",".join("0x%02X" % b for b in row) + " },")
    print("};")
    print()
    print("#endif /* RENDER_GOLD_H */")


if __name__ == "__main__":
    main()
