#!/usr/bin/env python3
"""mkromh.py -- bake a console client into the cartridge firmware.

At power-up there is no network and nothing to load a client from, so the
client IS the boot ROM: it is compiled into the firmware image and served the
instant the console starts fetching. No menu, no fallback -- the
O2/Intellivision rule.

Usage: mkromh.py client.bin > firmware/include/fujiconfigrom.h
"""

import os
import sys


def main():
    path = sys.argv[1]
    data = open(path, "rb").read()

    print("/* GENERATED by tools/mkromh.py from %s -- do not edit. */"
          % os.path.basename(path))
    print("#ifndef FUJI_CONFIGROM_H")
    print("#define FUJI_CONFIGROM_H")
    print()
    print("#include <stdint.h>")
    print()
    print("#define FUJI_CONFIGROM_SIZE %uu" % len(data))
    print()
    print("static const uint8_t _configrom[FUJI_CONFIGROM_SIZE] = {")
    for i in range(0, len(data), 16):
        print("    " + " ".join("0x%02X," % b for b in data[i:i + 16]))
    print("};")
    print()
    print("#endif /* FUJI_CONFIGROM_H */")


if __name__ == "__main__":
    main()
