#!/usr/bin/env bash
# build.sh -- assemble the Astrocade console clients with zmac.
#
# Usage: ./build.sh [client ...]        default: fujitest fujiboot fujicfg
#
# Output: build/<client>.bin, always exactly 8192 bytes: the assembled code,
# zero-padded, with the mailbox pages cleared and the "FUJI" claim signature
# stamped at 0x1CFC (see firmware/include/fuji_mailbox.h). checkrom.py then
# enforces the layout, so a client that grows into the mailbox pages fails
# here rather than on a console.
#
# Two special clients build banked images (protocol v2):
#   fujibank -> build/fujibank.bin, an APPBANK image (8K client + stamped 4K
#               pages via mkbanked.py; BANK_PAGES overrides the default 8);
#   gamebank -> build/gamebank256.bin and gamebank512.bin, synthetic game-
#               mapper images (4K program as the last bank via mkgame.py).
#
# fujiboot takes its target from the environment:
#   BOOT_HOST=0 BOOT_PATH=/game.bin ./build.sh fujiboot

set -euo pipefail
cd "$(dirname "$0")"

WINDOW=8192
CLAIM_OFF=$((0x1CFC))
ROM_TOP=$((0x1B00))

# zmac: PATH first, then the vendored source (built on demand -- see
# tools/zmac/PROVENANCE.md).
find_zmac() {
    if command -v zmac >/dev/null 2>&1; then
        echo zmac
        return
    fi
    local tree="$PWD/tools/zmac"
    if [ ! -x "$tree/zmac" ]; then
        # zmac.c is checked in; keep it newer than zmac.y so make never
        # wants yacc.
        touch "$tree/zmac.c"
        make -C "$tree" zmac >/dev/null
    fi
    echo "$tree/zmac"
}

ZMAC=$(find_zmac)
mkdir -p build

# fujiboot's baked-in target, regenerated every run so a stale value cannot
# survive an environment change.
gen_bootcfg() {
    {
        echo "; generated by build.sh -- do not edit"
        echo "BOOTHST EQU     ${BOOT_HOST:-0}"
        printf 'BOOTPTH:DB      "%s"\n' "${BOOT_PATH:-/fujitest.bin}"
        echo "        DB      0"
    } > build/bootcfg.inc
}

build_one() {
    local name=$1
    [ "$name" = fujiboot ] && gen_bootcfg
    # zmac 1.3 resolves INCLUDE against the cwd, so assemble from testrom/.
    (cd testrom && "$ZMAC" -o "../build/$name.raw" -x "../build/$name.lst" \
        "$name.asm")
    local size
    size=$(wc -c < "build/$name.raw")
    if [ "$size" -gt "$ROM_TOP" ]; then
        echo "build.sh: $name is $size bytes, over the $ROM_TOP ROM top" >&2
        exit 1
    fi
    # Pad to the full window, clear above ROM_TOP, stamp the claim.
    {
        cat "build/$name.raw"
        head -c $((WINDOW - size)) /dev/zero
    } > "build/$name.bin"
    printf 'FUJI' | dd of="build/$name.bin" bs=1 seek=$CLAIM_OFF \
        conv=notrunc status=none
    rm -f "build/$name.raw"
    python3 tools/checkrom.py "build/$name.bin"
}

# The APPBANK self-test: an ordinary 8K client, then pages appended.
build_fujibank() {
    build_one fujibank
    python3 tools/mkbanked.py build/fujibank.bin build/fujibank.bin \
        --pages "${BANK_PAGES:-8}"
    python3 tools/mkbanked.py --verify build/fujibank.bin
    python3 tools/checkrom.py --banked build/fujibank.bin
}

# The game-mapper self-test, both sizes from one source.
build_gamebank() {
    local v banks hot size
    for v in 256 512; do
        if [ "$v" = 256 ]; then banks=64; hotlo=0C0; else banks=128; hotlo=080; fi
        {
            echo "; generated by build.sh -- do not edit"
            echo "GBANKS  EQU     $banks"
            echo "GHOTLO  EQU     ${hotlo}H     ; hotspot base low byte (page 3FH)"
        } > build/gamecfg.inc
        (cd testrom && "$ZMAC" -o "../build/gamebank$v.4k" \
            -x "../build/gamebank$v.lst" gamebank.asm)
        size=$(wc -c < "build/gamebank$v.4k")
        if [ "$size" -gt 4096 ]; then
            echo "build.sh: gamebank is $size bytes, over its 4K bank" >&2
            exit 1
        fi
        python3 tools/mkgame.py "build/gamebank$v.4k" "build/gamebank$v.bin" \
            --size "${v}k"
        python3 tools/mkgame.py --verify "build/gamebank$v.bin"
        python3 tools/checkrom.py --game "$v" "build/gamebank$v.bin"
        rm -f "build/gamebank$v.4k"
    done
}

clients=("$@")
[ ${#clients[@]} -eq 0 ] && clients=(fujitest fujiboot fujicfg)
for client in "${clients[@]}"; do
    case "$client" in
        fujibank) build_fujibank ;;
        gamebank) build_gamebank ;;
        *)        build_one "$client" ;;
    esac
done
