#!/usr/bin/env bash
# Build Channel F console clients with Macroassembler AS (CPU F3850).
#
# AS is the same assembler the Arcadia (2650) and O2 (8048) ports already use,
# so CI reuses their cache block verbatim. Usage: ./build.sh [client ...]
set -euo pipefail

cd "$(dirname "$0")"
ASL="${ASL:-$HOME/asl/asl}"
P2BIN="${P2BIN:-$HOME/asl/p2bin}"
ROM_BASE=0x800

[ -x "$ASL" ]   || { echo "build.sh: no assembler at $ASL" >&2; exit 1; }
[ -x "$P2BIN" ] || { echo "build.sh: no p2bin at $P2BIN" >&2; exit 1; }

mkdir -p build
python3 tools/mkfont.py

# The boot target, baked in. Override per build:
#   BOOT_HOST=0 BOOT_PATH=/hello.bin ./build.sh fujiboot
BOOT_HOST="${BOOT_HOST:-0}"
BOOT_PATH="${BOOT_PATH:-/hello.bin}"
cat > testrom/bootcfg.inc <<CFGEOF
; GENERATED by build.sh -- do not edit.
BOOTHST	EQU $BOOT_HOST
BOOTPTH:	DB "$BOOT_PATH",0
CFGEOF

clients=("$@")
[ ${#clients[@]} -eq 0 ] && clients=(hello)

for c in "${clients[@]}"; do
    echo "=== $c ==="
    # A FujiNet client must be exactly 16K, because the "FUJI" claim sits at the
    # very top of the window ($47FC) and that is what tells the cart to keep the
    # mailbox alive after a boot. hello and romctest are plain 2K Videocarts
    # that never touch the mailbox, so they stay the size a real cart would be.
    case "$c" in
        hello|romctest) rom_end=0x0fff; claim="" ;;
        *)              rom_end=0x47ff; claim="--claim" ;;
    esac
    ( cd testrom && "$ASL" "$c.asm" -L -i . -q )
    # -l 0xff fills the gaps; note p2bin's -f FILTERS records out and would
    # silently produce an empty image, and -s would append a checksum byte.
    "$P2BIN" "testrom/$c.p" "build/$c.bin" -r "$ROM_BASE-$rom_end" -l 0xff -q
    mv -f "testrom/$c.lst" "build/$c.lst" 2>/dev/null || true
    rm -f "testrom/$c.p"
    python3 tools/checkrom.py "build/$c.bin" $claim
done
