set(PICO_PLATFORM rp2350)
set(CONFIG_SD_STORAGE 0)
set(PICO_FLASH_SIZE_BYTES 2097152)
set(PICO_FLASH_SPI_CLKDIV 2)

option(CONFIG_FLASH_FAT_STORAGE "Flash FAT storage" OFF)
option(CONFIG_FLASH_LFS_STORAGE "Flash LFS storage" ON)
option(CONFIG_JLP "Enable JLP" ON)
option(CONFIG_ECS_AUDIO "Enable ECS audio" OFF)
option(CONFIG_INTELLIVOICE "Enable Intellivoice" OFF)

if(CMAKE_BUILD_TYPE STREQUAL "Release")
   set(CONFIG_USB_DEVICE 0)
   set(MAX_ROM_SIZE 1024*228)    # ~456 kb 
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
   set(CONFIG_USB_DEVICE 1)
   set(MAX_ROM_SIZE 1024*215)    # ~430 kb
endif()
