#!/usr/bin/env python3
"""biosok.py -- which images each console's BIOS starts as 7800 games.

Runs every image in a directory through MAME's real NTSC and PAL BIOSes
(emu/biosok.lua) and writes "CRC NTSC PAL" lines for mkmapdb.py --biosok.
The cart hands a game back to the console's own BIOS only where it passes.

Usage: biosok.py /tmp/atari7800 > tools/biosok.tsv
"""

import concurrent.futures
import os
import subprocess
import sys
import zlib

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAME = os.environ.get("MAME", os.path.expanduser("~/Workspace/mame-a7800"))
ROMS = os.environ.get("ROMS", os.path.expanduser("~/Workspace/mame/roms"))


def run(path, system):
    env = dict(os.environ, A78_EMU_DIR=os.path.join(HERE, "emu"), FUJINET_IMAGE=path)
    args = ["./a7800", system, "-rompath", ROMS, "-cartslot", "fujinet",
            "-cart", os.path.join(HERE, "build", "hello.a78"),
            "-autoboot_script", os.path.join(HERE, "emu", "biosok.lua"),
            "-video", "none", "-sound", "none", "-nothrottle", "-seconds_to_run", "20",
            "-nvram_directory", "/dev/null", "-cfg_directory", "/dev/null"]
    out = subprocess.run(args, cwd=MAME, env=env, capture_output=True, text=True).stdout
    for line in out.splitlines():
        if line.startswith("BIOSOK "):
            return int(line.split()[1])
    return 0


def one(path):
    crc = zlib.crc32(open(path, "rb").read())
    return crc, run(path, "a7800"), run(path, "a7800p"), os.path.basename(path)


def main():
    d = sys.argv[1]
    files = sorted(os.path.join(d, f) for f in os.listdir(d))
    with concurrent.futures.ThreadPoolExecutor(max_workers=24) as ex:
        rows = list(ex.map(one, files))
    print("# CRC NTSC PAL -- GENERATED by tools/biosok.py from MAME's own BIOSes")
    for crc, ntsc, pal, name in sorted(rows):
        print("%08X %d %d  # %s" % (crc, ntsc, pal, name))


if __name__ == "__main__":
    main()
