#!/usr/bin/env python3
"""Sign the power-on boot block and pack it into the C array the cart serves.

    tools/mkbootblk.py build/bootblk.bin build/gen/a78bootblk.h

Builds the vendored 7800sign (Bruce Tomlin, LGPL-2.1; tools/7800sign/) into
build/, writes the 120-byte signature at $FF80 and checks it. The NTSC BIOS
refuses an unsigned cart -- MAME does not, so emu/sigtest.lua is the real check.
"""
import os
import shutil
import subprocess
import sys

here = os.path.dirname(os.path.abspath(__file__))


def build_signer(build):
    signer = os.path.join(build, "7800sign")
    if not os.path.exists(signer) or \
            os.path.getmtime(signer) < os.path.getmtime(os.path.join(here, "7800sign", "7800sign.c")):
        os.makedirs(build, exist_ok=True)
        subprocess.run(["cc", "-O2", "-w", "-o", signer,
                        os.path.join(here, "7800sign", "7800sign.c")], check=True)
    return signer


# --verify <a78bootblk.h> <builddir>: the baked block's signature is right
if len(sys.argv) == 4 and sys.argv[1] == "--verify":
    hdr, build = sys.argv[2], sys.argv[3]
    signer = build_signer(build)
    body = open(hdr).read().split("{", 1)[1].split("}", 1)[0]
    data = bytes(int(x, 16) for x in body.replace(",", " ").split())
    path = os.path.join(build, "bootblk.verify")
    open(path, "wb").write(data)
    res = subprocess.run([signer, "-t", path], capture_output=True, text=True)
    if "is valid" not in res.stdout:
        sys.exit("mkbootblk: %s: the signature does not verify\n%s" % (hdr, res.stdout))
    print("mkbootblk: %s: signature valid" % hdr)
    sys.exit(0)

if len(sys.argv) != 3:
    sys.exit("usage: mkbootblk.py <bootblk.bin> <a78bootblk.h>\n"
             "       mkbootblk.py --verify <a78bootblk.h> <builddir>")
src, out = sys.argv[1], sys.argv[2]
build = os.path.dirname(os.path.abspath(src))
signer = build_signer(build)

signed = os.path.join(build, "bootblk.signed")
shutil.copyfile(src, signed)
data = open(signed, "rb").read()
if len(data) != 0x1000:
    sys.exit("%s is %d bytes: the boot block is 4096" % (src, len(data)))
subprocess.run([signer, "-w", signed], check=True, stdout=subprocess.DEVNULL)
res = subprocess.run([signer, "-t", signed], capture_output=True, text=True)
if "is valid" not in res.stdout:
    sys.exit("mkbootblk: 7800sign did not produce a valid signature:\n" + res.stdout)
data = open(signed, "rb").read()

with open(out, "w") as f:
    f.write("/* a78bootblk.h -- GENERATED by tools/mkbootblk.py, do not edit:\n"
            " * the BIOS checks the signature at $FF80 against every other byte. */\n\n")
    f.write("#ifndef A78BOOTBLK_H\n#define A78BOOTBLK_H\n\n")
    f.write("#define FUJI_BOOTBLK_SIZE %d\n\n" % len(data))
    f.write("static const unsigned char _bootblk[FUJI_BOOTBLK_SIZE] = {\n")
    for i in range(0, len(data), 12):
        f.write("    " + " ".join("0x%02X," % b for b in data[i:i + 12]) + "\n")
    f.write("};\n\n#endif /* A78BOOTBLK_H */\n")
print("mkbootblk: signed boot block -> %s" % out)
