#!/usr/bin/env python3
"""Pack the loader into the C array the cart serves at $0600.

    tools/mkloaderh.py build/loader.bin > build/gen/a78loaderrom.h
"""
import sys

if len(sys.argv) != 2:
    sys.exit("usage: mkloaderh.py <loader.bin>")

data = open(sys.argv[1], "rb").read()
if len(data) != 512:
    sys.exit("%s is %d bytes: the loader is 512" % (sys.argv[1], len(data)))

print("/* a78loaderrom.h -- GENERATED by tools/mkloaderh.py, do not edit. */")
print()
print("#ifndef A78LOADERROM_H")
print("#define A78LOADERROM_H")
print()
print("#define FUJI_LOADERROM_SIZE %d" % len(data))
print()
print("static const unsigned char _loaderrom[FUJI_LOADERROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* A78LOADERROM_H */")
