#!/usr/bin/env python3
"""Pack the resident client (CONFIG) into the C array the cart loads at boot.

    tools/mkromh.py build/config.a78 > build/gen/fujiconfigrom.h

The loader copies it into the SRAM after the boot block, so it is a claimed
image of any size the SRAM takes; an .a78 header is dropped.
"""
import sys

if len(sys.argv) != 2:
    sys.exit("usage: mkromh.py <client.{a78,bin}>")

data = open(sys.argv[1], "rb").read()
if len(data) >= 128 and data[1:10] == b"ATARI7800":
    data = data[128:]
claim = data[len(data) - 0x90:len(data) - 0x8C] if len(data) >= 0x90 else b""
if claim != b"FUJI":
    sys.exit("%s: no FUJI claim at $FF70 (run tools/checkrom.py --claim)" % sys.argv[1])

print("/* fujiconfigrom.h -- GENERATED by tools/mkromh.py from %s, do not edit. */"
      % sys.argv[1].split("/")[-1])
print()
print("#ifndef FUJICONFIGROM_H")
print("#define FUJICONFIGROM_H")
print()
print("#define FUJI_CONFIGROM_SIZE %d" % len(data))
print()
print("static const unsigned char _configrom[FUJI_CONFIGROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* FUJICONFIGROM_H */")
