#define CHAR_HEIGHT				12

//#define FONTSPACE (CHAR_HEIGHT * (1 + HIGHEST_ASCII_CHAR - LOWEST_ASCII_CHAR ))

enum eStatus_icons_char_num {

   LOWEST_ASCII_CHAR = 32,

   CHAR_SELECTION = 127,  // override DEL so we're <128

   CHAR_L_Wifi = 128,
   CHAR_R_Wifi,
   CHAR_L_NoWifi,
   CHAR_R_NoWifi,
   CHAR_L_Page,
   CHAR_R_Page,
   CHAR_L_Account,
   CHAR_R_Account,
   CHAR_L_NoAccount,
   CHAR_R_NoAccount,

   CHAR_PERIODPERIOD,
   CHAR_PERIODPERIOD2,

   CHAR_END
};

// Unrelated, but we want to continue the numbering...
// add more here
// BUT BEWARE -- stuffing CHARS>128 into (signed) char arrays is problematic
// housekeeping...

#define HIGHEST_ASCII_CHAR (CHAR_END - 1)

enum charNumbers {

   // COMMON/SHARED

   CH_SPACE,				// 0
   CH_EXCLAIM,
   CH_QUOTE,
   CH_HASH,
   CH_DOLLAR,
   CH_PERCENT,
   CH_AMPERSAND,
   CH_SINGLE_QUOTE,
   CH_ROUND_OPEN,
   CH_ROUND_CLOSE,
   CH_ASTERISK,			// 10
   CH_PLUS,
   CH_COMMA,
   CH_MINUS,
   CH_PERIOD,
   CH_SLASH,
   CH_COLON,
   CH_SEMICOLON,
   CH_LESS,
   CH_EQUAL,
   CH_MORE,				// 20
   CH_QUESTION,
   CH_AT,
   CH_SQUARE_OPEN,
   CH_SQUARE_CLOSE,
   CH_BACKSLASH,
   CH_ACCENT,
   CH_UNDERSCORE,
   CH_GRAVE,
   CH_CURLY_OPEN,

   // 30
   CH_CURLY_CLOSE,
   CH_VERTICAL,
   CH_TILDE,

   CH_WIFI_L,
   CH_WIFI_R,
   CH_NO_WIFI_L,
   CH_NO_WIFI_R,
   CH_PAGE_L,
   CH_PAGE_R,
   CH_ACCOUNT_L,

   // 40
   CH_ACCOUNT_R,
   CH_NO_ACCOUNT_L,
   CH_NO_ACCOUNT_R,

   CH_SELECTION,			// show selected font (box)
   // CH_PERIODPERIOD,
   // CH_PERIODPERIOD2,

   // SMALL CAPS FONT
   // OK to add variable # more chars here...

   CH_SC_EXCLAIM,
   CH_SC_QUESTION,
   CH_SC_PERIOD,
   CH_SC_SEMICOLON,
   CH_SC_COLON,
   CH_SC_ROUND_OPEN,
   CH_SC_ROUND_CLOSE,

   CH_SC_0,
   CH_SC_1,
   CH_SC_2,
   CH_SC_3,
   CH_SC_4,
   CH_SC_5,
   CH_SC_6,				// 50
   CH_SC_7,
   CH_SC_8,
   CH_SC_9,

   CH_SC_A,
   CH_SC_B,
   CH_SC_C,
   CH_SC_D,
   CH_SC_E,
   CH_SC_F,
   CH_SC_G,
   CH_SC_H,
   CH_SC_I,
   CH_SC_J,
   CH_SC_K,
   CH_SC_L,
   CH_SC_M,
   CH_SC_N,
   CH_SC_O,
   CH_SC_P,
   CH_SC_Q,
   CH_SC_R,
   CH_SC_S,
   CH_SC_T,
   CH_SC_U,
   CH_SC_V,
   CH_SC_W,
   CH_SC_X,
   CH_SC_Y,
   CH_SC_Z,

   CH_SC_a,
   CH_SC_b,
   CH_SC_c,
   CH_SC_d,
   CH_SC_e,
   CH_SC_f,
   CH_SC_g,
   CH_SC_h,
   CH_SC_i,
   CH_SC_j,
   CH_SC_k,
   CH_SC_l,
   CH_SC_m,
   CH_SC_n,
   CH_SC_o,
   CH_SC_p,
   CH_SC_q,
   CH_SC_r,
   CH_SC_s,
   CH_SC_t,
   CH_SC_u,
   CH_SC_v,
   CH_SC_w,
   CH_SC_x,
   CH_SC_y,
   CH_SC_z,

   CH_SC_PERIODPERIOD,
   CH_SC_PERIODPERIOD2,

   // TRICHOTOMIC-12
   // OK to add variable # more chars here...

   CH_TRICO_0,
   CH_TRICO_1,
   CH_TRICO_2,
   CH_TRICO_3,
   CH_TRICO_4,
   CH_TRICO_5,
   CH_TRICO_6,
   CH_TRICO_7,
   CH_TRICO_8,
   CH_TRICO_9,

   CH_TRICO_A,
   CH_TRICO_B,
   CH_TRICO_C,
   CH_TRICO_D,
   CH_TRICO_E,
   CH_TRICO_F,
   CH_TRICO_G,
   CH_TRICO_H,
   CH_TRICO_I,
   CH_TRICO_J,
   CH_TRICO_K,
   CH_TRICO_L,
   CH_TRICO_M,
   CH_TRICO_N,
   CH_TRICO_O,
   CH_TRICO_P,
   CH_TRICO_Q,
   CH_TRICO_R,
   CH_TRICO_S,
   CH_TRICO_T,
   CH_TRICO_U,
   CH_TRICO_V,
   CH_TRICO_W,
   CH_TRICO_X,
   CH_TRICO_Y,
   CH_TRICO_Z,

   CH_TRICO_a,
   CH_TRICO_b,
   CH_TRICO_c,
   CH_TRICO_d,
   CH_TRICO_e,
   CH_TRICO_f,
   CH_TRICO_g,
   CH_TRICO_h,
   CH_TRICO_i,
   CH_TRICO_j,
   CH_TRICO_k,
   CH_TRICO_l,
   CH_TRICO_m,
   CH_TRICO_n,
   CH_TRICO_o,
   CH_TRICO_p,
   CH_TRICO_q,
   CH_TRICO_r,
   CH_TRICO_s,
   CH_TRICO_t,
   CH_TRICO_u,
   CH_TRICO_v,
   CH_TRICO_w,
   CH_TRICO_x,
   CH_TRICO_y,
   CH_TRICO_z,

   CH_TRICO_PERIODPERIOD,
   CH_TRICO_PERIODPERIOD2,

   // CAPTAIN MORGAN SPICE
   // OK to add variable # more chars here...
   CH_MORGAN_Exclamation,
   CH_MORGAN_Quote,
   CH_MORGAN_Hash,
   CH_MORGAN_Dollar,
   CH_MORGAN_Percent,
   CH_MORGAN_At,
   CH_MORGAN_Ampersand,
   CH_MORGAN_Apostrophe,
   CH_MORGAN_RoundOpen,
   CH_MORGAN_RoundClose,
   CH_MORGAN_Asterisk,
   CH_MORGAN_Plus,
   CH_MORGAN_Comma,
   CH_MORGAN_Minus,
   CH_MORGAN_Period,
   CH_MORGAN_Slash,
   CH_MORGAN_Colon,
   CH_MORGAN_SemiColon,
   CH_MORGAN_Less,
   CH_MORGAN_Equal,
   CH_MORGAN_Greater,
   CH_MORGAN_Question,
   CH_MORGAN_SquareOpen,
   CH_MORGAN_BackSlash,
   CH_MORGAN_SquareClose,
   CH_MORGAN_Accent,
   CH_MORGAN_UnderScore,
   CH_MORGAN_Grave,
   CH_MORGAN_CurlyOpen,
   CH_MORGAN_Vertical,
   CH_MORGAN_CurlyClose,
   CH_MORGAN_Tilde,

   CH_MORGAN_0,
   CH_MORGAN_1,
   CH_MORGAN_2,
   CH_MORGAN_3,
   CH_MORGAN_4,
   CH_MORGAN_5,
   CH_MORGAN_6,
   CH_MORGAN_7,
   CH_MORGAN_8,
   CH_MORGAN_9,

   CH_MORGAN_A,
   CH_MORGAN_B,
   CH_MORGAN_C,
   CH_MORGAN_D,
   CH_MORGAN_E,
   CH_MORGAN_F,
   CH_MORGAN_G,
   CH_MORGAN_H,
   CH_MORGAN_I,
   CH_MORGAN_J,
   CH_MORGAN_K,
   CH_MORGAN_L,
   CH_MORGAN_M,
   CH_MORGAN_N,
   CH_MORGAN_O,
   CH_MORGAN_P,
   CH_MORGAN_Q,
   CH_MORGAN_R,
   CH_MORGAN_S,
   CH_MORGAN_T,
   CH_MORGAN_U,
   CH_MORGAN_V,
   CH_MORGAN_W,
   CH_MORGAN_X,
   CH_MORGAN_Y,
   CH_MORGAN_Z,

   CH_MORGAN_a,
   CH_MORGAN_b,
   CH_MORGAN_c,
   CH_MORGAN_d,
   CH_MORGAN_e,
   CH_MORGAN_f,
   CH_MORGAN_g,
   CH_MORGAN_h,
   CH_MORGAN_i,
   CH_MORGAN_j,
   CH_MORGAN_k,
   CH_MORGAN_l,
   CH_MORGAN_m,
   CH_MORGAN_n,
   CH_MORGAN_o,
   CH_MORGAN_p,
   CH_MORGAN_q,
   CH_MORGAN_r,
   CH_MORGAN_s,
   CH_MORGAN_t,
   CH_MORGAN_u,
   CH_MORGAN_v,
   CH_MORGAN_w,
   CH_MORGAN_x,
   CH_MORGAN_y,
   CH_MORGAN_z,
   CH_MORGAN_PERIODPERIOD,
   CH_MORGAN_PERIODPERIOD2,

   // GLACIER BELLE
   // OK to add variable # more chars here...

   CH_PELL_QUESTION,

   CH_PELL_0,
   CH_PELL_1,
   CH_PELL_2,
   CH_PELL_3,
   CH_PELL_4,
   CH_PELL_5,
   CH_PELL_6,
   CH_PELL_7,
   CH_PELL_8,
   CH_PELL_9,

   CH_PELL_A,
   CH_PELL_B,
   CH_PELL_C,
   CH_PELL_D,
   CH_PELL_E,
   CH_PELL_F,
   CH_PELL_G,
   CH_PELL_H,
   CH_PELL_I,
   CH_PELL_J,
   CH_PELL_K,
   CH_PELL_L,
   CH_PELL_M,
   CH_PELL_N,
   CH_PELL_O,
   CH_PELL_P,
   CH_PELL_Q,
   CH_PELL_R,
   CH_PELL_S,
   CH_PELL_T,
   CH_PELL_U,
   CH_PELL_V,
   CH_PELL_W,
   CH_PELL_X,
   CH_PELL_Y,
   CH_PELL_Z,

   CH_PELL_a,
   CH_PELL_b,
   CH_PELL_c,
   CH_PELL_d,
   CH_PELL_e,
   CH_PELL_f,
   CH_PELL_g,
   CH_PELL_h,
   CH_PELL_i,
   CH_PELL_j,
   CH_PELL_k,
   CH_PELL_l,
   CH_PELL_m,
   CH_PELL_n,
   CH_PELL_o,
   CH_PELL_p,
   CH_PELL_q,
   CH_PELL_r,
   CH_PELL_s,
   CH_PELL_t,
   CH_PELL_u,
   CH_PELL_v,
   CH_PELL_w,
   CH_PELL_x,
   CH_PELL_y,
   CH_PELL_z,

   CH_PELL_PERIODPERIOD,
   CH_PELL_PERIODPERIOD2,

};

uint16_t convertAsciiToCharnum(uint8_t font, uint8_t ascii);

extern const uint8_t sharedFont[];
