#!/usr/bin/env python3
"""Pack the built loader ROM into the C array the cart serves at $5800.

    ./tools/mkloaderh.py build/loader.bin > firmware/include/nesloaderrom.h
"""
import sys

if len(sys.argv) != 2:
    sys.exit("usage: mkloaderh.py <loader.bin>")

data = open(sys.argv[1], "rb").read()
if len(data) != 2048:
    sys.exit("%s is %d bytes: the loader ROM is exactly 2048" % (sys.argv[1], len(data)))

print("/* nesloaderrom.h -- GENERATED by tools/mkloaderh.py, do not edit.")
print(" *")
print(" * The 2K loader ROM the cart serves at $5800-$5FFF: the swap stub that")
print(" * copies a staged image into the SRAMs. Rebuild with:")
print(" *   ./build.sh loader && ./tools/mkloaderh.py build/loader.bin \\")
print(" *       > firmware/include/nesloaderrom.h")
print(" */")
print()
print("#ifndef NESLOADERROM_H")
print("#define NESLOADERROM_H")
print()
print("#define FUJI_LOADERROM_SIZE %d" % len(data))
print()
print("static const unsigned char _loaderrom[FUJI_LOADERROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* NESLOADERROM_H */")
