#!/usr/bin/env python3
"""Emit testrom/font.inc: a 3x5 glyph set for $20-$5F, as five 64-byte row tables.

Row-major tables (not glyph-major) so a glyph row is FNTRn + (char-32) -- one
signed ADC reaches any glyph, which a glyph-major layout could not do (offsets
run to 315 and ADC is +/-127).
"""
import sys

# 3 wide, 5 tall. '#' lit. Lowercase folds to uppercase at draw time.
GLYPHS = {
    ' ': "...;...;...;...;...",   '!': ".#.;.#.;.#.;...;.#.",
    '"': "#.#;#.#;...;...;...",   '#': "#.#;###;#.#;###;#.#",
    '$': ".##;##.;.#.;.##;##.",   '%': "#.#;..#;.#.;#..;#.#",
    '&': "##.;##.;###;#.#;###",   "'": ".#.;.#.;...;...;...",
    '(': "..#;.#.;.#.;.#.;..#",   ')': "#..;.#.;.#.;.#.;#..",
    '*': "...;#.#;.#.;#.#;...",   '+': "...;.#.;###;.#.;...",
    ',': "...;...;...;.#.;#..",   '-': "...;...;###;...;...",
    '.': "...;...;...;...;.#.",   '/': "..#;..#;.#.;#..;#..",
    '0': "###;#.#;#.#;#.#;###",   '1': ".#.;##.;.#.;.#.;###",
    '2': "###;..#;###;#..;###",   '3': "###;..#;###;..#;###",
    '4': "#.#;#.#;###;..#;..#",   '5': "###;#..;###;..#;###",
    '6': "###;#..;###;#.#;###",   '7': "###;..#;..#;..#;..#",
    '8': "###;#.#;###;#.#;###",   '9': "###;#.#;###;..#;###",
    ':': "...;.#.;...;.#.;...",   ';': "...;.#.;...;.#.;#..",
    '<': "..#;.#.;#..;.#.;..#",   '=': "...;###;...;###;...",
    '>': "#..;.#.;..#;.#.;#..",   '?': "###;..#;.##;...;.#.",
    '@': "###;#.#;###;#..;###",
    'A': "###;#.#;###;#.#;#.#",   'B': "##.;#.#;##.;#.#;##.",
    'C': "###;#..;#..;#..;###",   'D': "##.;#.#;#.#;#.#;##.",
    'E': "###;#..;##.;#..;###",   'F': "###;#..;##.;#..;#..",
    'G': "###;#..;#.#;#.#;###",   'H': "#.#;#.#;###;#.#;#.#",
    'I': "###;.#.;.#.;.#.;###",   'J': "..#;..#;..#;#.#;###",
    'K': "#.#;#.#;##.;#.#;#.#",   'L': "#..;#..;#..;#..;###",
    'M': "#.#;###;###;#.#;#.#",   'N': "##.;#.#;#.#;#.#;#.#",
    'O': "###;#.#;#.#;#.#;###",   'P': "###;#.#;###;#..;#..",
    'Q': "###;#.#;#.#;###;..#",   'R': "###;#.#;##.;#.#;#.#",
    'S': "###;#..;###;..#;###",   'T': "###;.#.;.#.;.#.;.#.",
    'U': "#.#;#.#;#.#;#.#;###",   'V': "#.#;#.#;#.#;#.#;.#.",
    'W': "#.#;#.#;###;###;#.#",   'X': "#.#;#.#;.#.;#.#;#.#",
    'Y': "#.#;#.#;###;.#.;.#.",   'Z': "###;..#;.#.;#..;###",
    '[': ".##;.#.;.#.;.#.;.##",   '\\': "#..;#..;.#.;..#;..#",
    ']': "##.;.#.;.#.;.#.;##.",   '^': ".#.;#.#;...;...;...",
    '_': "...;...;...;...;###",   '`': "#..;.#.;...;...;...",
    '{': "..#;.#.;##.;.#.;..#",   '|': ".#.;.#.;.#.;.#.;.#.",
    '}': "#..;.#.;.##;.#.;#..",   '~': "...;.##;###;##.;...",
    '\x7f': "###;#.#;#.#;#.#;###",
}

FIRST, LAST = 0x20, 0x7F


def rows_for(ch):
    # Lowercase is derived, not drawn. Three pixels wide leaves no room for
    # real letterforms, so a-z are the uppercase glyph squashed into four rows
    # -- the top two OR'd together -- which reads as "the same letter, shorter".
    # An x-height difference is what the on-screen keyboard actually needs:
    # SSIDs and passwords are case-sensitive, so the user has to be able to see
    # which case they just typed, and only the height has to be unambiguous.
    if 'a' <= ch <= 'z':
        up = rows_for(ch.upper())
        return [0, up[0] | up[1], up[2], up[3], up[4]]

    art = GLYPHS.get(ch)
    if art is None:
        art = GLYPHS['?']
    out = []
    for line in art.split(';'):
        if len(line) != 3:
            sys.exit("glyph %r row %r is not 3 wide" % (ch, line))
        bits = 0
        for i, c in enumerate(line):          # left pixel -> bit 2
            if c == '#':
                bits |= 1 << (2 - i)
        out.append(bits)
    if len(out) != 5:
        sys.exit("glyph %r is not 5 tall" % ch)
    return out


def main():
    tables = [[] for _ in range(5)]
    for code in range(FIRST, LAST + 1):
        for r, bits in enumerate(rows_for(chr(code))):
            tables[r].append(bits)

    L = []
    L.append("; GENERATED by tools/mkfont.py -- do not edit by hand.")
    L.append("; 3x5 glyphs for $%02X-$%02X in a 4x6 cell." % (FIRST, LAST))
    L.append("; Five row-major tables: glyph row n of char c is (FNTR<n> + c - $%02X)," % FIRST)
    L.append("; so one signed ADC reaches any glyph. Bit 2 = leftmost pixel.")
    L.append("FNTFST\tEQU %02XH" % FIRST)
    L.append("FNTLST\tEQU %02XH" % LAST)
    L.append("; Glyphs per row table. DSTR steps between tables by FNTCNT-1")
    L.append("; (LM has already advanced DC0 by one), so this MUST stay under")
    L.append("; 128: ADC treats the accumulator as signed.")
    L.append("FNTCNT\tEQU %d" % (LAST - FIRST + 1))
    for r in range(5):
        L.append("")
        L.append("FNTR%d:" % r)
        for i in range(0, len(tables[r]), 16):
            chunk = tables[r][i:i + 16]
            L.append("\tDB " + ",".join("%d" % b for b in chunk))
    L.append("")
    open("testrom/font.inc", "w").write("\n".join(L) + "\n")
    print("testrom/font.inc: %d glyphs, 5 tables x %d bytes = %d bytes"
          % (LAST - FIRST + 1, len(tables[0]), 5 * len(tables[0])))


main()
