#!/usr/bin/env bash
# apply.sh -- graft the FujiNet SMS cartridge device into a MAME tree.
#
# Usage: ./apply.sh /path/to/mame
#
# Copies the device model (fujinet.cpp/h, fujitcp.c/h) and the cartridge
# firmware's own sources (fujimail, fujibus, smsmap, fuji_load, the bus decode,
# the baked CONFIG and loader page) into src/devices/bus/sega8/, and edits:
#
#   scripts/src/bus.lua              the sega8 file list
#   src/devices/bus/sega8/sega8_slot.cpp  a selectable "fujinet" slot option
#   src/mame/sega/sms.cpp            a "none" BIOS on the export consoles, so
#                                    an image runs from power-on for A/B tests
#
# Idempotent: run it again after editing any source here. The CONFIG and
# loader headers come from build/gen (../build-cart.sh) or firmware/baked/.
#
# Afterwards: make -C /path/to/mame -j$(nproc) REGENIE=1 NOWERROR=1
# (REGENIE=1 the first time, because bus.lua changed).

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:?usage: apply.sh /path/to/mame}
BUSDIR="$MAME/src/devices/bus/sega8"
BUSLUA="$MAME/scripts/src/bus.lua"
SLOT="$BUSDIR/sega8_slot.cpp"
DRIVER="$MAME/src/mame/sega/sms.cpp"
FW=../firmware
GEN=../build/gen
[ -f "$GEN/fujiconfigrom.h" ] || GEN=$FW/baked      # no fresh build: the baked pair

[ -d "$BUSDIR" ] || { echo "apply.sh: $BUSDIR missing" >&2; exit 1; }
for f in "$GEN/fujiconfigrom.h" "$GEN/smsloaderrom.h"; do
    [ -f "$f" ] || { echo "apply.sh: $f missing; run ../build-cart.sh" >&2; exit 1; }
done

# MAME forces a C++ precompiled header on every device file, so the shared C
# sources go in under .cpp names (they build both ways).
cp fujinet.cpp fujinet.h fujitcp.h "$BUSDIR/"
cp fujitcp.c "$BUSDIR/fujitcp.cpp"
for f in fujimail fujibus smsmap smsmap_db fuji_load; do
    cp "$FW/src/$f.c" "$BUSDIR/$f.cpp"
done
cp "$FW/include/fujimail.h" "$FW/include/fujibus.h" "$FW/include/fuji_mailbox.h" \
   "$FW/include/sms_cart.h" "$FW/include/smsmap.h" "$FW/include/smsmap_db.h" \
   "$FW/include/fuji_load.h" "$GEN/fujiconfigrom.h" "$GEN/smsloaderrom.h" "$BUSDIR/"

# fujimail.c, fujibus.c and fujitcp.c are identical across the FujiNet ports
# but compiled against each port's own fuji_mailbox.h, and several ports share
# this tree: give this copy its own symbols.
{
    echo "/* GENERATED by pico/sms/emu/apply.sh -- do not edit. */"
    echo "#ifndef SMS_FUJINS_H"
    echo "#define SMS_FUJINS_H"
    for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
               fujibus_build_request fujibus_parse_reply fujibus_selftest \
               fujitcp_init fujitcp_active fujitcp_close fujitcp_transact \
               fujitcp_send_bare; do
        echo "#define $sym sms_$sym"
    done
    echo "#endif"
} > "$BUSDIR/fujins.h"

for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h; do
    if ! head -1 "$BUSDIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$BUSDIR/$f")" > "$BUSDIR/$f.tmp"
        mv "$BUSDIR/$f.tmp" "$BUSDIR/$f"
    fi
done

if ! grep -q "sega8/fujinet.cpp" "$BUSLUA"; then
    python3 - "$BUSLUA" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
anchor = '\t\tMAME_DIR .. "src/devices/bus/sega8/rom.h",\n'
if anchor not in text:
    sys.exit("apply.sh: bus.lua anchor line not found")
files = ("fujinet.cpp", "fujinet.h", "fujitcp.cpp", "fujitcp.h", "fujimail.cpp",
         "fujimail.h", "fujibus.cpp", "fujibus.h", "smsmap.cpp", "smsmap.h",
         "smsmap_db.cpp", "smsmap_db.h", "fuji_load.cpp", "fuji_load.h",
         "fuji_mailbox.h", "sms_cart.h", "fujiconfigrom.h", "smsloaderrom.h", "fujins.h")
addition = anchor + "".join('\t\tMAME_DIR .. "src/devices/bus/sega8/%s",\n' % f for f in files)
open(path, "w").write(text.replace(anchor, addition, 1))
EOF2
    echo "apply.sh: bus.lua updated (build with REGENIE=1)"
fi

if ! grep -q "SEGA8_FUJINET" "$SLOT"; then
    python3 - "$SLOT" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
inc = '#include "mgear.h"\n'
if inc not in text:
    sys.exit("apply.sh: sega8_slot.cpp include anchor not found")
text = text.replace(inc, inc + '#include "fujinet.h"\n', 1)
opt = '// FujiNet cartridge (pico/sms in fujinet-firmware): selectable, any image\n\tdevice.option_add("fujinet",  SEGA8_FUJINET);\n'
for fn in ("void sms_cart(device_slot_interface &device)\n{\n",
           "void sg1000mk3_cart(device_slot_interface &device)\n{\n"):
    if fn not in text:
        sys.exit("apply.sh: sega8_slot.cpp option list not found: " + fn.split("(")[0])
    text = text.replace(fn, fn + "\t" + opt, 1)
open(path, "w").write(text)
EOF2
    echo "apply.sh: sega8_slot.cpp updated"
fi

if ! grep -q 'FujiNet A/B tests' "$DRIVER"; then
    python3 - "$DRIVER" <<'EOF2'
import re, sys
path = sys.argv[1]
text = open(path).read()
for name in ("sms1", "sms", "sms1pal", "smspal"):
    m = re.search(r"ROM_START\(\s*%s\s*\)(.*?)ROM_END" % name, text, re.S)
    if not m:
        sys.exit("apply.sh: sms.cpp ROM_START(%s) not found" % name)
    body = m.group(1)
    n = len(re.findall(r"ROM_SYSTEM_BIOS\(", body))
    add = '\tROM_SYSTEM_BIOS( %d, "none", "No BIOS (FujiNet A/B tests)" )\n' % n
    text = text[:m.end(1)] + add + text[m.end(1):]
open(path, "w").write(text)
EOF2
    echo "apply.sh: sms.cpp updated"
fi

echo "apply.sh: done"
