#!/usr/bin/env bash
# build.sh -- the 6502 side: the boot block, the loader and the bring-up
# clients, with cc65 (ca65/ld65). Everything lands in build/.
#
#   ./build.sh                    the boot block, the loader and every client
#   ./build.sh fujiboot           just one
#   BOOT_HOST=0 BOOT_PATH=/x.bin BOOT_DIRECT=0 ./build.sh fujiboot
#
# Each client is build/<name>.bin (what the cart runs) and build/<name>.a78
# (what MAME's -cart takes).
set -euo pipefail
cd "$(dirname "$0")"
ROOT=$PWD

command -v ca65 >/dev/null || { echo "build.sh: no ca65 (cc65)" >&2; exit 1; }
mkdir -p build/gen build/obj

python3 tools/mkfont.py > build/gen/font.inc
cat > build/gen/bootcfg.inc <<EOC
; GENERATED by build.sh -- do not edit.
BOOTHST = ${BOOT_HOST:-0}
.define BOOTPATH "${BOOT_PATH:-/soak.bin}"
BOOTDIRECT = ${BOOT_DIRECT:-0}
EOC

asm() {
    ca65 -I testrom -I build/gen -o "build/obj/$1.o" "testrom/$1.s"
}

build_loader() {
    asm loader
    ld65 -C testrom/loader.cfg -m build/obj/loader.map -o build/loader.bin build/obj/loader.o
    python3 tools/checkrom.py --loader --map build/obj/loader.map build/loader.bin
    python3 tools/mkloaderh.py build/loader.bin > build/gen/a78loaderrom.h
}

build_bootblk() {
    asm bootblk
    ld65 -C testrom/bootblk.cfg -o build/bootblk.bin build/obj/bootblk.o
    python3 tools/mkbootblk.py build/bootblk.bin build/gen/a78bootblk.h
}

SHARED="a78init fujidisp fujilib"

build_one() {
    local name=$1 objs=() notia=--notia cfg=testrom/a78.cfg defs=()
    [ -f "testrom/$name.s" ] || { echo "no testrom/$name.s" >&2; exit 1; }
    if [ "$name" = fujibank ]; then
        cfg=testrom/a78bank.cfg
        defs=(-D BANKED)
    fi
    for f in $SHARED $name; do
        ca65 -I testrom -I build/gen "${defs[@]}" -o "build/obj/$f.o" "testrom/$f.s"
        objs+=("build/obj/$f.o")
    done
    ld65 -C "$cfg" -m "build/obj/$name.map" -o "build/$name.bin" "${objs[@]}"
    [ "$name" = fujiboot ] && [ "${BOOT_DIRECT:-0}" != 0 ] && notia=
    python3 tools/checkrom.py --claim $notia --map "build/obj/$name.map" "build/$name.bin"
    python3 tools/mka78.py "build/$name.bin" "build/$name.a78" "FUJINET $name"
}

targets=("$@")
if [ ${#targets[@]} -eq 0 ]; then
    targets=(bootblk loader hello fujitest fujiboot fujibank pokeytest)
fi
for t in "${targets[@]}"; do
    case "$t" in
        loader) build_loader ;;
        bootblk) build_bootblk ;;
        *) build_one "$t" ;;
    esac
done
