#!/usr/bin/env bash
# apply.sh -- graft the FujiNet cartridge device into a MAME tree.
#
# Usage: ./apply.sh /path/to/mame
#
# Copies the device model (fujinet.cpp/h, fujitcp.c/h) and the cartridge
# firmware's own protocol sources (fujimail, fujibus, colmap, and their
# headers -- MAME then runs the code the cartridge actually ships) into
# src/devices/bus/coleco/cartridge/, and makes the only two shared-file edits:
# the bus.lua file list and the cart-slot option in exp.cpp.
# Idempotent: run it again after editing any source here.
#
# Afterwards: make -C /path/to/mame -j$(nproc) REGENIE=1 (REGENIE=1 is required
# the first time because bus.lua changed).

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:?usage: apply.sh /path/to/mame}
BUSDIR="$MAME/src/devices/bus/coleco/cartridge"
BUSLUA="$MAME/scripts/src/bus.lua"
# The slot options live in the bus device itself on this platform, not in the
# driver -- colecovision_cartridges() is at the bottom of exp.cpp.
DRIVER="$BUSDIR/exp.cpp"

[ -d "$BUSDIR" ] || { echo "apply.sh: $BUSDIR missing" >&2; exit 1; }

# The shared protocol sources are C, but MAME's device project forces a C++
# precompiled header on every file it owns, so they are copied in under .cpp
# names and compiled as C++ (they are written to build both ways).
cp fujinet.cpp fujinet.h fujitcp.h "$BUSDIR/"
cp fujitcp.c "$BUSDIR/fujitcp.cpp"
cp ../firmware/src/fujimail.c "$BUSDIR/fujimail.cpp"
cp ../firmware/src/fujibus.c "$BUSDIR/fujibus.cpp"
cp ../firmware/src/colmap.c "$BUSDIR/colmap.cpp"
cp ../firmware/include/fujimail.h ../firmware/include/fujibus.h \
   ../firmware/include/colmap.h ../firmware/include/fuji_mailbox.h \
   "$BUSDIR/"
rm -f "$BUSDIR/fujitcp.c" "$BUSDIR/fujimail.c" "$BUSDIR/fujibus.c" \
      "$BUSDIR/colmap.c"

# Rename every shared symbol, because more than one of these cartridges can be
# grafted into the same MAME tree at once.
#
# fujimail.c, fujibus.c and fujitcp.c are byte-identical across the Astrocade,
# Arcadia and ColecoVision ports -- that is the whole point of sharing them --
# but each copy is compiled against its OWN fuji_mailbox.h, where FN_R_MAGIC0
# is 0x1C09 on one platform and 0x7C09 on another. With all three grafted, the
# linker picks one definition of fujimail_paint() for the whole binary and the
# others silently paint the wrong offsets: the cartridge answers, the socket
# connects, and the client reads 0xFF forever. Prefixing makes the collision
# impossible instead of merely unlikely.
cat > "$BUSDIR/fujins.h" <<'NSEOF'
/* GENERATED by pico/coleco/emu/apply.sh -- do not edit.
 *
 * Give this port's copies of the shared protocol sources their own symbols, so
 * several FujiNet cartridges can live in one MAME binary. See apply.sh. */
#ifndef COLECO_FUJINS_H
#define COLECO_FUJINS_H
NSEOF
for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
           fujibus_build_request fujibus_parse_reply fujibus_selftest \
           fujitcp_init fujitcp_active fujitcp_close fujitcp_transact \
           fujitcp_send_bare; do
    echo "#define $sym coleco_$sym" >> "$BUSDIR/fujins.h"
done
echo "#endif" >> "$BUSDIR/fujins.h"

# Inject the include as the first line of every copied shared file, so the
# renames reach declarations and definitions alike.
for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h; do
    if ! head -1 "$BUSDIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$BUSDIR/$f")" > "$BUSDIR/$f.tmp"
        mv "$BUSDIR/$f.tmp" "$BUSDIR/$f"
    fi
done

# bus.lua: add our files to the COLECO_CART block, once.
if ! grep -q "coleco/cartridge/fujinet.cpp" "$BUSLUA"; then
    python3 - "$BUSLUA" <<'EOF'
import sys

path = sys.argv[1]
text = open(path).read()
anchor = '\t\tMAME_DIR .. "src/devices/bus/coleco/cartridge/xin1.cpp",\n'
if anchor not in text:
    sys.exit("apply.sh: bus.lua anchor line not found")
addition = anchor + "".join(
    f'\t\tMAME_DIR .. "src/devices/bus/coleco/cartridge/{f}",\n'
    for f in ("fujinet.cpp", "fujinet.h", "fujitcp.cpp", "fujitcp.h",
              "fujimail.cpp", "fujimail.h", "fujibus.cpp", "fujibus.h",
              "colmap.cpp", "colmap.h", "fuji_mailbox.h", "fujins.h"))
open(path, "w").write(text.replace(anchor, addition, 1))
EOF
    echo "apply.sh: bus.lua updated (build with REGENIE=1)"
fi

# exp.cpp: include + selectable slot option, once. Plain option_add, unlike
# every stock ColecoVision mapper, so -cartslot fujinet works from the CLI.
if ! grep -q "COLECOVISION_FUJINET" "$DRIVER"; then
    python3 - "$DRIVER" <<'EOF'
import sys

path = sys.argv[1]
text = open(path).read()
inc_anchor = '#include "xin1.h"\n'
opt_anchor = '\tdevice.option_add_internal("xin1", COLECOVISION_XIN1);\n'
for a in (inc_anchor, opt_anchor):
    if a not in text:
        sys.exit(f"apply.sh: exp.cpp anchor not found: {a!r}")
text = text.replace(inc_anchor, inc_anchor + '#include "fujinet.h"\n', 1)
text = text.replace(opt_anchor,
                    opt_anchor + '\tdevice.option_add("fujinet", COLECOVISION_FUJINET);\n',
                    1)
open(path, "w").write(text)
EOF
    echo "apply.sh: exp.cpp updated"
fi

echo "apply.sh: done"
