#!/usr/bin/env bash
# apply.sh -- graft the FujiNet Atari 5200 cartridge device into a MAME tree.
#
# Usage: ./apply.sh /path/to/mame
#
# Copies the device model (a5200_fujinet.cpp/h, fujitcp.c/h) and the
# cartridge firmware's own sources (fujimail, fujibus, a52map, fuji_load, the
# baked CONFIG) into src/devices/bus/a800/, and edits:
#
#   scripts/src/bus.lua                    the a800 file list
#   src/devices/bus/a800/a800_carts.cpp    a selectable "fujinet" option
#
# The 5200 driver is not touched. Idempotent: run it again after editing any
# source here. CONFIG comes from build/gen (../build-cart.sh) or
# firmware/baked/.
#
# Afterwards, in a single-driver tree:
#   make SUBTARGET=a5200 SOURCES=src/mame/atari/atari400.cpp REGENIE=1 NOWERROR=1
# (REGENIE=1 the first time, because bus.lua changed).

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:?usage: apply.sh /path/to/mame}
BUSDIR="$MAME/src/devices/bus/a800"
BUSLUA="$MAME/scripts/src/bus.lua"
CARTS="$BUSDIR/a800_carts.cpp"
FW=../firmware
GEN=../build/gen
[ -f "$GEN/fujiconfigrom.h" ] || GEN=$FW/baked      # no fresh build: the baked one

[ -d "$BUSDIR" ] || { echo "apply.sh: $BUSDIR missing" >&2; exit 1; }
[ -f "$GEN/fujiconfigrom.h" ] || { echo "apply.sh: $GEN/fujiconfigrom.h missing; run ../build-cart.sh" >&2; exit 1; }

# MAME forces a C++ precompiled header on every device file, so the shared C
# sources go in under .cpp names (they build both ways).
cp a5200_fujinet.cpp a5200_fujinet.h fujitcp.h "$BUSDIR/"
cp fujitcp.c "$BUSDIR/fujitcp.cpp"
for f in fujimail fujibus a52map a52map_db fuji_load; do
    cp "$FW/src/$f.c" "$BUSDIR/$f.cpp"
done
cp "$FW/include/fujimail.h" "$FW/include/fujibus.h" "$FW/include/fuji_mailbox.h" \
   "$FW/include/a52map.h" "$FW/include/a52map_db.h" "$FW/include/fuji_load.h" \
   "$GEN/fujiconfigrom.h" "$BUSDIR/"

# fujimail.c, fujibus.c, fujitcp.c and fuji_load.c carry the same symbols in
# several FujiNet ports, and a tree may hold more than one: give this copy
# its own.
{
    echo "/* GENERATED by pico/atari-5200/emu/apply.sh -- do not edit. */"
    echo "#ifndef A52_FUJINS_H"
    echo "#define A52_FUJINS_H"
    for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
               fujibus_build_request fujibus_parse_reply fujibus_selftest \
               fujitcp_init fujitcp_active fujitcp_close fujitcp_abort fujitcp_transact \
               fujitcp_send_bare fuji_load_init fuji_load_target fuji_load_commit \
               fuji_load_stage_config fuji_load_arm; do
        echo "#define $sym a52_$sym"
    done
    echo "#endif"
} > "$BUSDIR/fujins.h"

for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h \
         fuji_load.cpp fuji_load.h; do
    if ! head -1 "$BUSDIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$BUSDIR/$f")" > "$BUSDIR/$f.tmp"
        mv "$BUSDIR/$f.tmp" "$BUSDIR/$f"
    fi
done

if ! grep -q "a800/a5200_fujinet.cpp" "$BUSLUA"; then
    python3 - "$BUSLUA" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
anchor = '\t\tMAME_DIR .. "src/devices/bus/a800/a5200_supercart.h",\n'
if anchor not in text:
    sys.exit("apply.sh: bus.lua anchor line not found")
files = ("a5200_fujinet.cpp", "a5200_fujinet.h", "fujitcp.cpp", "fujitcp.h",
         "fujimail.cpp", "fujimail.h", "fujibus.cpp", "fujibus.h", "a52map.cpp",
         "a52map.h", "a52map_db.cpp", "a52map_db.h", "fuji_load.cpp", "fuji_load.h",
         "fuji_mailbox.h", "fujiconfigrom.h", "fujins.h")
addition = anchor + "".join('\t\tMAME_DIR .. "src/devices/bus/a800/%s",\n' % f for f in files)
open(path, "w").write(text.replace(anchor, addition, 1))
EOF2
    echo "apply.sh: bus.lua updated (build with REGENIE=1)"
fi

if ! grep -q "A5200_FUJINET" "$CARTS"; then
    python3 - "$CARTS" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
inc = '#include "a800_carts.h"\n'
if inc not in text:
    sys.exit("apply.sh: a800_carts.cpp include anchor not found")
text = text.replace(inc, inc + '#include "a5200_fujinet.h"\n', 1)
anchor = 'void a5200_carts(device_slot_interface &device)\n{\n'
if anchor not in text:
    sys.exit("apply.sh: a800_carts.cpp a5200 option list not found")
opt = ('\t// FujiNet cartridge (pico/atari-5200 in fujinet-firmware): selectable\n'
       '\tdevice.option_add("fujinet",         A5200_FUJINET);\n')
text = text.replace(anchor, anchor + opt, 1)
open(path, "w").write(text)
EOF2
    echo "apply.sh: a800_carts.cpp updated"
fi

echo "apply.sh: done"
