/**
 * FTP class for #FujiNet
 */

#ifndef FNFTP_H
#define FNFTP_H

#include <string>
#include "../tcpip/fnTcpClient.h"

using namespace std;

class fnFTP
{
public:

    /**
     * Log into FTP server.
     * @param hostname The host to connect to.
     * @param port the control port # to connect to. Default is 21.
     * @return The FTP result code generated by login.
     */
    int login(string hostname, unsigned short port = 21);

    /**
     * Log out of FTP server, closes control connection.
     * @return the FTP result generated by the logout.
     */
    int logout();

protected:
private:

    /**
     * The fnTCP client used for control connection
     */
    fnTcpClient control;

    /**
     * The fnTCP client used for data connection
     */
    fnTcpClient data;
};

#endif /* FNFTP_H */