/* GENERATED by pico/atari-7800/tools/mkmapdb.py from MAME hash/a7800.xml (CC0-1.0) -- do not edit. */

#include "a78map_db.h"

const a78map_db_t a78map_db[] = {
    { 0x0198AED4u, A78MAP_ROM, 0, 0, 0 },  /* jrpacman */
    { 0x020EFE25u, A78MAP_ROM, 0, 3, 0 },  /* centipedu */
    { 0x02764A86u, A78MAP_SG, 0, 2, 0 },  /* barnblst */
    { 0x056C6D48u, A78MAP_ROM, 0, 0, 0 },  /* ruptus */
    { 0x057D9C3Cu, A78MAP_ROM, 0, 2, 0 },  /* hattrick (top 48K) */
    { 0x05A2B94Cu, A78MAP_SG, 0, 3, 0 },  /* aceofaceu */
    { 0x065E063Fu, A78MAP_ROM, 0, 3, 0 },  /* Donkey Kong (USA) */
    { 0x065F3873u, A78MAP_SG, 0, 2, 0 },  /* matmania */
    { 0x0818D8CDu, A78MAP_SG_RAM, 0, 3, 8 },  /* jinksu */
    { 0x08EB2B5Au, A78MAP_ROM, 0, 0, 0 },  /* armora2 */
    { 0x0A43D1C5u, A78MAP_ROM, 0, 2, 0 },  /* Donkey Kong (Europe) */
    { 0x0E6A8443u, A78MAP_ROM, 0, 0, 0 },  /* spacduel */
    { 0x0F2F66F8u, A78MAP_ROM, 0, 0, 0 },  /* gatop2 */
    { 0x0F87FD7Bu, A78MAP_SG_RAM, 0, 2, 8 },  /* towertop */
    { 0x12EFEB07u, A78MAP_ROM, 0, 2, 0 },  /* choplift */
    { 0x13B68650u, A78MAP_ROM, 0, 3, 0 },  /* supskateu */
    { 0x15DE2327u, A78MAP_ROM, 0, 0, 0 },  /* gatop4 */
    { 0x16B54D5Bu, A78MAP_ROM, 0, 2, 0 },  /* prowres */
    { 0x177FC850u, A78MAP_SG, 0, 2, 0 },  /* meltdown */
    { 0x187EC84Eu, A78MAP_SG, 0, 3, 0 },  /* midnightu */
    { 0x1A0A3EB3u, A78MAP_ROM, 0, 3, 0 },  /* galagau */
    { 0x1A6B1E88u, A78MAP_ROM, 0, 0, 0 },  /* meteorshu */
    { 0x1B3DD167u, A78MAP_ROM, 0, 0, 0 },  /* pacpolux */
    { 0x1C5A1082u, A78MAP_ROM, 0, 3, 0 },  /* dkongjru (top 48K) */
    { 0x1E219482u, A78MAP_SG, 0, 3, 0 },  /* mpsychou */
    { 0x1E4593DBu, A78MAP_ROM, 0, 0, 0 },  /* aerial */
    { 0x1E85A87Fu, A78MAP_ROM, 0, 0, 0 },  /* mooncrstu */
    { 0x20C5DB80u, A78MAP_SG, 0, 2, 0 },  /* aceoface */
    { 0x224B93D4u, A78MAP_POKEY, 0, 0, 0 },  /* froggie */
    { 0x297899BBu, A78MAP_ROM, 0, 3, 0 },  /* kungfumu */
    { 0x2A0A93BEu, A78MAP_SG, 0, 2, 0 },  /* fatalrun */
    { 0x2A0D1E6Bu, A78MAP_ROM, 0, 0, 0 },  /* hopman */
    { 0x2B5382B7u, A78MAP_SG, 0, 2, 0 },  /* ninjaglf */
    { 0x2C430BCEu, A78MAP_ROM, 0, 3, 0 },  /* joustu */
    { 0x2C67FEA7u, A78MAP_SG9, 0, 0, 0 },  /* dkongxmups */
    { 0x2F211F7Fu, A78MAP_SG_RAM, 0, 3, 16 },  /* plutos */
    { 0x2FDDAD78u, A78MAP_SG, 0, 3, 0 },  /* sentinelu */
    { 0x30D641FFu, A78MAP_ROM, 0, 0, 0 },  /* santasim */
    { 0x3124B41Cu, A78MAP_ROM, 0, 0, 0 },  /* bonq */
    { 0x33991EE8u, A78MAP_ROM, 0, 2, 0 },  /* dsrtflcn (top 48K) */
    { 0x33F8A8F6u, A78MAP_ROM, 0, 2, 0 },  /* centiped */
    { 0x366777F1u, A78MAP_SG, 0, 3, 0 },  /* darkchamu */
    { 0x372AE19Bu, A78MAP_ROM, 0, 0, 0 },  /* dsrtflcnu */
    { 0x3796705Fu, A78MAP_ROM, 0, 0, 0 },  /* gatop3 */
    { 0x38BB45BAu, A78MAP_SG, 0, 2, 0 },  /* mpsycho */
    { 0x39296DA2u, A78MAP_ROM, 0, 0, 0 },  /* worm */
    { 0x39A316AAu, A78MAP_ACT, A78DB_SWAP8K, 3, 0 },  /* rampage (8K halves swapped) */
    { 0x3A935531u, A78MAP_ROM, 0, 0, 0 },  /* kcmunch */
    { 0x3B1F2F47u, A78MAP_SG_RAM, 0, 3, 8 },  /* impmissu */
    { 0x3CEC4BE8u, A78MAP_SG, 0, 2, 0 },  /* mean18 */
    { 0x3FBE74CEu, A78MAP_POKEY, 0, 3, 0 },  /* devcard */
    { 0x40B629A1u, A78MAP_ROM, 0, 0, 0 },  /* gatop6 */
    { 0x415A28ADu, A78MAP_ROM, 0, 0, 0 },  /* superpacu */
    { 0x419BFF61u, A78MAP_ROM, 0, 3, 0 },  /* chopliftu */
    { 0x435A9A89u, A78MAP_ROM, 0, 0, 0 },  /* xevious */
    { 0x4407BA04u, A78MAP_SG_RAM, 0, 3, 8 },  /* towertopu */
    { 0x45CCA116u, A78MAP_ROM, 0, 0, 0 },  /* guntus */
    { 0x46DD9662u, A78MAP_SG, 0, 2, 0 },  /* scrapdog */
    { 0x47340DF9u, A78MAP_SG, 0, 2, 0 },  /* sentinel */
    { 0x47BE8090u, A78MAP_ROM, 0, 0, 0 },  /* mazy */
    { 0x47E94868u, A78MAP_ROM, 0, 3, 0 },  /* Food Fight (USA) (Beta) */
    { 0x499DE304u, A78MAP_ROM, 0, 0, 0 },  /* mazy2 */
    { 0x4A8F2171u, A78MAP_SG, 0, 3, 0 },  /* meltdownu */
    { 0x4BAEAC35u, A78MAP_ROM, 0, 0, 0 },  /* ultrapac */
    { 0x4D634BF5u, A78MAP_ACT, 0, 0, 0 },  /* ddragon */
    { 0x4E3B9E64u, A78MAP_SG, 0, 3, 0 },  /* planetsmu */
    { 0x5049E4BEu, A78MAP_ROM, 0, 0, 0 },  /* crazyottou */
    { 0x50CB13F3u, A78MAP_ROM, 0, 3, 0 },  /* digdugu */
    { 0x50FD19CBu, A78MAP_SG, 0, 2, 0 },  /* cracked */
    { 0x513CB9EEu, A78MAP_ROM, 0, 3, 0 },  /* tomcatu */
    { 0x553EA894u, A78MAP_ROM, 0, 0, 0 },  /* paccollu */
    { 0x56239D62u, A78MAP_ROM, 0, 0, 0 },  /* astdeluxu */
    { 0x5637C44Au, A78MAP_ROM, 0, 0, 0 },  /* crazyotto */
    { 0x56AC5864u, A78MAP_ROM, 0, 0, 0 },  /* failsafe */
    { 0x59677A47u, A78MAP_ROM, 0, 0, 0 },  /* cracky */
    { 0x5990A9F8u, A78MAP_ROM, 0, 2, 0 },  /* galaga */
    { 0x5999A36Eu, A78MAP_ROM, 0, 0, 0 },  /* hattricku */
    { 0x5CC8C34Fu, A78MAP_SG, 0, 3, 0 },  /* scrapdogu */
    { 0x5D13730Cu, A78MAP_ROM, 0, 0, 0 },  /* [BIOS] Atari 7800 (USA) */
    { 0x5D3BABDCu, A78MAP_ROM, 0, 0, 0 },  /* mieyen */
    { 0x5FD9A141u, A78MAP_SG, 0, 3, 0 },  /* xenophobu */
    { 0x63D1C7C1u, A78MAP_ABS, 0, 3, 0 },  /* f18u */
    { 0x64D9C4BEu, A78MAP_SG, 0, 2, 0 },  /* fightn */
    { 0x6510B674u, A78MAP_SG9, 0, 0, 0 },  /* dkongxmps */
    { 0x65AE616Eu, A78MAP_SG_RAM, 0, 3, 16 },  /* sirius */
    { 0x65C6DF3Fu, A78MAP_SG_RAM, 0, 3, 16 },  /* sumgames */
    { 0x67C8AF57u, A78MAP_ROM, 0, 0, 0 },  /* starwarsu */
    { 0x67EBF1EDu, A78MAP_ROM, 0, 0, 0 },  /* failsafeu */
    { 0x68D48FDCu, A78MAP_ROM, 0, 2, 0 },  /* baseball */
    { 0x6A19F0FEu, A78MAP_SG9, 0, 2, 0 },  /* alienbrg */
    { 0x6B27EA2Cu, A78MAP_ROM, 0, 2, 0 },  /* suphuey */
    { 0x6C8D9E68u, A78MAP_SG, 0, 2, 0 },  /* karateka */
    { 0x6DDFB54Cu, A78MAP_ROM, 0, 3, 0 },  /* Asteroids (USA) (Beta) */
    { 0x6E170055u, A78MAP_SG9, 0, 0, 0 },  /* dkongxmou */
    { 0x6FD15498u, A78MAP_ROM, 0, 3, 0 },  /* xeviousup */
    { 0x715E1A2Fu, A78MAP_ROM, 0, 0, 0 },  /* gatop1 */
    { 0x716476EDu, A78MAP_ROM, 0, 0, 0 },  /* svellas */
    { 0x71846500u, A78MAP_ROM, 0, 3, 0 },  /* suphueyu */
    { 0x720EBC74u, A78MAP_SG, 0, 3, 0 },  /* fightnu */
    { 0x729DD769u, A78MAP_ROM, 0, 2, 0 },  /* diagtestp */
    { 0x72BD4BFDu, A78MAP_ROM, 0, 0, 0 },  /* dkongu */
    { 0x7419E768u, A78MAP_ROM, 0, 0, 0 },  /* cacorm */
    { 0x74517C71u, A78MAP_ROM, 0, 0, 0 },  /* paccoll */
    { 0x75FC124Fu, A78MAP_ROM, 0, 3, 0 },  /* xeviousu */
    { 0x7873B949u, A78MAP_POKEY, 0, 0, 0 },  /* beefdrop */
    { 0x795BD49Fu, A78MAP_ROM, 0, 0, 0 },  /* mariou */
    { 0x7A4D622Cu, A78MAP_ROM, 0, 0, 0 },  /* readriot */
    { 0x7A628295u, A78MAP_ROM, 0, 2, 0 },  /* 1on1 */
    { 0x7B3DFD62u, A78MAP_ROM, 0, 0, 0 },  /* bootskell */
    { 0x7C211612u, A78MAP_SG_POKEY, 0, 2, 0 },  /* commando */
    { 0x7CA6D521u, A78MAP_SG, 0, 2, 0 },  /* midnight */
    { 0x7D9370FBu, A78MAP_ROM, 0, 3, 0 },  /* 1on1u */
    { 0x7EA09C07u, A78MAP_ROM, 0, 0, 0 },  /* dkong */
    { 0x8021A13Bu, A78MAP_ROM, 0, 3, 0 },  /* Mario Bros. (USA) */
    { 0x80AC3695u, A78MAP_ROM, 0, 0, 0 },  /* mooncrst */
    { 0x8421033Au, A78MAP_ROM, 0, 2, 0 },  /* mspacman */
    { 0x8560A801u, A78MAP_ROM, 0, 0, 0 },  /* hangly */
    { 0x8678F1C0u, A78MAP_ROM, 0, 0, 0 },  /* starwars */
    { 0x885C29AFu, A78MAP_ROM, 0, 0, 0 },  /* cavit */
    { 0x8981B531u, A78MAP_SG_RAM, 0, 3, 16 },  /* wingames */
    { 0x8A6C1F15u, A78MAP_SG, 0, 3, 0 },  /* ikariu */
    { 0x8AACF980u, A78MAP_ROM, 0, 0, 0 },  /* dkongjru */
    { 0x8B06BB4Bu, A78MAP_SG9, 0, 0, 0 },  /* dkongxmu */
    { 0x8F167BA9u, A78MAP_ROM, 0, 2, 0 },  /* supskate */
    { 0x90D7AAD3u, A78MAP_ROM, 0, 0, 0 },  /* spaceinv */
    { 0x9207ED3Bu, A78MAP_SG_RAM, 0, 2, 8 },  /* jinks */
    { 0x930B30DFu, A78MAP_SG, 0, 3, 0 },  /* waterski */
    { 0x938B753Eu, A78MAP_ROM, 0, 0, 0 },  /* hattrick */
    { 0x95DC7E96u, A78MAP_SG, 0, 2, 0 },  /* planetsm */
    { 0x993046EDu, A78MAP_ROM, 0, 0, 0 },  /* neuras */
    { 0x994AF6E0u, A78MAP_SG_RAM, 0, 2, 8 },  /* impmiss */
    { 0x9A74FBF2u, A78MAP_MRAM, 0, 3, 2 },  /* fractal */
    { 0x9B3BE616u, A78MAP_ROM, 0, 2, 0 },  /* joust */
    { 0x9BE408D3u, A78MAP_HSC, 0, 2, 0 },  /* hiscore */
    { 0x9C3086EBu, A78MAP_ROM, 0, 0, 0 },  /* spaceinvu */
    { 0x9F6C0600u, A78MAP_SG9, 0, 0, 0 },  /* dkongxm */
    { 0x9FA0FBDAu, A78MAP_ROM, 0, 0, 0 },  /* gatop5 */
    { 0xA0529DB5u, A78MAP_ROM, 0, 3, 0 },  /* GATO (USA) (Proto) */
    { 0xA0A0DA0Cu, A78MAP_ROM, 0, 0, 0 },  /* impetus */
    { 0xA1DC0899u, A78MAP_ROM, 0, 3, 0 },  /* dsrtflcnu (top 48K) */
    { 0xA1EAA7C1u, A78MAP_ROM, 0, 3, 0 },  /* diagtest */
    { 0xA4199A30u, A78MAP_ROM, 0, 0, 0 },  /* battlot */
    { 0xA4265D4Bu, A78MAP_SG, 0, 2, 0 },  /* bsktbrwl */
    { 0xA44DF354u, A78MAP_SG, 0, 3, 0 },  /* fatalrunu */
    { 0xA4C4808Bu, A78MAP_POKEY, 0, 3, 0 },  /* ballblazu */
    { 0xA56FF7EAu, A78MAP_ROM, 0, 0, 0 },  /* dsrtflcn */
    { 0xA5E75537u, A78MAP_SG, 0, 3, 0 },  /* pitfight */
    { 0xA85FB962u, A78MAP_ROM, 0, 3, 0 },  /* polepos2u */
    { 0xAA265865u, A78MAP_ACT, A78DB_SWAP8K, 3, 0 },  /* ddragonu (8K halves swapped) */
    { 0xAAE12695u, A78MAP_SG, 0, 3, 0 },  /* tdown */
    { 0xAB65A41Du, A78MAP_ROM, 0, 0, 0 },  /* ripoffu */
    { 0xAB72EA89u, A78MAP_ROM, 0, 0, 0 },  /* astdelux */
    { 0xABA91829u, A78MAP_SG, 0, 3, 0 },  /* matmaniau */
    { 0xAD176C55u, A78MAP_ROM, 0, 0, 0 },  /* yewdow */
    { 0xAFF85565u, A78MAP_POKEY, 0, 2, 0 },  /* ballblaz */
    { 0xB01205BFu, A78MAP_ROM, 0, 2, 0 },  /* tomcat */
    { 0xB05CF8D2u, A78MAP_ROM, 0, 0, 0 },  /* gatop7 */
    { 0xB1508030u, A78MAP_SG, 0, 3, 0 },  /* rsbaseb */
    { 0xB1C8D47Du, A78MAP_ROM, 0, 0, 0 },  /* ripoff */
    { 0xB223E461u, A78MAP_ROM, 0, 0, 0 },  /* osotos */
    { 0xB367966Eu, A78MAP_ROM, 0, 0, 0 },  /* dkongjr */
    { 0xB4557DD7u, A78MAP_ROM, 0, 0, 0 },  /* mspacatk */
    { 0xB8678FA6u, A78MAP_ROM, 0, 0, 0 },  /* foodfup */
    { 0xB89E3605u, A78MAP_ROM, 0, 0, 0 },  /* awass */
    { 0xBC23C57Bu, A78MAP_ROM, 0, 3, 0 },  /* prowresu */
    { 0xBFCE8DEEu, A78MAP_ROM, 0, 0, 0 },  /* antiair */
    { 0xC1531FC4u, A78MAP_ROM, 0, 2, 0 },  /* kungfum */
    { 0xC4B61D17u, A78MAP_SG_RAM, 0, 0, 8 },  /* impmissbf */
    { 0xC5149EF4u, A78MAP_ROM, 0, 0, 0 },  /* dsrtflcna */
    { 0xC64549ECu, A78MAP_ROM, 0, 2, 0 },  /* foodf */
    { 0xC784DBACu, A78MAP_ROM, 0, 2, 0 },  /* Donkey Kong Junior (Europe) */
    { 0xC8849D36u, A78MAP_SG9, 0, 3, 0 },  /* alienbrgu */
    { 0xC8B9D7B5u, A78MAP_SG, 0, 3, 0 },  /* bsktbrwlu */
    { 0xC93A563Eu, A78MAP_SG, 0, 2, 0 },  /* darkcham */
    { 0xCB22305Du, A78MAP_ROM, 0, 3, 0 },  /* robotron */
    { 0xCB48E8DCu, A78MAP_SG, 0, 3, 0 },  /* ninjaglfu */
    { 0xCB621CDCu, A78MAP_SG, 0, 2, 0 },  /* ikari */
    { 0xCCDC2DBFu, A78MAP_ROM, 0, 0, 0 },  /* wasp */
    { 0xCD1A98C5u, A78MAP_SG_POKEY, 0, 3, 0 },  /* commandou */
    { 0xCF0E44F1u, A78MAP_SG, 0, 2, 0 },  /* xenophob */
    { 0xCF21D9ACu, A78MAP_SG, 0, 3, 0 },  /* mean18u */
    { 0xCF648E88u, A78MAP_SG_RAM, 0, 0, 16 },  /* wingameso */
    { 0xCF6F4A6Cu, A78MAP_ROM, 0, 3, 0 },  /* hattricku (top 48K) */
    { 0xD18640F0u, A78MAP_ROM, 0, 0, 0 },  /* astrof */
    { 0xD2876EE2u, A78MAP_ACT, 0, 0, 0 },  /* rampage */
    { 0xD2EA5686u, A78MAP_SG9, 0, 3, 0 },  /* crossbowu */
    { 0xD34FD674u, A78MAP_ROM, 0, 0, 0 },  /* lift */
    { 0xD362712Eu, A78MAP_SG9, 0, 0, 0 },  /* dkongxmo */
    { 0xD44622B3u, A78MAP_UNSUPPORTED, 0, 0, 0 },  /* bentley */
    { 0xD581EF7Bu, A78MAP_ROM, 0, 0, 0 },  /* ascend */
    { 0xD5AC738Bu, A78MAP_ROM, 0, 2, 0 },  /* xevious (top 48K) */
    { 0xD5B61170u, A78MAP_ROM, 0, 0, 0 },  /* [BIOS] Atari 7800 (Europe) */
    { 0xD5D08D7Eu, A78MAP_ROM, 0, 0, 0 },  /* pacman */
    { 0xD751C7A6u, A78MAP_ROM, 0, 2, 0 },  /* polepos2 */
    { 0xD98BC2F8u, A78MAP_ROM, 0, 3, 0 },  /* 7800 Monitor Cart (USA) (Program) (Unl) */
    { 0xDB91B181u, A78MAP_SG, 0, 3, 0 },  /* tank */
    { 0xDFB93F40u, A78MAP_ROM, 0, 3, 0 },  /* asteroid */
    { 0xE2DC056Eu, A78MAP_ROM, 0, 0, 0 },  /* pacplus */
    { 0xE42FC700u, A78MAP_ROM, 0, 3, 0 },  /* mspacmanu */
    { 0xE51EB3BCu, A78MAP_ROM, 0, 0, 0 },  /* gatop8 */
    { 0xE5D714B0u, A78MAP_ABS, 0, 2, 0 },  /* f18 */
    { 0xE645FD1Fu, A78MAP_SG, 0, 3, 0 },  /* crackedu */
    { 0xE64A5CDEu, A78MAP_ROM, 0, 3, 0 },  /* foodfu */
    { 0xE8C2A662u, A78MAP_SG, 0, 3, 0 },  /* rampart */
    { 0xE920A2DCu, A78MAP_ROM, 0, 0, 0 },  /* superpac */
    { 0xE93D8894u, A78MAP_SG9, 0, 2, 0 },  /* crossbow */
    { 0xEA240BF3u, A78MAP_ROM, 0, 0, 0 },  /* meteorsh */
    { 0xEA42FF6Eu, A78MAP_ROM, 0, 0, 0 },  /* scramble */
    { 0xED0A587Du, A78MAP_SG, 0, 3, 0 },  /* barnblstu */
    { 0xEF2D2560u, A78MAP_ROM, 0, 0, 0 },  /* spacduelu */
    { 0xEFAB7077u, A78MAP_ROM, 0, 2, 0 },  /* digdug */
    { 0xEFAD3D9Du, A78MAP_ROM, 0, 2, 0 },  /* mario */
    { 0xF20773D5u, A78MAP_ACT, 0, 0, 0 },  /* ddragonu */
    { 0xF26621E3u, A78MAP_SG, 0, 3, 0 },  /* klax */
    { 0xF29ABDB2u, A78MAP_ACT, A78DB_SWAP8K, 2, 0 },  /* ddragon (8K halves swapped) */
    { 0xF33D4DFAu, A78MAP_ROM, 0, 3, 0 },  /* baseballu */
    { 0xFD40B838u, A78MAP_ROM, 0, 0, 0 },  /* polepos2p */
    { 0xFD503BD4u, A78MAP_SG9, 0, 0, 0 },  /* dkongxmcc */
    { 0xFEC21472u, A78MAP_ROM, 0, 3, 0 },  /* karatekau */
    { 0xFF6DD806u, A78MAP_ROM, 0, 0, 0 },  /* astrob */
    { 0xFF7A4C60u, A78MAP_SG9, 0, 3, 0 },  /* mia */
};

const unsigned a78map_db_count = sizeof a78map_db / sizeof a78map_db[0];
