#!/usr/bin/env bash
# apply.sh -- graft the FujiNet Atari 7800 cartridge device into a MAME tree.
#
# Usage: ./apply.sh /path/to/mame
#
# Copies the device model (fujinet.cpp/h, fujitcp.c/h) and the cartridge
# firmware's own sources (fujimail, fujibus, a78map, fuji_load, hsc, the bus
# decode, the baked CONFIG, loader and boot block) into
# src/devices/bus/a7800/, and edits:
#
#   scripts/src/bus.lua              the a7800 file list
#   src/devices/bus/a7800/a78_carts.h  a selectable "fujinet" slot option
#
# The device installs its own handlers; the 7800 driver is not touched.
# Idempotent: run it again after editing any source here. The generated
# headers come from build/gen (../build-cart.sh) or firmware/baked/.
#
# Afterwards: make -C /path/to/mame -j$(nproc) REGENIE=1 NOWERROR=1
# (REGENIE=1 the first time, because bus.lua changed).

set -euo pipefail
cd "$(dirname "$0")"

MAME=${1:?usage: apply.sh /path/to/mame}
BUSDIR="$MAME/src/devices/bus/a7800"
BUSLUA="$MAME/scripts/src/bus.lua"
CARTS="$BUSDIR/a78_carts.h"
FW=../firmware
GEN=../build/gen
[ -f "$GEN/fujiconfigrom.h" ] || GEN=$FW/baked      # no fresh build: the baked set

[ -d "$BUSDIR" ] || { echo "apply.sh: $BUSDIR missing" >&2; exit 1; }
for f in fujiconfigrom.h a78loaderrom.h a78bootblk.h; do
    [ -f "$GEN/$f" ] || { echo "apply.sh: $GEN/$f missing; run ../build-cart.sh" >&2; exit 1; }
done

# MAME forces a C++ precompiled header on every device file, so the shared C
# sources go in under .cpp names (they build both ways).
cp fujinet.cpp fujinet.h fujitcp.h "$BUSDIR/"
cp fujitcp.c "$BUSDIR/fujitcp.cpp"
for f in fujimail fujibus a78map a78map_db fuji_load hsc; do
    cp "$FW/src/$f.c" "$BUSDIR/$f.cpp"
done
cp "$FW/include/fujimail.h" "$FW/include/fujibus.h" "$FW/include/fuji_mailbox.h" \
   "$FW/include/a78_cart.h" "$FW/include/a78map.h" "$FW/include/a78map_db.h" \
   "$FW/include/fuji_load.h" "$FW/include/hsc.h" \
   "$GEN/fujiconfigrom.h" "$GEN/a78loaderrom.h" "$GEN/a78bootblk.h" "$BUSDIR/"

# fujimail.c, fujibus.c and fujitcp.c carry the same symbols in every FujiNet
# port, and several ports share this tree: give this copy its own.
{
    echo "/* GENERATED by pico/atari-7800/emu/apply.sh -- do not edit. */"
    echo "#ifndef A78_FUJINS_H"
    echo "#define A78_FUJINS_H"
    for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
               fujibus_build_request fujibus_parse_reply fujibus_selftest \
               fujitcp_init fujitcp_active fujitcp_close fujitcp_transact \
               fujitcp_send_bare fuji_load_init fuji_load_stage fuji_load_unstage \
               fuji_load_arm fuji_load_busy fuji_load_event fuji_load_ack \
               fuji_load_abort fuji_load_handover fuji_load_slices fuji_load_slice \
               hsc_init hsc_restore hsc_service hsc_save_chunk; do
        echo "#define $sym a78_$sym"
    done
    echo "#endif"
} > "$BUSDIR/fujins.h"

for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fujitcp.cpp fujitcp.h \
         fuji_load.cpp fuji_load.h hsc.cpp hsc.h; do
    if ! head -1 "$BUSDIR/$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$BUSDIR/$f")" > "$BUSDIR/$f.tmp"
        mv "$BUSDIR/$f.tmp" "$BUSDIR/$f"
    fi
done

if ! grep -q "a7800/fujinet.cpp" "$BUSLUA"; then
    python3 - "$BUSLUA" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
anchor = '\t\tMAME_DIR .. "src/devices/bus/a7800/rom.h",\n'
if anchor not in text:
    sys.exit("apply.sh: bus.lua anchor line not found")
files = ("fujinet.cpp", "fujinet.h", "fujitcp.cpp", "fujitcp.h", "fujimail.cpp",
         "fujimail.h", "fujibus.cpp", "fujibus.h", "a78map.cpp", "a78map.h",
         "a78map_db.cpp", "a78map_db.h", "fuji_load.cpp", "fuji_load.h", "hsc.cpp",
         "hsc.h", "fuji_mailbox.h", "a78_cart.h", "fujiconfigrom.h", "a78loaderrom.h",
         "a78bootblk.h", "fujins.h")
addition = anchor + "".join('\t\tMAME_DIR .. "src/devices/bus/a7800/%s",\n' % f for f in files)
open(path, "w").write(text.replace(anchor, addition, 1))
EOF2
    echo "apply.sh: bus.lua updated (build with REGENIE=1)"
fi

if ! grep -q "A78_FUJINET" "$CARTS"; then
    python3 - "$CARTS" <<'EOF2'
import sys
path = sys.argv[1]
text = open(path).read()
inc = '#include "cpuwiz.h"\n'
if inc not in text:
    sys.exit("apply.sh: a78_carts.h include anchor not found")
text = text.replace(inc, inc + '#include "fujinet.h"\n', 1)
anchor = 'static void a7800_cart(device_slot_interface &device)\n{\n'
if anchor not in text:
    sys.exit("apply.sh: a78_carts.h option list not found")
opt = ('\t// FujiNet cartridge (pico/atari-7800 in fujinet-firmware): selectable\n'
       '\tdevice.option_add("fujinet",      A78_FUJINET);\n')
text = text.replace(anchor, anchor + opt, 1)
open(path, "w").write(text)
EOF2
    echo "apply.sh: a78_carts.h updated"
fi

echo "apply.sh: done"
