#ifndef FUJI_DEVICES_H
#define FUJI_DEVICES_H

enum FujiDeviceID {
  FUJI_DEVICEID_FUJINET      = 0x70,

  FUJI_DEVICEID_CLOCK        = 0x45,
  FUJI_DEVICEID_CPM          = 0x5A,
  FUJI_DEVICEID_DISK         = 0x31,
  FUJI_DEVICEID_DISK_LAST    = 0x3F,
  FUJI_DEVICEID_MIDI         = 0x99,
  FUJI_DEVICEID_NETWORK      = 0x71,
  FUJI_DEVICEID_NETWORK_LAST = 0x78,
  FUJI_DEVICEID_PRINTER      = 0x40,
  FUJI_DEVICEID_PRINTER_LAST = 0x43,
  FUJI_DEVICEID_SERIAL       = 0x50,
  FUJI_DEVICEID_SERIAL_LAST  = 0x53,
  FUJI_DEVICEID_VOICE        = 0x43,
};

#endif /* FUJI_DEVICES_H */
