#ifndef FUJI_DEVICES_H
#define FUJI_DEVICES_H

#if defined(BUILD_ADAM) || defined(BUILD_LYNX)
enum fujiDeviceID_t {
  FUJI_DEVICEID_FUJINET      = 0x0F,

  FUJI_DEVICEID_KEYBOARD     = 0x01,
  FUJI_DEVICEID_PRINTER      = 0x02,
  FUJI_DEVICEID_DISK         = 0x04,
  FUJI_DEVICEID_DISK2        = 0x05,
  FUJI_DEVICEID_DISK3        = 0x06,
  FUJI_DEVICEID_DISK4        = 0x07,
  FUJI_DEVICEID_TAPE         = 0x08,
  FUJI_DEVICEID_NETWORK_TEMP = 0x09,
  FUJI_DEVICEID_NETWORK      = 0x0E,
};
#else
enum fujiDeviceID_t {
  FUJI_DEVICEID_FUJINET      = 0x70,

  FUJI_DEVICEID_DISK         = 0x31,
  FUJI_DEVICEID_DISK_LAST    = 0x3F,
  FUJI_DEVICEID_PRINTER      = 0x40,
  FUJI_DEVICEID_PRINTER_LAST = 0x43,
  FUJI_DEVICEID_VOICE        = 0x43,
  FUJI_DEVICEID_CLOCK        = 0x45,
  FUJI_DEVICEID_SIO2BT_SMART = 0x45, // Doubles as APETime and "High Score Submission" to URL
  FUJI_DEVICEID_ASPEQT       = 0x46,
  FUJI_DEVICEID_SIO2BT_NET   = 0x4E,
  FUJI_DEVICEID_TYPE3POLL    = 0x4F,
  FUJI_DEVICEID_SERIAL       = 0x50,
  FUJI_DEVICEID_SERIAL_LAST  = 0x53,
  FUJI_DEVICEID_CPM          = 0x5A,
  FUJI_DEVICEID_CASSETTE     = 0x5F,
  FUJI_DEVICEID_PCLINK       = 0x6F,
  FUJI_DEVICEID_NETWORK      = 0x71,
  FUJI_DEVICEID_NETWORK_LAST = 0x78,
  FUJI_DEVICEID_MIDI         = 0x99,
};
#endif /* BUILD_ADAM || BUILD_LYNX */

#endif /* FUJI_DEVICES_H */
