#ifndef FUJI_COMMANDS_H
#define FUJI_COMMANDS_H

#include <stdint.h>

/*
 * Fuji Device Command Definitions
 */

enum fujiCommandID_t : uint8_t {
    FUJICMD_RESET                      = 0xFF,
    FUJICMD_GET_SSID                   = 0xFE,
    FUJICMD_SCAN_NETWORKS              = 0xFD,
    FUJICMD_GET_SCAN_RESULT            = 0xFC,
    FUJICMD_SET_SSID                   = 0xFB,
    FUJICMD_GET_WIFISTATUS             = 0xFA,
    FUJICMD_MOUNT_HOST                 = 0xF9,
    FUJICMD_MOUNT_IMAGE                = 0xF8,
    FUJICMD_OPEN_DIRECTORY             = 0xF7,
    FUJICMD_READ_DIR_ENTRY             = 0xF6,
    FUJICMD_CLOSE_DIRECTORY            = 0xF5,
    FUJICMD_READ_HOST_SLOTS            = 0xF4,
    FUJICMD_WRITE_HOST_SLOTS           = 0xF3,
    FUJICMD_READ_DEVICE_SLOTS          = 0xF2,
    FUJICMD_WRITE_DEVICE_SLOTS         = 0xF1,
    FUJICMD_ENABLE_UDPSTREAM           = 0xF0,
    FUJICMD_SET_BAUDRATE               = 0xEB,
    FUJICMD_GET_WIFI_ENABLED           = 0xEA,
    FUJICMD_UNMOUNT_IMAGE              = 0xE9,
    FUJICMD_GET_ADAPTERCONFIG          = 0xE8,
    FUJICMD_NEW_DISK                   = 0xE7,
    FUJICMD_UNMOUNT_HOST               = 0xE6,
    FUJICMD_GET_DIRECTORY_POSITION     = 0xE5,
    FUJICMD_SET_DIRECTORY_POSITION     = 0xE4,
    FUJICMD_SET_HSIO_INDEX             = 0xE3,
    FUJICMD_SET_DEVICE_FULLPATH        = 0xE2,
    FUJICMD_SET_HOST_PREFIX            = 0xE1,
    FUJICMD_GET_HOST_PREFIX            = 0xE0,
    FUJICMD_SET_SIO_EXTERNAL_CLOCK     = 0xDF,
    FUJICMD_WRITE_APPKEY               = 0xDE,
    FUJICMD_READ_APPKEY                = 0xDD,
    FUJICMD_OPEN_APPKEY                = 0xDC,
    FUJICMD_CLOSE_APPKEY               = 0xDB,
    FUJICMD_GET_DEVICE_FULLPATH        = 0xDA,
    FUJICMD_CONFIG_BOOT                = 0xD9,
    FUJICMD_COPY_FILE                  = 0xD8,
    FUJICMD_MOUNT_ALL                  = 0xD7,
    FUJICMD_SET_BOOT_MODE              = 0xD6,
    FUJICMD_ENABLE_DEVICE              = 0xD5,
    FUJICMD_DISABLE_DEVICE             = 0xD4,
    FUJICMD_RANDOM_NUMBER              = 0xD3,
    FUJICMD_GET_TIME                   = 0xD2,
    FUJICMD_DEVICE_ENABLE_STATUS       = 0xD1,
    FUJICMD_BASE64_ENCODE_INPUT        = 0xD0,
    FUJICMD_BASE64_ENCODE_COMPUTE      = 0xCF,
    FUJICMD_BASE64_ENCODE_LENGTH       = 0xCE,
    FUJICMD_BASE64_ENCODE_OUTPUT       = 0xCD,
    FUJICMD_BASE64_DECODE_INPUT        = 0xCC,
    FUJICMD_BASE64_DECODE_COMPUTE      = 0xCB,
    FUJICMD_BASE64_DECODE_LENGTH       = 0xCA,
    FUJICMD_BASE64_DECODE_OUTPUT       = 0xC9,
    FUJICMD_HASH_INPUT                 = 0xC8,
    FUJICMD_HASH_COMPUTE               = 0xC7,
    FUJICMD_HASH_LENGTH                = 0xC6,
    FUJICMD_HASH_OUTPUT                = 0xC5,
    FUJICMD_GET_ADAPTERCONFIG_EXTENDED = 0xC4,
    FUJICMD_HASH_COMPUTE_NO_CLEAR      = 0xC3,
    FUJICMD_HASH_CLEAR                 = 0xC2,
    FUJICMD_GET_HEAP                   = 0xC1,
    FUJICMD_QRCODE_OUTPUT              = 0xBF,
    FUJICMD_QRCODE_LENGTH              = 0xBE,
    FUJICMD_QRCODE_ENCODE              = 0xBD,
    FUJICMD_QRCODE_INPUT               = 0xBC,
    FUJICMD_GENERATE_GUID              = 0xBB,
    FUJICMD_GET_DEVICE8_FULLPATH       = 0xA7,
    FUJICMD_GET_DEVICE7_FULLPATH       = 0xA6,
    FUJICMD_GET_DEVICE6_FULLPATH       = 0xA5,
    FUJICMD_GET_DEVICE5_FULLPATH       = 0xA4,
    FUJICMD_GET_DEVICE4_FULLPATH       = 0xA3,
    FUJICMD_GET_DEVICE3_FULLPATH       = 0xA2,
    FUJICMD_GET_DEVICE2_FULLPATH       = 0xA1,
    FUJICMD_GET_DEVICE1_FULLPATH       = 0xA0,
    FUJICMD_STATUS                     = 0x53, // S
    FUJICMD_HSIO_INDEX                 = 0x3F, // ?
    FUJICMD_NAK                        = 0x15, // ASCII NAK
    FUJICMD_ACK                        = 0x06, // ASCII ACK
    FUJICMD_SEND_ERROR                 = 0x02,
    FUJICMD_SEND_RESPONSE              = 0x01,
    FUJICMD_DEVICE_READY               = 0x00,

    DISKCMD_HSIO_WRITE                 = 0xD7,
    DISKCMD_HSIO_STATUS                = 0xD3,
    DISKCMD_HSIO_READ                  = 0xD2,
    DISKCMD_HSIO_PUT                   = 0xD0,
    DISKCMD_HSIO_FORMAT_MEDIUM         = 0xA2,
    DISKCMD_HSIO_FORMAT                = 0xA1,
    DISKCMD_WRITE                      = 0x57, // W
    DISKCMD_STATUS                     = 0x53, // S
    DISKCMD_READ                       = 0x52, // R
    DISKCMD_PUT                        = 0x50, // P
    DISKCMD_PERCOM_WRITE               = 0x4F, // O
    DISKCMD_PERCOM_READ                = 0x4E, // N
    DISKCMD_HSIO_INDEX                 = 0x3F, // ?
    DISKCMD_FORMAT_MEDIUM              = 0x22, // "
    DISKCMD_FORMAT                     = 0x21, // !

    NETCMD_SPECIAL_INQUIRY             = 0xFF,
    NETCMD_PASSWORD                    = 0xFE,
    NETCMD_USERNAME                    = 0xFD,
    NETCMD_CHANNEL_MODE                = 0xFC,
    NETCMD_SET_PARAMETERS              = 0xFB,
    NETCMD_SET_HSIO_INDEX              = 0xE3,
    NETCMD_QUERY_ALT                   = 0x81,
    NETCMD_PARSE_ALT                   = 0x80,
    NETCMD_GET_REMOTE                  = 0x72, // r
    NETCMD_CLOSE_CLIENT                = 0x63, // c
    NETCMD_SET_INT_RATE                = 0x5A, // Z
    NETCMD_WRITE                       = 0x57, // W
    NETCMD_TRANSLATION                 = 0x54, // T
    NETCMD_STATUS                      = 0x53, // S
    NETCMD_READ                        = 0x52, // R
    NETCMD_QUERY                       = 0x51, // Q
    NETCMD_PARSE                       = 0x50, // P
    NETCMD_OPEN                        = 0x4F, // O
    NETCMD_UNLISTEN                    = 0x4D, // M
    NETCMD_GET_ERROR                   = 0x45, // E
    NETCMD_SET_DESTINATION             = 0x44, // D
    NETCMD_CLOSE                       = 0x43, // C
    NETCMD_CONTROL                     = 0x41, // A
    NETCMD_HSIO_INDEX                  = 0x3F, // ?
    NETCMD_GETCWD                      = 0x30, // 0
    NETCMD_CHDIR                       = 0x2C, // ,
    NETCMD_RMDIR                       = 0x2B, // +
    NETCMD_MKDIR                       = 0x2A, // *
    NETCMD_TELL                        = 0x26, // &
    NETCMD_SEEK                        = 0x25, // %
    NETCMD_UNLOCK                      = 0x24, // $
    NETCMD_LOCK                        = 0x23, // #
    NETCMD_DELETE                      = 0x21, // !
    NETCMD_RENAME                      = 0x20,
    NETCMD_SEND_ERROR                  = 0x02,
    NETCMD_SEND_RESPONSE               = 0x01,
    NETCMD_DEVICE_READY                = 0x00,

    MODEMCMD_STREAM                    = 0x58, // X
    MODEMCMD_WRITE                     = 0x57, // W
    MODEMCMD_STATUS                    = 0x53, // S
    MODEMCMD_AUTOANSWER                = 0x4F, // O
    MODEMCMD_BAUDRATELOCK              = 0x4E, // N
    MODEMCMD_UNLISTEN                  = 0x4D, // M
    MODEMCMD_LISTEN                    = 0x4C, // L
    MODEMCMD_SET_DUMP                  = 0x44, // D
    MODEMCMD_CONFIGURE                 = 0x42, // B
    MODEMCMD_CONTROL                   = 0x41, // A
    MODEMCMD_TYPE3_POLL                = 0x40, // @
    MODEMCMD_TYPE1_POLL                = 0x3F, // ?
    MODEMCMD_LOAD_HANDLER              = 0x26, // &
    MODEMCMD_LOAD_RELOCATOR            = 0x21, // !

    APETIMECMD_GETTZTIME               = 0x9A,
    APETIMECMD_SETTZ                   = 0x99,
    APETIMECMD_GETTIME                 = 0x93,
    APETIMECMD_GET_ISO_UTC_ALT         = 0x7A, // z
    APETIMECMD_SETTZ_ALT               = 0x74, // t
    APETIMECMD_GET_SOS_ALT             = 0x73, // s
    APETIMECMD_GET_PRODOS_ALT          = 0x70, // p
    APETIMECMD_GET_ISO_LOCAL_ALT       = 0x69, // i
    APETIMECMD_GET_ATARI_ALT           = 0x61, // a
    APETIMECMD_GET_ISO_UTC             = 0x5A, // Z
    APETIMECMD_SETTZ_ALT2              = 0x54, // T
    APETIMECMD_GET_SOS                 = 0x53, // S
    APETIMECMD_GET_PRODOS              = 0x50, // P
    APETIMECMD_GETTZ_LEN               = 0x4C, // L
    APETIMECMD_GET_ISO_LOCAL           = 0x49, // I
    APETIMECMD_GET_GENERAL             = 0x47, // G
    APETIMECMD_GET_ATARI               = 0x41, // A
};

#endif /* FUJI_COMMANDS_H */
