#!/usr/bin/env python3
"""Pack the loader page into the C array the cart serves at $B800.

    tools/mkloaderh.py build/loader.bin > build/gen/smsloaderrom.h
"""
import sys

if len(sys.argv) != 2:
    sys.exit("usage: mkloaderh.py <loader.bin>")

data = open(sys.argv[1], "rb").read()
if len(data) > 2048:
    sys.exit("%s is %d bytes: the loader page is 2048" % (sys.argv[1], len(data)))
data = data + b"\xff" * (2048 - len(data))

print("/* smsloaderrom.h -- GENERATED by tools/mkloaderh.py, do not edit. */")
print()
print("#ifndef SMSLOADERROM_H")
print("#define SMSLOADERROM_H")
print()
print("#define FUJI_LOADERROM_SIZE %d" % len(data))
print()
print("static const unsigned char _loaderrom[FUJI_LOADERROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* SMSLOADERROM_H */")
