#!/usr/bin/env python3
"""mkmapdb.py -- the cart's mapper database, from MAME's SMS software list.

Every sms.xml entry becomes {CRC-32 of the whole image, mapper, cart RAM}, so
a known image gets exactly the board MAME's software list gives it. Multi-chip
entries are keyed by the CRC of their chips concatenated.

Usage: mkmapdb.py ~/Workspace/mame/hash/sms.xml > firmware/src/smsmap_db.c
"""

import sys
import xml.etree.ElementTree as ET

KINDS = {"rom": "SMSMAP_SEGA", "codemasters": "SMSMAP_CODEMASTERS",
         "korean": "SMSMAP_KOREAN", "korean_nb": "SMSMAP_KOREAN_NB",
         "zemina": "SMSMAP_ZEMINA", "nemesis": "SMSMAP_NEMESIS",
         "janggun": "SMSMAP_JANGGUN", "4pak": "SMSMAP_4PAK"}


def gf2_times(mat, vec):
    s = 0
    i = 0
    while vec:
        if vec & 1:
            s ^= mat[i]
        vec >>= 1
        i += 1
    return s


def gf2_square(mat):
    return [gf2_times(mat, mat[n]) for n in range(32)]


def crc32_combine(crc1, crc2, len2):
    """zlib's crc32_combine: the CRC of A+B from crc(A), crc(B), len(B)."""
    if len2 == 0:
        return crc1
    odd = [0xEDB88320] + [1 << n for n in range(31)]
    even = gf2_square(odd)
    odd = gf2_square(even)
    while True:
        even = gf2_square(odd)
        if len2 & 1:
            crc1 = gf2_times(even, crc1)
        len2 >>= 1
        if not len2:
            break
        odd = gf2_square(even)
        if len2 & 1:
            crc1 = gf2_times(odd, crc1)
        len2 >>= 1
        if not len2:
            break
    return crc1 ^ crc2


def num(s):
    return int(s, 0)


def main():
    tree = ET.parse(sys.argv[1])
    rows = {}
    for sw in tree.getroot().iter("software"):
        for part in sw.iter("part"):
            if part.get("interface") != "sms_cart":
                continue
            slot = "rom"
            for f in part.iter("feature"):
                if f.get("name") == "slot":
                    slot = f.get("value")
            roms, ram = [], 0
            for da in part.iter("dataarea"):
                if da.get("name") == "rom":
                    for r in da.iter("rom"):
                        if r.get("crc") and r.get("size"):
                            roms.append((num(r.get("offset", "0")), num(r.get("size")),
                                         int(r.get("crc"), 16)))
                elif da.get("name") == "ram":
                    ram = num(da.get("size"))
            if not roms:
                continue
            roms.sort()
            crc = roms[0][2]
            for _, size, c in roms[1:]:
                crc = crc32_combine(crc, c, size)
            kind = KINDS.get(slot, "SMSMAP_UNSUPPORTED")
            prev = rows.get(crc)
            if prev and prev != (kind, ram // 1024):
                print("mkmapdb: CRC %08X is %s and %s; keeping the first"
                      % (crc, prev, (kind, ram // 1024)), file=sys.stderr)
                continue
            rows[crc] = (kind, ram // 1024, sw.get("name"))

    out = sys.stdout
    out.write("/* GENERATED by pico/sms/tools/mkmapdb.py from MAME hash/sms.xml"
              " (CC0-1.0) -- do not edit. */\n\n")
    out.write('#include "smsmap_db.h"\n\n')
    out.write("const smsmap_db_t smsmap_db[] = {\n")
    for crc in sorted(rows):
        kind, ram_kb, name = rows[crc]
        out.write("    { 0x%08Xu, %s, %u },  /* %s */\n" % (crc, kind, ram_kb, name))
    out.write("};\n\n")
    out.write("const unsigned smsmap_db_count = sizeof smsmap_db / sizeof smsmap_db[0];\n")


if __name__ == "__main__":
    main()
