#!/usr/bin/env python3
"""Pack the resident client into the C array the cart serves at power-on.

    tools/mkromh.py build/config.sms > build/gen/fujiconfigrom.h
"""
import sys

if len(sys.argv) != 2:
    sys.exit("usage: mkromh.py <client.sms>")

data = open(sys.argv[1], "rb").read()
# The cart serves CONFIG straight out of RP2350 SRAM at $0000-$7FFF, so it is
# one flat 32K image carrying the claim and a valid SEGA header.
if len(data) != 0x8000 or data[0x7FF0:0x7FF8] != b"TMR SEGA" or data[0x7FDC:0x7FE0] != b"FUJI":
    sys.exit("%s: not a 32K claimed SMS client (run tools/checkrom.py)" % sys.argv[1])

print("/* fujiconfigrom.h -- GENERATED by tools/mkromh.py from %s, do not edit. */"
      % sys.argv[1].split("/")[-1])
print()
print("#ifndef FUJICONFIGROM_H")
print("#define FUJICONFIGROM_H")
print()
print("#define FUJI_CONFIGROM_SIZE %d" % len(data))
print()
print("static const unsigned char _configrom[FUJI_CONFIGROM_SIZE] = {")
for i in range(0, len(data), 12):
    print("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
print("};")
print()
print("#endif /* FUJICONFIGROM_H */")
