#!/usr/bin/env bash
# build.sh -- assemble the ColecoVision console-side clients.
#
#   ./build.sh                 every client in testrom/ -> build/*.bin
#   ./build.sh fujitest        just that one
#
# Unlike its siblings this port builds in C, with z88dk's +coleco target and
# the user's own OS7 BIOS binding library (os7lib). That is not a shortcut:
# "use OS7 for everything" is the design, the ColecoVision window is 32K rather
# than 8K so C's overhead is affordable, and os7lib already wraps mode_1,
# load_ascii, put_vram, init_writer/writer, poller and decoder.
#
# Environment overrides:
#   Z88DK      z88dk root      (default ~/Workspace/z88dk)
#   OS7LIB     os7lib checkout (default ~/Workspace/os7lib)
#   BOOT_HOST  fujiboot's host slot   (default 0)
#   BOOT_PATH  fujiboot's image path  (default /soak.bin)

set -euo pipefail
cd "$(dirname "$0")"

Z88DK=${Z88DK:-$HOME/Workspace/z88dk}
OS7LIB=${OS7LIB:-$HOME/Workspace/os7lib}
export ZCCCFG="$Z88DK/lib/config"
export PATH="$Z88DK/bin:$PATH"

WINDOW=32768
ROM_TOP=0x7800
CLAIM_OFF=0x7CFC
# appmake's fences are absolute console addresses, not image offsets.
FENCE=0xF800

[ -x "$Z88DK/bin/zcc" ] || { echo "no zcc at $Z88DK/bin/zcc" >&2; exit 1; }
[ -f "$OS7LIB/os7.lib" ] || { echo "no os7.lib at $OS7LIB" >&2; exit 1; }

mkdir -p build

# The link line is colecovision-targ's, which is a shipped game's, plus three
# additions:
#   -Cz--romsize/--rombase   force exactly 32768 bytes based at $8000;
#   --code-fence/--data-fence  warn if anything reaches the mailbox pages.
#     appmake only WARNS on a fence breach (src/appmake/rom.c), so the real
#     enforcement is tools/checkrom.py -- the fence just makes it visible
#     earlier, with a section name attached;
#   CLIB_DEFAULT_SCREEN_MODE=-1  keeps the crt0's tms99x8 init out of the way
#     so os7lib's mode_1 owns the VDP.
CFLAGS="+coleco -O2 -I$OS7LIB/src -Itestrom"
LDFLAGS="+coleco -m -s \
  -pragma-define:CRT_ORG_BSS=0x702C \
  -pragma-define:CRT_COLECO_SPRITE_NAME_SIZE=128 \
  -pragma-define:CRT_COLECO_SPRITE_ORDER_SIZE=32 \
  -pragma-define:CRT_COLECO_BIOS_BUFFER_SIZE=32 \
  -pragma-define:CRT_COLECO_BIOS_CONTROLLER_SIZE=12 \
  -pragma-define:CRT_ENABLE_STDIO=0 \
  -pragma-define:REGISTER_SP=0x73B8 \
  -pragma-define:CLIB_FOPEN_MAX=0 \
  -pragma-define:fputc_cons=0 \
  -pragma-define:CLIB_DEFAULT_SCREEN_MODE=-1 \
  -Cz--romsize=$WINDOW -Cz--rombase=$WINDOW \
  -Cz--code-fence=$FENCE -Cz--data-fence=$FENCE \
  -L$OS7LIB -los7"

gen_bootcfg() {
    cat > build/bootcfg.h <<EOF
/* GENERATED by build.sh -- do not edit. */
#ifndef BOOTCFG_H
#define BOOTCFG_H
#define BOOT_HOST ${BOOT_HOST:-0}
#define BOOT_PATH "${BOOT_PATH:-/soak.bin}"
#endif
EOF
}

# Shared client sources. Kept as one list rather than a library because the
# whole set is a few hundred lines and every client wants all of it.
SHARED="fujidisp.c fujilib.c fujiin.c fujisnd.c fujiedit.c fujisplash.c fujisplash_data.c"

build_one() {
    local name=$1
    [ -f "testrom/$name.c" ] || { echo "no testrom/$name.c" >&2; exit 1; }
    [ "$name" = fujiboot ] && gen_bootcfg

    rm -f "build/$name.bin"
    # shellcheck disable=SC2086
    (cd testrom && zcc $CFLAGS $LDFLAGS -I../build \
        "$name.c" $SHARED -o "../build/$name" -create-app)
    mv "build/$name.rom" "build/$name.bin" 2>/dev/null || \
        mv "build/$name" "build/$name.bin"
    python3 tools/checkrom.py --stamp "build/$name.bin"
}

# With no arguments, build every client that exists -- fujicfg has not been
# written yet and a missing one must not fail the default build.
targets=("$@")
if [ ${#targets[@]} -eq 0 ]; then
    targets=()
    for t in hello fujitest fujiboot fujicfg; do
        [ -f "testrom/$t.c" ] && targets+=("$t")
    done
fi
for t in "${targets[@]}"; do
    build_one "$t"
done
