#!/usr/bin/env bash
# build.sh -- assemble the Arcadia console clients with Macroassembler AS.
#
# Usage: ./build.sh [client ...]        default: fujitest fujiboot fujicfg
#
# Output: build/<client>.bin, always exactly 8192 bytes: image 0x0000-0x0FFF
# is CPU $0000-$0FFF (block 1) and image 0x1000-0x1FFF is CPU $2000-$2FFF
# (block 2). The assembler works in CPU addresses; p2bin emits a $0000-$2FFF
# flat and tools/mkimage.py folds it, rejecting code in the $1000-$1FFF
# console-RAM hole or the $2B00-$2FFF mailbox pages. The "FUJI" claim is
# stamped at image 0x1CFC and checkrom.py enforces the final layout (see
# firmware/include/fuji_mailbox.h).
#
# fujiboot takes its target from the environment:
#   BOOT_HOST=0 BOOT_PATH=/game.bin ./build.sh fujiboot
#
# AS: a native asl on PATH first, then ~/asl (the CI build location), then
# the Windows binaries under wine -- the same ladder as pico/o2/build.sh
# (AS is not packaged for Arch).

set -euo pipefail
cd "$(dirname "$0")"

CLAIM_OFF=$((0x1CFC))

AS_BIN="${AS_BIN:-$HOME/Workspace/o2workspace/bin}"
if command -v asl >/dev/null 2>&1; then
    AS=asl P2BIN=p2bin
elif [ -x "$HOME/asl/asl" ]; then
    AS="$HOME/asl/asl" P2BIN="$HOME/asl/p2bin"
else
    AS="wine $AS_BIN/asw.exe" P2BIN="wine $AS_BIN/p2bin.exe"
    export WINEDEBUG=-all
fi

mkdir -p build

# fujiboot's baked-in target, regenerated every run so a stale value cannot
# survive an environment change.
gen_bootcfg() {
    {
        echo "; generated by build.sh -- do not edit"
        echo "BOOTHST EQU     ${BOOT_HOST:-0}"
        printf 'BOOTPTH:DB      "%s"\n' "${BOOT_PATH:-/fujitest.bin}"
        echo "        DB      0"
    } > build/bootcfg.inc
}

build_one() {
    local name=$1
    [ "$name" = fujiboot ] && gen_bootcfg
    # AS resolves INCLUDE against the cwd, so assemble from testrom/.
    (cd testrom && $AS -q -L "$name.asm")
    mv "testrom/$name.p" "build/$name.p"
    mv -f "testrom/$name.lst" "build/$name.lst" 2>/dev/null || true
    $P2BIN "build/$name.p" "build/$name.flat" -r '$0000-$2FFF' -l 0
    python3 tools/mkimage.py "build/$name.flat" "build/$name.bin"
    printf 'FUJI' | dd of="build/$name.bin" bs=1 seek=$CLAIM_OFF \
        conv=notrunc status=none
    rm -f "build/$name.p" "build/$name.flat"
    python3 tools/checkrom.py "build/$name.bin"
}

clients=("$@")
[ ${#clients[@]} -eq 0 ] && clients=(fujitest fujiboot fujicfg)
for client in "${clients[@]}"; do
    build_one "$client"
done
